### ISSUE TITLE
[Deployment Issue] caprover serversetup error

### ISSUE THREAD

**Issue by zylstra** [caprover/caprover#1085]
**What is the problem?**
At the caprover serversetup instruction in Step 3 I get the error:
`/usr/local/lib/node_modules/caprover/node_modules/update-notifier/index.js:2
const {spawn} = require('child_process');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/caprover/built/commands/caprover.js:6:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)`

**If applicable, content of `captain-definition` file:**
I do not know where this file is.

**Steps to reproduce the problem:**
Type caprover serversetup at the command line on my laptop.

**Answers to the following questions if applicable:**
- Your OS and version?  Ubuntu 16.04.4 LTS on Windows 10
- RAM?  8 GB

**Comment by githubsaturn** [comment]
See here: https://stackoverflow.com/a/50043538

> The problem is that your version of Node.js is too old and doesn't support the latest features.

Make sure your node version is at least 14
