### ISSUE TITLE
Can't start app with remote registry as dockerhub

### ISSUE THREAD

**Issue by alexander-potemkin** [caprover/caprover#1110]
I'm trying to setup an app with cluster configured on it, but failing to do so with the error:

> Failed: Error: Push failed: {"message":"unauthorized: authentication required"}unauthorized: authentication required

I successfully verified the credentials are correct, as per the troubleshooting step I [found in issues](https://github.com/caprover/caprover/issues/110#issuecomment-357076020) earlier.

<img width="915" alt="Screenshot 2021-05-21 at 20 33 24" src="https://user-images.githubusercontent.com/2323840/119177109-84af8480-ba74-11eb-8d7d-6f7711eae6d6.png">

Caprover logs attached below. As there is no request dump in the logs, I can't tell what could go wrong...

The repository is a usual hub.docker.com with my personal credentials on my personal repository.

Any help would be much appreciated!

```
captain-captain.1.leftqbfj0s5i@servername    | May 21st 2021, 5:33:02.312 pm    Registering app started: n8n-db
captain-captain.1.leftqbfj0s5i@servername    | May 21st 2021, 5:33:02.312 pm    Error: App Name already exists. Please use a different name
captain-captain.1.leftqbfj0s5i@servername    | Error: App Name already exists. Please use a different name
captain-captain.1.leftqbfj0s5i@servername    |     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
captain-captain.1.leftqbfj0s5i@servername    |     at /usr/src/app/built/datastore/AppsDataStore.js:579:49
captain-captain.1.leftqbfj0s5i@servername    |     at new Promise (<anonymous>)
captain-captain.1.leftqbfj0s5i@servername    |     at AppsDataStore.registerAppDefinition (/usr/src/app/built/datastore/AppsDataStore.js:573:16)
captain-captain.1.leftqbfj0s5i@servername    |     at /usr/src/app/built/routes/user/apps/appdefinition/AppDefinitionRouter.js:163:10
captain-captain.1.leftqbfj0s5i@servername    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
captain-captain.1.leftqbfj0s5i@servername    |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
captain-captain.1.leftqbfj0s5i@servername    |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
captain-captain.1.leftqbfj0s5i@servername    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
captain-captain.1.leftqbfj0s5i@servername    |     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
captain-captain.1.leftqbfj0s5i@servername    | POST /api/v2/user/apps/appDefinitions/register 200 1.813 ms - 94
captain-captain.1.leftqbfj0s5i@servername    | May 21st 2021, 5:33:10.439 pm    Registering app started: test2-db
captain-captain.1.leftqbfj0s5i@servername    | May 21st 2021, 5:33:10.450 pm    Building docker image. This might take a few minutes...
captain-captain.1.leftqbfj0s5i@servername    | May 21st 2021, 5:33:10.552 pm    Docker Auth is found. Pushing the image...
captain-captain.1.leftqbfj0s5i@servername    | May 21st 2021, 5:33:13.409 pm    Error: Wrapped: unauthorized: authentication required
captain-captain.1.leftqbfj0s5i@servername    | Error: Wrapped: unauthorized: authentication required
captain-captain.1.leftqbfj0s5i@servername    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.leftqbfj0s5i@servername    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
captain-captain.1.leftqbfj0s5i@servername    |     at /usr/src/app/built/docker/DockerApi.js:477:46
captain-captain.1.leftqbfj0s5i@servername    |     at Array.forEach (<anonymous>)
captain-captain.1.leftqbfj0s5i@servername    |     at IncomingMessage.<anonymous> (/usr/src/app/built/docker/DockerApi.js:470:46)
captain-captain.1.leftqbfj0s5i@servername    |     at IncomingMessage.emit (events.js:315:20)
captain-captain.1.leftqbfj0s5i@servername    |     at addChunk (internal/streams/readable.js:309:12)
captain-captain.1.leftqbfj0s5i@servername    |     at readableAddChunk (internal/streams/readable.js:280:11)
captain-captain.1.leftqbfj0s5i@servername    |     at IncomingMessage.Readable.push (internal/streams/readable.js:223:10)
captain-captain.1.leftqbfj0s5i@servername    |     at HTTPParser.parserOnBody (_http_common.js:139:24)
captain-captain.1.leftqbfj0s5i@servername    | May 21st 2021, 5:33:13.409 pm    Error: Wrapped: {"message":"unauthorized: authentication required"}
captain-captain.1.leftqbfj0s5i@servername    | Error: Wrapped: {"message":"unauthorized: authentication required"}
captain-captain.1.leftqbfj0s5i@servername    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.leftqbfj0s5i@servername    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
captain-captain.1.leftqbfj0s5i@servername    |     at /usr/src/app/built/docker/DockerApi.js:479:46
captain-captain.1.leftqbfj0s5i@servername    |     at Array.forEach (<anonymous>)
captain-captain.1.leftqbfj0s5i@servername    |     at IncomingMessage.<anonymous> (/usr/src/app/built/docker/DockerApi.js:470:46)
captain-captain.1.leftqbfj0s5i@servername    |     at IncomingMessage.emit (events.js:315:20)
captain-captain.1.leftqbfj0s5i@servername    |     at addChunk (internal/streams/readable.js:309:12)
captain-captain.1.leftqbfj0s5i@servername    |     at readableAddChunk (internal/streams/readable.js:280:11)
captain-captain.1.leftqbfj0s5i@servername    |     at IncomingMessage.Readable.push (internal/streams/readable.js:223:10)
captain-captain.1.leftqbfj0s5i@servername    |     at HTTPParser.parserOnBody (_http_common.js:139:24)
captain-captain.1.leftqbfj0s5i@servername    | May 21st 2021, 5:33:13.410 pm    Error: Wrapped: PUSH FAILED
captain-captain.1.leftqbfj0s5i@servername    | Error: Wrapped: PUSH FAILED
captain-captain.1.leftqbfj0s5i@servername    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.leftqbfj0s5i@servername    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
captain-captain.1.leftqbfj0s5i@servername    |     at /usr/src/app/built/user/DockerRegistryHelper.js:59:42
captain-captain.1.leftqbfj0s5i@servername    |     at new Promise (<anonymous>)
captain-captain.1.leftqbfj0s5i@servername    |     at /usr/src/app/built/user/DockerRegistryHelper.js:58:28
captain-captain.1.leftqbfj0s5i@servername    |     at runMicrotasks (<anonymous>)
captain-captain.1.leftqbfj0s5i@servername    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
captain-captain.1.leftqbfj0s5i@servername    | May 21st 2021, 5:33:13.410 pm    Error: Wrapped: 
captain-captain.1.leftqbfj0s5i@servername    | {"message":"unauthorized: authentication required"}unauthorized: authentication required
captain-captain.1.leftqbfj0s5i@servername    | Error: Wrapped: 
captain-captain.1.leftqbfj0s5i@servername    | {"message":"unauthorized: authentication required"}unauthorized: authentication required
captain-captain.1.leftqbfj0s5i@servername    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.leftqbfj0s5i@servername    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
captain-captain.1.leftqbfj0s5i@servername    |     at /usr/src/app/built/user/DockerRegistryHelper.js:60:42
captain-captain.1.leftqbfj0s5i@servername    |     at new Promise (<anonymous>)
captain-captain.1.leftqbfj0s5i@servername    |     at /usr/src/app/built/user/DockerRegistryHelper.js:58:28
captain-captain.1.leftqbfj0s5i@servername    |     at runMicrotasks (<anonymous>)
captain-captain.1.leftqbfj0s5i@servername    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
captain-captain.1.leftqbfj0s5i@servername    | May 21st 2021, 5:33:15.418 pm    Error: Push failed: 
captain-captain.1.leftqbfj0s5i@servername    | {"message":"unauthorized: authentication required"}unauthorized: authentication required
captain-captain.1.leftqbfj0s5i@servername    | Error: Push failed: 
captain-captain.1.leftqbfj0s5i@servername    | {"message":"unauthorized: authentication required"}unauthorized: authentication required
captain-captain.1.leftqbfj0s5i@servername    |     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
captain-captain.1.leftqbfj0s5i@servername    |     at /usr/src/app/built/user/DockerRegistryHelper.js:61:57
captain-captain.1.leftqbfj0s5i@servername    |     at new Promise (<anonymous>)
captain-captain.1.leftqbfj0s5i@servername    |     at /usr/src/app/built/user/DockerRegistryHelper.js:58:28
captain-captain.1.leftqbfj0s5i@servername    |     at runMicrotasks (<anonymous>)
captain-captain.1.leftqbfj0s5i@servername    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
captain-captain.1.leftqbfj0s5i@servername    | POST /api/v2/user/apps/appDefinitions/register 200 4979.924 ms - 149
```

**Comment by githubsaturn** [comment]
1- Is this only an issue with one click apps? Can you create regular apps?
2- What credentials and URL are you using for your Docker registry? Take a screenshot with secret information redacted.

**Comment by alexander-potemkin** [comment]
1. Only one-click apps; empty new app created Ok.
2. Screenshot attached. Reducted - is a single word (array of characters, no extra symbols).
<img width="523" alt="Screenshot 2021-05-23 at 12 46 19" src="https://user-images.githubusercontent.com/2323840/119255553-20500a80-bbc5-11eb-8aba-f81dab90c195.png">

**Comment by githubsaturn** [comment]
Use `registry-1.docker.io` as your URL

See here: https://docs.docker.com/registry/introduction/

**Comment by alexander-potemkin** [comment]
🤦‍♂️
