### ISSUE TITLE
Random Break

### ISSUE THREAD

**Issue by maxvia87** [caprover/caprover#1133]
Hello,

Since this morning my apps are not working anymore and I cant connect to the caprover cli.

My caprover been running for months and I have deployed anything for weeks.

This is the error I get when I run `docker service logs captain-captain --since 5m`

```
captain-captain.1.vw95no0ugnng@scraper    | Captain Starting ...
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:56.429 pm    Emptying generated and temp folders.
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:56.437 pm    Ensuring directories are available on host. Started.
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:56.446 pm    Ensuring directories are available on host. Finished.
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:56.454 pm    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:56.462 pm    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:56.465 pm    Migration not needed, skipping.
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:56.474 pm    Copying fake certificates...
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:56.479 pm    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:56.480 pm    Locking NGINX configuration reloading...
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:56.499 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:56.504 pm    Captain Nginx is already running.. 
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:59.510 pm    Retrying to get NodeID for captain-nginx retry count:0
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:59.513 pm    Updating NGINX service...
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:03:59.524 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:04.525 pm    Pruning containers...
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:04.527 pm    NGINX is fully set up and working...
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:04.529 pm    Captain Certbot is already running.. 
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:04.532 pm    Updating Certbot service...
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:07.551 pm    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:09.547 pm    Pruning containers...
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:10.554 pm    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:13.559 pm    Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:16.566 pm    Retrying to get containerId for captain-certbot retry count:3
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:19.570 pm    Retrying to get containerId for captain-certbot retry count:4
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:22.574 pm    Retrying to get containerId for captain-certbot retry count:5
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:22.577 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive 
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:23.561 pm    **** Captain is initialized and ready to serve you! ****
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:24.573 pm    Error: Wrapped: Verification Failed for captain.caprover.scrapthem.com
captain-captain.1.vw95no0ugnng@scraper    | Error: Wrapped: Verification Failed for captain.caprover.scrapthem.com
captain-captain.1.vw95no0ugnng@scraper    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.vw95no0ugnng@scraper    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
captain-captain.1.vw95no0ugnng@scraper    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:54:42)
captain-captain.1.vw95no0ugnng@scraper    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.vw95no0ugnng@scraper    |     at Request.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.vw95no0ugnng@scraper    |     at ClientRequest.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at Socket.socketErrorListener (_http_client.js:469:9)
captain-captain.1.vw95no0ugnng@scraper    |     at Socket.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at emitErrorNT (internal/streams/destroy.js:106:8)
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:24.573 pm    Error: Wrapped: Error        Error: connect ECONNREFUSED 138.68.173.199:80
captain-captain.1.vw95no0ugnng@scraper    | Error: Wrapped: Error        Error: connect ECONNREFUSED 138.68.173.199:80
captain-captain.1.vw95no0ugnng@scraper    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.vw95no0ugnng@scraper    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
captain-captain.1.vw95no0ugnng@scraper    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:55:42)
captain-captain.1.vw95no0ugnng@scraper    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.vw95no0ugnng@scraper    |     at Request.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.vw95no0ugnng@scraper    |     at ClientRequest.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at Socket.socketErrorListener (_http_client.js:469:9)
captain-captain.1.vw95no0ugnng@scraper    |     at Socket.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at emitErrorNT (internal/streams/destroy.js:106:8)
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:24.574 pm    Error: Wrapped: body         undefined
captain-captain.1.vw95no0ugnng@scraper    | Error: Wrapped: body         undefined
captain-captain.1.vw95no0ugnng@scraper    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.vw95no0ugnng@scraper    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
captain-captain.1.vw95no0ugnng@scraper    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:56:42)
captain-captain.1.vw95no0ugnng@scraper    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.vw95no0ugnng@scraper    |     at Request.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.vw95no0ugnng@scraper    |     at ClientRequest.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at Socket.socketErrorListener (_http_client.js:469:9)
captain-captain.1.vw95no0ugnng@scraper    |     at Socket.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at emitErrorNT (internal/streams/destroy.js:106:8)
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:24.574 pm    Error: Wrapped: randomUuid   5317be6b-3beb-4265-9c4a-7e8f6dd773bd
captain-captain.1.vw95no0ugnng@scraper    | Error: Wrapped: randomUuid   5317be6b-3beb-4265-9c4a-7e8f6dd773bd
captain-captain.1.vw95no0ugnng@scraper    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.vw95no0ugnng@scraper    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
captain-captain.1.vw95no0ugnng@scraper    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:57:42)
captain-captain.1.vw95no0ugnng@scraper    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.vw95no0ugnng@scraper    |     at Request.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.vw95no0ugnng@scraper    |     at ClientRequest.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at Socket.socketErrorListener (_http_client.js:469:9)
captain-captain.1.vw95no0ugnng@scraper    |     at Socket.emit (events.js:315:20)
captain-captain.1.vw95no0ugnng@scraper    |     at emitErrorNT (internal/streams/destroy.js:106:8)
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:24.574 pm    Captain health check failed: #0 at captain.caprover.scrapthem.com
captain-captain.1.vw95no0ugnng@scraper    | June 18th 2021, 1:04:24.575 pm    NGINX health check failed: #0
```
I havent touched anything in my domain settings neithe. Any idea what is happening?

Thank you

**Comment by githubsaturn** [comment]
It means that your server is not able to verify your domain.  Either something is your DNS settings have changed, or the networking stack of your server have changed. It doesn't break by itself.  

Temporarily until you find the problem, you can disable self verification:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by githubsaturn** [comment]
Your logs look fine. What do you mean by it's not working? Can you not access the dashboard?

**Comment by maxvia87** [comment]
Yes I cant access the dashboard nor can make requests to the apps running on the caprover instance. When I do `docker service logs captain-nginx --since 2m` this is what I see : 

` 2021/06/18 17:15:25 [emerg] 1#1: host not found in upstream "puma" in /etc/nginx/conf.d/captain.conf:97
` 

I dont understand why this is happening has I havent made any change

**Comment by githubsaturn** [comment]
What's the output of this:
curl -v https://captain.yourdomain.com

**Comment by githubsaturn** [comment]
Also, shell into your nginx container and run

cat /etc/nginx/conf.d/captain.conf

**Comment by maxvia87** [comment]
> What's the output of this:
> curl -v https://captain.yourdomain.com

Could not resolve host:

**Comment by maxvia87** [comment]
when I do curl -v https://mydomain.com 

`* TCP_NODELAY set
* Connection failed
* connect to 138.68.173.199 port 443 failed: Connection refused
* Failed to connect to scrapthem.com port 443: Connection refused`

**Comment by githubsaturn** [comment]
> > What's the output of this:
> > curl -v https://captain.yourdomain.com
> 
> Could not resolve host:

This is a big problem. It's a dns issue. Your captain url must be resolved to the ip address of your server

**Comment by maxvia87** [comment]
> > > What's the output of this:
> > > curl -v https://captain.yourdomain.com
> > 
> > 
> > Could not resolve host:
> 
> This is a big problem. It's a dns issue. Your captain url must be resolved to the ip address of your server

I it weird because on my digital ocean droplet it is... 
I have an issue though, when I do `docker ps` I see that I have 2 img that keep restarting. 'caprover/certbot-sleeping:v1.6.0' and 'caprover/caprover:1.9.0'. 

On each img how can see what is the error that have them restart? 

Thank you for your help

**Comment by maxvia87** [comment]
- [ ] [
<img width="1256" alt="Screen Shot 2021-06-19 at 11 14 17" src="https://user-images.githubusercontent.com/64636974/122637544-932ea180-d0ef-11eb-9b2b-7079ad9a78e3.png">
](url)

This is my network config. Seems legit. Always been the same. I check on my registrar and everything seems fine as well but it's true when i do `curl -v https://www.scrapthem.com`. I get a `9 port 443 failed: Connection refused`

**Comment by maxvia87** [comment]
also when I do `docker service ps captain-captain --no-trunc`, I get this 
```

3dgnenb0nlis5uw2jxpwg668t   captain-captain.1       caprover/caprover:1.9.0   scraper   Running         Running 52 seconds ago                               
lopb0eelm8xw2gsncto4b1aov    \_ captain-captain.1   caprover/caprover:1.9.0   scraper   Shutdown        Failed 58 seconds ago    "task: non-zero exit (1)"   
is32w2yq1tv78oj38s0g6fukj    \_ captain-captain.1   caprover/caprover:1.9.0   scraper   Shutdown        Failed 2 minutes ago     "task: non-zero exit (1)"   
mwia7s40w5s827g76ocqai548    \_ captain-captain.1   caprover/caprover:1.9.0   scraper   Shutdown        Failed 4 minutes ago     "task: non-zero exit (1)"   
yhc3fn1s651kbcoviwcvwsgvk    \_ captain-captain.1   caprover/caprover:1.9.0   scraper   Shutdown        Failed 6 minutes ago     "task: non-zero exit (1)" 
```

**Comment by githubsaturn** [comment]
> On each img how can see what is the error that have them restart?

You can try running `docker service logs` and scroll up to find the previous container.


Looks like your container restarts every 2 minutes... So all you have to do is to run
```
docker service logs captain-captain --follow
```
And just watch the logs for 2 min to see what's failing

**Comment by maxvia87** [comment]
working, see #1138 . Thank you @githubsaturn
