### ISSUE TITLE
Unable to restore my Backup

### ISSUE THREAD

**Issue by Alfagun74** [caprover/caprover#1176]
Im currently migrating my server to another machine which has worked flawless previously. But now when i try to restore my backup this happens:

```shell
alfagun74# docker run -p 80:80 -p 443:443 -p 3000:3000 -e MAIN_NODE_IP_ADDRESS='127.0.0.1' -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover

> caprover@0.0.0 start /usr/src/app
> node ./built/server.js

Captain Starting ...
Overriding skipVerifyingDomains from /captain/data/config-override.json
Installing Captain Service ...

 Installation of CapRover is starting...
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html

 >>> Checking System Compatibility <<<
   Docker Version passed.
******* Warning *******    CapRover and Docker work best on Ubuntu - specially when it comes to storage drivers.
   X86 CPU detected.
   Total RAM 152057 MB
Pulling: nginx:1
Pulling: caprover/caprover-placeholder-app:latest
Pulling: caprover/certbot-sleeping:v1.6.0
August 29th 2021, 12:41:15.251 pm    Resuming restoration from backup...
August 29th 2021, 12:41:15.255 pm    Processing the restoration instructions...
August 29th 2021, 12:41:15.256 pm    Processing restoration instructions is done
August 29th 2021, 12:41:15.256 pm    Starting swarm at 127.0.0.1:2377
Swarm started: tgp94zsrou29sdngmo9yzdpbc
August 29th 2021, 12:41:15.897 pm    Starting restoration, phase-1.
August 29th 2021, 12:41:15.908 pm    Single node restoration detected.
August 29th 2021, 12:41:15.909 pm    Waiting for 5 seconds for things to settle...
August 29th 2021, 12:41:20.914 pm    Getting nodes info...
August 29th 2021, 12:41:20.919 pm    Remapping nodesId in config...
August 29th 2021, 12:41:20.929 pm    Config remapping done.
August 29th 2021, 12:41:20.930 pm    Setting up salt...
Installation failed.
Error: dest already exists.
    at /usr/src/app/node_modules/fs-extra/lib/move/move.js:41:31
    at /usr/src/app/node_modules/universalify/index.js:22:54
```

If i try to install it without the backup it works fine, but obviously i need my backed up stuff.

When i leave the swarm and retry to start caprover i get:

```
alfagun74# docker run -p 80:80 -p 443:443 -p 3000:3000 -e MAIN_NODE_IP_ADDRESS='127.0.0.1' -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover

> caprover@0.0.0 start /usr/src/app
> node ./built/server.js

Captain Starting ...
Overriding skipVerifyingDomains from /captain/data/config-override.json
Installing Captain Service ...

 Installation of CapRover is starting...
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html

 >>> Checking System Compatibility <<<
   Docker Version passed.
******* Warning *******    CapRover and Docker work best on Ubuntu - specially when it comes to storage drivers.
   X86 CPU detected.
   Total RAM 152057 MB
Pulling: nginx:1
Pulling: caprover/caprover-placeholder-app:latest
Pulling: caprover/certbot-sleeping:v1.6.0
August 29th 2021, 12:46:25.300 pm    Resuming restoration from backup...
August 29th 2021, 12:46:25.304 pm    Processing the restoration instructions...
August 29th 2021, 12:46:25.305 pm    Processing restoration instructions is done
August 29th 2021, 12:46:25.305 pm    Starting swarm at 127.0.0.1:2377
Swarm started: 33jjk7th7e7lpr9d3nxj55xs1
August 29th 2021, 12:46:25.947 pm    Starting restoration, phase-1.
August 29th 2021, 12:46:25.951 pm    Single node restoration detected.
August 29th 2021, 12:46:25.951 pm    Waiting for 5 seconds for things to settle...
August 29th 2021, 12:46:30.958 pm    Getting nodes info...
August 29th 2021, 12:46:30.963 pm    Remapping nodesId in config...
Installation failed.
Error: Old nodeId tgp94zsrou29sdngmo9yzdpbc for app home is not found in the map.
    at /usr/src/app/built/user/system/BackupManager.js:133:27
    at Array.forEach (<anonymous>)
    at /usr/src/app/built/user/system/BackupManager.js:118:52
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

What am i doing wrong?

Answers to the following questions where applicable:
- Debian 11 Unstable
- 142GB RAM

**Comment by Alfagun74** [comment]
Fixed it by deleting the /captain/data folder. I had it because i needed the skipVerifyingDomains Flag in the Overrides but you mustn't have this flag when restoring a backup apparently. See https://github.com/caprover/caprover/blob/master/src/user/system/BackupManager.ts#L206

**Comment by Alfagun74** [comment]
Fixed it by deleting the /captain/data folder. I had it because i needed the skipVerifyingDomains Flag in the Overrides but you mustn't have this flag when restoring a backup apparently. See https://github.com/caprover/caprover/blob/master/src/user/system/BackupManager.ts#L206
