### ISSUE TITLE
[Deployment Issue] HTTP 500 Error when trying to deploy Docker Image

### ISSUE THREAD

**Issue by kaaax0815** [caprover/caprover#1186]
What is the problem?
I want to deploy a Image to my already created app using the API

If applicable, content of POST Data:
```js
{
  response: {
    status: 500,
    statusText: "Internal Server Error",
    data: "Internal Server Error",
    headers: Headers {
  connection: "keep-alive",
  "content-length": "21",
  "content-type": "text/plain; charset=utf-8",
  date: "Mon, 06 Sep 2021 21:50:34 GMT",
  etag: 'W/"15-/6VXivhc2MKdLfIkLcUE47K6aH0"',
  server: "nginx",
  "x-powered-by": "Express"
}
  },
  config: {
    url: "redacted/api/v2/user/apps/appData/test-app",
    baseURL: undefined,
    method: "post",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      "X-Namespace": "captain",
      "X-Captain-Auth": "redacted"
    },
    params: undefined,
    data: { captainDefinitionContent: { schemaVersion: 2, imageName: "denoland/deno" } },
    timeout: undefined,
    withCredentials: undefined,
    auth: undefined,
    paramsSerializer: undefined
  }
}
```

Steps to reproduce the problem:
Get Auth Token. Works fine
Create test-app. Works fine
POST:
```js
{ schemaVersion: 2, imageName: 'denoland/deno' }
```
Get this error:
```
captain-captain.1.21gns5a77bcw@hidden        | September 6th 2021, 9:50:34.307 pm    Error: Wrapped: Trigger app build is called with no token/namespace/appName
captain-captain.1.21gns5a77bcw@hidden        | Error: Wrapped: Trigger app build is called with no token/namespace/appName
captain-captain.1.21gns5a77bcw@hidden        |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.21gns5a77bcw@hidden        |     at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
captain-captain.1.21gns5a77bcw@hidden        |     at /usr/src/app/built/injection/Injector.js:80:30
captain-captain.1.21gns5a77bcw@hidden        |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
captain-captain.1.21gns5a77bcw@hidden        |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
captain-captain.1.21gns5a77bcw@hidden        |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
captain-captain.1.21gns5a77bcw@hidden        |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
captain-captain.1.21gns5a77bcw@hidden        |     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
captain-captain.1.21gns5a77bcw@hidden        |     at param (/usr/src/app/node_modules/express/lib/router/index.js:354:14)
captain-captain.1.21gns5a77bcw@hidden        |     at param (/usr/src/app/node_modules/express/lib/router/index.js:365:14)
captain-captain.1.21gns5a77bcw@hidden        | September 6th 2021, 9:50:34.322 pm    SyntaxError: /captain/temp/image_raw/test-app/7/source_files/captain-definition: Unexpected token o in JSON at position 1
captain-captain.1.21gns5a77bcw@hidden        | SyntaxError: /captain/temp/image_raw/test-app/7/source_files/captain-definition: Unexpected token o in JSON at position 1
captain-captain.1.21gns5a77bcw@hidden        |     at JSON.parse (<anonymous>)
captain-captain.1.21gns5a77bcw@hidden        |     at Object._readFile (/usr/src/app/node_modules/jsonfile/index.js:25:16)
captain-captain.1.21gns5a77bcw@hidden        | POST /api/v2/user/apps/appData/test-app 500 16.141 ms - 21
```

Answers to the following questions if applicable:
- Your OS and version? Ubuntu 20.04
- RAM? 4GB
- Captain Version: v1.10.0

**Comment by githubsaturn** [comment]
You're not sending a valid JSON. You need double quote for all keys and single quote is not valid either.

**Comment by kaaax0815** [comment]
This is a Javascript Object not the actual JSON

**Comment by githubsaturn** [comment]
Please provide step by step where the error happens.

**Comment by kaaax0815** [comment]
I post 
```json
{
  "schemaVersion":2,
  "imageName":"denoland/deno"
}
```
to `/user/apps/appData/test-app`
with headers:
```json
{
  "Content-Type":"application/json",
  "Accept":"application/json",
  "X-Namespace":"captain",
  "X-Captain-Auth":"redacted"
}
```
then I get the log
```
captain-captain.1.21gns5a77bcw@hidden        | September 6th 2021, 9:50:34.307 pm    Error: Wrapped: Trigger app build is called with no token/namespace/appName
captain-captain.1.21gns5a77bcw@hidden        | Error: Wrapped: Trigger app build is called with no token/namespace/appName
captain-captain.1.21gns5a77bcw@hidden        |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.21gns5a77bcw@hidden        |     at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
captain-captain.1.21gns5a77bcw@hidden        |     at /usr/src/app/built/injection/Injector.js:80:30
captain-captain.1.21gns5a77bcw@hidden        |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
captain-captain.1.21gns5a77bcw@hidden        |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
captain-captain.1.21gns5a77bcw@hidden        |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
captain-captain.1.21gns5a77bcw@hidden        |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
captain-captain.1.21gns5a77bcw@hidden        |     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
captain-captain.1.21gns5a77bcw@hidden        |     at param (/usr/src/app/node_modules/express/lib/router/index.js:354:14)
captain-captain.1.21gns5a77bcw@hidden        |     at param (/usr/src/app/node_modules/express/lib/router/index.js:365:14)
captain-captain.1.21gns5a77bcw@hidden        | September 6th 2021, 9:50:34.322 pm    SyntaxError: /captain/temp/image_raw/test-app/7/source_files/captain-definition: Unexpected token o in JSON at position 1
captain-captain.1.21gns5a77bcw@hidden        | SyntaxError: /captain/temp/image_raw/test-app/7/source_files/captain-definition: Unexpected token o in JSON at position 1
captain-captain.1.21gns5a77bcw@hidden        |     at JSON.parse (<anonymous>)
captain-captain.1.21gns5a77bcw@hidden        |     at Object._readFile (/usr/src/app/node_modules/jsonfile/index.js:25:16)
captain-captain.1.21gns5a77bcw@hidden        | POST /api/v2/user/apps/appData/test-app 500 16.141 ms - 21
```

and a HTTP 500 Error Response

**Comment by githubsaturn** [comment]
Are you using the caprover api CLI command or just use your own POST implementation?

**Comment by kaaax0815** [comment]
I am using my own POST implementation using [axiod](https://deno.land/x/axiod@0.20.0-0)(uses [fetch API](https://developer.mozilla.org/docs/Web/API/Fetch_API)) on [deno](https://deno.land/)

**Comment by githubsaturn** [comment]
That's not a supported use case. Please use the official CLI tool.

My guess is you have a typo or serialization error but it's not a caprover issue.

**Comment by kaaax0815** [comment]
This error also occurs using the CLI. With Path `/user/apps/appData/test-app` with Method `POST` and JSON `{"captainDefinitionContent": { "schemaVersion": 2, "imageName": "deno-land/docker" }}`

When using `detached: 1` Query (like in the frontend) no error occurs

**Comment by kaaax0815** [comment]
I copied the request from the frontend I only get the error when not using `?detached=1`

**Comment by kaaax0815** [comment]
Small addition when not using `detached=1` param i dont get the docker error message, i get a 500 also. because e.g i use an image that doesnt exist i get `Internal Server Error` not `(HTTP code 404) unexpected - pull access denied for 3-test, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by kaaax0815** [comment]
I now know when the error occurrs

This body works:
```js
'{"captainDefinitionContent":"{\\"schemaVersion\\":2,\\"imageName\\":\\"6-test\\"}","gitHash":""}'
```

this doesnt:
```js
JSON.stringify({
  captainDefinitionContent: { schemaVersion: 2, imageName: '6-test' },
  gitHash: ''
})
// results in '{"captainDefinitionContent":{"schemaVersion":2,"imageName":"6-test"},"gitHash":""}'
```

**Comment by githubsaturn** [comment]
I've just tested this with and without detached, and it works fine. As you discovered, it's a bug in your serialization step. You can simply use CURL:
```bash
curl 'https://captain.domain.com/api/v2/user/apps/appData/qqqq?detached=1' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'x-captain-auth: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
  -H 'x-namespace: captain' \
  --data-raw '{"captainDefinitionContent":"{\"schemaVersion\":2,\"imageName\":\"nginx\"}","gitHash":""}' \
  --compressed
```
