### ISSUE TITLE
[Deployment Issue] Deploys are failing because the Dockerfile appears to be missing  

### ISSUE THREAD

**Issue by pj-simpson** [caprover/caprover#1216]
My deploys are failing when attempting to use the CLI tool. The Dockerfile is unable to be found, despite being in the same directory as the captain-definition. 

Captain definition contents: 

```
{
    "schemaVersion":2,
    "dockerfilePath": "./DockerFile"
}
```

Steps to reproduce the problem:

All recent changes are checked in and commited. There is a Dockerfile and a captain-definition file in my project root. 
'caprover deploy' command, via CLI tool. 
Select the correct machine, app, branch 

Output in my shell: 

```
------------------------- Thu Oct 07 2021 21:20:09 GMT+0000 (Coordinated Universal Time)
Build started for portal
Build has failed!
----------------------
Deploy failed!
Error: ENOENT: no such file or directory, open '/captain/temp/image_raw/portal/10/source_files/DockerFile'
```
This happens almost instantaneously, as you would imagine. 

From the server logs I can get: 
`docker service logs captain-captain --since 5m
`
```
October 7th 2021, 9:13:33.371 pm    Error: Wrapped: Trigger app build is called with no token/namespace/appName
captain-captain.1.op1unhdbf1i5@els-caprover    | Error: Wrapped: Trigger app build is called with no token/namespace/appName
captain-captain.1.op1unhdbf1i5@els-caprover    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.op1unhdbf1i5@els-caprover    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
captain-captain.1.op1unhdbf1i5@els-caprover    |     at /usr/src/app/built/injection/Injector.js:80:30
captain-captain.1.op1unhdbf1i5@els-caprover    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
captain-captain.1.op1unhdbf1i5@els-caprover    |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
captain-captain.1.op1unhdbf1i5@els-caprover    |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
captain-captain.1.op1unhdbf1i5@els-caprover    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
captain-captain.1.op1unhdbf1i5@els-caprover    |     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
captain-captain.1.op1unhdbf1i5@els-caprover    |     at param (/usr/src/app/node_modules/express/lib/router/index.js:354:14)
captain-captain.1.op1unhdbf1i5@els-caprover    |     at param (/usr/src/app/node_modules/express/lib/router/index.js:365:14)
captain-captain.1.op1unhdbf1i5@els-caprover    | POST /api/v2/user/apps/appData/portal?detached=1 200 63.527 ms - 58
captain-captain.1.op1unhdbf1i5@els-caprover    | October 7th 2021, 9:13:33.497 pm    Error: ENOENT: no such file or directory, open '/captain/temp/image_raw/portal/9/source_files/DockerFile'
captain-captain.1.op1unhdbf1i5@els-caprover    | Error: ENOENT: no such file or directory, open '/captain/temp/image_raw/portal/9/source_files/DockerFile'
captain-captain.1.op1unhdbf1i5@els-caprover    |     at Object.openSync (fs.js:498:3)
captain-captain.1.op1unhdbf1i5@els-caprover    |     at Object.readFileSync (fs.js:394:35)
captain-captain.1.op1unhdbf1i5@els-caprover    |     at /usr/src/app/built/user/ImageMaker.js:300:22
```

I have attempted logging out of the cli tool and then back in. The effect is the same.

**Comment by githubsaturn** [comment]
Miss probably you're having a spelling issue. Are you sure the F is capitalized in your filename?
