### ISSUE TITLE
502 Bad Geteway error.

### ISSUE THREAD

**Issue by amankch** [caprover/caprover#1277]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```
I can connect and visit my captain dashbaord but most of apps, which deploy here, give 502 Bad Gateway error. Statrted suudenly from today.
```
 docker service logs captain-captain --since 60m
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | Captain Starting ...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | Overriding skipVerifyingDomains from /captain/data/config-override.json
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.343 pm    Emptying generated and temp folders.
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.482 pm    Ensuring directories are available on host. Started.
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.518 pm    Ensuring directories are available on host. Finished.
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.535 pm    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.560 pm    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.579 pm    Migration not needed, skipping.
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.629 pm    Copying fake certificates...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.643 pm    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.643 pm    Locking NGINX configuration reloading...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.826 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.844 pm    Captain Nginx is already running..
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.855 pm    Updating NGINX service...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:50.884 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 79.760 ms - 69
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 304 3.111 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:55.885 pm    Pruning containers...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:55.887 pm    NGINX is fully set up and working...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:55.906 pm    Captain Certbot is already running..
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:55.913 pm    Updating Certbot service...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:42:55.956 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:43:00.940 pm    Pruning containers...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:43:04.221 pm    **** Captain is initialized and ready to serve you! ****
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 6.232 ms - 101
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | POST /api/v2/login 200 346.896 ms - 307
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 501.283 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 1205.708 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 8.216 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:43:14.219 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:43:15.886 pm    executeCommand Container: captain-certbot certbot renew --non-interactive
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 555.359 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 123.746 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 548.257 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 1153.213 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi 200 1.744 ms - 101
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | POST /api/v2/login 200 321.240 ms - 307
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi 200 2.302 ms - 301
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 285.512 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 376.035 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 1815.659 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 1830.367 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi 304 1.777 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 846.784 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi 304 1.351 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi 304 1.770 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi/logs?encoding=hex 200 974.600 ms - 6536
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET / 304 2.194 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appData/chatappapi 304 1.312 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /static/js/main.ee60e3c4.chunk.js 304 0.719 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /static/js/2.a8870b67.chunk.js 304 2.176 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /icon-512x512.png 304 0.932 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /light-theme.css 304 1.272 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /dark-theme.css 304 1.242 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:43:52.218 pm    JsonWebTokenError: jwt must be provided
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | JsonWebTokenError: jwt must be provided
captain-captain.1.gsl9w8lg15e3@SocialRecharge    |     at Object.module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:53:17)
captain-captain.1.gsl9w8lg15e3@SocialRecharge    |     at /usr/src/app/built/user/Authenticator.js:78:17
captain-captain.1.gsl9w8lg15e3@SocialRecharge    |     at new Promise (<anonymous>)
captain-captain.1.gsl9w8lg15e3@SocialRecharge    |     at Authenticator.decodeAuthToken (/usr/src/app/built/user/Authenticator.js:77:16)
captain-captain.1.gsl9w8lg15e3@SocialRecharge    |     at /usr/src/app/built/injection/Injector.js:43:14
captain-captain.1.gsl9w8lg15e3@SocialRecharge    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
captain-captain.1.gsl9w8lg15e3@SocialRecharge    |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
captain-captain.1.gsl9w8lg15e3@SocialRecharge    |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
captain-captain.1.gsl9w8lg15e3@SocialRecharge    |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
captain-captain.1.gsl9w8lg15e3@SocialRecharge    |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appDefinitions 200 1.954 ms - 62
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /light-theme.css 304 0.603 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /manifest.json 304 0.685 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /icon-512x512.png 304 0.902 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | POST /api/v2/login 200 250.847 ms - 307
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /icon-512x512.png 304 0.860 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/system/info 304 10.945 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/apps/appDefinitions 200 12.247 ms - 103834
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | GET /api/v2/user/system/versioninfo 304 852.434 ms - -
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:44:28.154 pm    Updating Load Balancer - renewAllCerts
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:44:28.154 pm    Locking NGINX configuration reloading...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:44:28.223 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:44:28.223 pm    sendReloadSignal...
captain-captain.1.gsl9w8lg15e3@SocialRecharge    | December 2nd 2021, 2:44:28.228 pm    Kill HUP Container: d5a0a83448f8679d9143f54675467d7afec107b8d3a62936d12de4e97332
```

```
 uname -a && lsb_release -a && free -h
Linux SocialRecharge 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
              total        used        free      shared  buff/cache   available
Mem:           7.8G        1.7G        4.7G         16M        1.4G        6.4G
Swap:            0B          0B          0B
```

**Comment by githubsaturn** [comment]
When you receive a 502 error from your apps, it means that your apps are malfunctioning. Nginx cannot reach out to your apps. So to debug:
- Run `docker ps` to make sure all your containers (apps) are healthy and they are running
- Get logs from your apps directly (not `captain-captain`, but `srv-captain--yourappname`)
- Identify the issue and fix it.

**Comment by amankch** [comment]
> When you receive a 502 error from your apps, it means that your apps are malfunctioning. Nginx cannot reach out to your apps. So to debug:
> 
> * Run `docker ps` to make sure all your containers (apps) are healthy and they are running
> * Get logs from your apps directly (not `captain-captain`, but `srv-captain--yourappname`)
> * Identify the issue and fix it.

Now from this morning not been able to access the dashboard also, when visiting the captain dashboard receiving the following error messages:-

Your connection is not private
Attackers might be trying to steal your information from captain.server.-----.-- (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID
