### ISSUE TITLE
Bad Gateway when deploy app with caprover

### ISSUE THREAD

**Issue by Trung229** [caprover/caprover#1304]
Hi everyone,

I am deploying an express application to Caprover, but every time i deploy that say Bad gateway although it work fine on my machine

I followed Caprover's instructions to debug [solution](https://caprover.com/docs/troubleshooting.html#successful-deploy-but-502-bad-gateway-error) I have tried all the ways it mentioned but it not only doesn't work but also slows down the loading of the app,  i hope you guys can help me

Thanks everyone

this is my log on caprover

```js
2022-01-11T13:32:45.908963040Z npm info it worked if it ends with ok
2022-01-11T13:32:45.909037503Z npm info using npm@5.4.2
2022-01-11T13:32:45.909063060Z npm info using node@v8.7.0
2022-01-11T13:32:45.963982396Z npm info lifecycle ec2decord@0.0.0~prestart: ec2decord@0.0.0
2022-01-11T13:32:45.964008005Z npm info lifecycle ec2decord@0.0.0~start: ec2decord@0.0.0
2022-01-11T13:32:45.988097533Z
2022-01-11T13:32:45.988121727Z > ec2decord@0.0.0 start /usr/src/app
2022-01-11T13:32:45.988127018Z > node ./bin/www
2022-01-11T13:32:45.988131292Z
2022-01-11T13:32:46.374987486Z /usr/src/app/node_modules/mongodb/lib/bson.js:10
2022-01-11T13:32:46.375013973Z catch { } // eslint-disable-line
2022-01-11T13:32:46.375019589Z ^
2022-01-11T13:32:46.375061444Z
2022-01-11T13:32:46.375065604Z SyntaxError: Unexpected token {
2022-01-11T13:32:46.375069896Z at createScript (vm.js:80:10)
2022-01-11T13:32:46.375074199Z at Object.runInThisContext (vm.js:139:10)
2022-01-11T13:32:46.375078328Z at Module._compile (module.js:588:28)
2022-01-11T13:32:46.375082456Z at Object.Module._extensions..js (module.js:635:10)
2022-01-11T13:32:46.375086628Z at Module.load (module.js:545:32)
2022-01-11T13:32:46.375090681Z at tryModuleLoad (module.js:508:12)
2022-01-11T13:32:46.375094769Z at Function.Module._load (module.js:500:3)
2022-01-11T13:32:46.375098886Z at Module.require (module.js:568:17)
2022-01-11T13:32:46.375103001Z at require (internal/module.js:11:18)
2022-01-11T13:32:46.375107094Z at Object.<anonymous> (/usr/src/app/node_modules/mongodb/lib/utils.js:11:16)
2022-01-11T13:32:46.384921532Z npm info lifecycle ec2decord@0.0.0~start: Failed to exec start script
2022-01-11T13:32:46.384940533Z npm ERR! code ELIFECYCLE
2022-01-11T13:32:46.384944991Z npm ERR! errno 1
2022-01-11T13:32:46.384949231Z npm ERR! ec2decord@0.0.0 start: `node ./bin/www`
2022-01-11T13:32:46.384953573Z npm ERR! Exit status 1
2022-01-11T13:32:46.384957598Z npm ERR!
2022-01-11T13:32:46.384961669Z npm ERR! Failed at the ec2decord@0.0.0 start script.
2022-01-11T13:32:46.384965901Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-01-11T13:32:46.396959360Z
2022-01-11T13:32:46.396984297Z npm ERR! A complete log of this run can be found in:
2022-01-11T13:32:46.396989577Z npm ERR! /root/.npm/_logs/2022-01-11T13_32_46_384Z-debug.log
2022-01-11T13:32:47.007971276Z npm info it worked if it ends with ok
2022-01-11T13:32:47.008805464Z npm info using npm@5.4.2
2022-01-11T13:32:47.009404973Z npm info using node@v8.7.0
2022-01-11T13:32:47.043741811Z npm info lifecycle ec2decord@0.0.0~prestart: ec2decord@0.0.0
2022-01-11T13:32:47.044506274Z npm info lifecycle ec2decord@0.0.0~start: ec2decord@0.0.0
2022-01-11T13:32:47.047728889Z
2022-01-11T13:32:47.047742649Z > ec2decord@0.0.0 start /usr/src/app
2022-01-11T13:32:47.047747877Z > node ./bin/www
2022-01-11T13:32:47.047752171Z
2022-01-11T13:32:47.247207119Z /usr/src/app/node_modules/mongodb/lib/bson.js:10
2022-01-11T13:32:47.247230070Z catch { } // eslint-disable-line
2022-01-11T13:32:47.247234998Z ^
2022-01-11T13:32:47.247239160Z
2022-01-11T13:32:47.247243180Z SyntaxError: Unexpected token {
2022-01-11T13:32:47.247247362Z at createScript (vm.js:80:10)
2022-01-11T13:32:47.247251529Z at Object.runInThisContext (vm.js:139:10)
2022-01-11T13:32:47.247255685Z at Module._compile (module.js:588:28)
2022-01-11T13:32:47.247284003Z at Object.Module._extensions..js (module.js:635:10)
2022-01-11T13:32:47.247288857Z at Module.load (module.js:545:32)
2022-01-11T13:32:47.247292967Z at tryModuleLoad (module.js:508:12)
2022-01-11T13:32:47.247297355Z at Function.Module._load (module.js:500:3)
2022-01-11T13:32:47.247301437Z at Module.require (module.js:568:17)
2022-01-11T13:32:47.247305482Z at require (internal/module.js:11:18)
2022-01-11T13:32:47.247309680Z at Object.<anonymous> (/usr/src/app/node_modules/mongodb/lib/utils.js:11:16)
2022-01-11T13:32:47.249200482Z npm info lifecycle ec2decord@0.0.0~start: Failed to exec start script
2022-01-11T13:32:47.251043650Z npm ERR! code ELIFECYCLE
2022-01-11T13:32:47.251736118Z npm ERR! errno 1
2022-01-11T13:32:47.252922453Z npm ERR! ec2decord@0.0.0 start: `node ./bin/www`
2022-01-11T13:32:47.253384646Z npm ERR! Exit status 1
2022-01-11T13:32:47.253913316Z npm ERR!
2022-01-11T13:32:47.254349466Z npm ERR! Failed at the ec2decord@0.0.0 start script.
2022-01-11T13:32:47.254770447Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-01-11T13:32:47.260288028Z
2022-01-11T13:32:47.260794581Z npm ERR! A complete log of this run can be found in:
2022-01-11T13:32:47.261203635Z npm ERR! /root/.npm/_logs/2022-01-11T13_32_47_256Z-debug.log
2022-01-11T13:32:50.701098992Z npm info it worked if it ends with ok
2022-01-11T13:32:50.701904052Z npm info using npm@5.4.2
2022-01-11T13:32:50.702492872Z npm info using node@v8.7.0
2022-01-11T13:32:50.733191167Z npm info lifecycle ec2decord@0.0.0~prestart: ec2decord@0.0.0
2022-01-11T13:32:50.733951293Z npm info lifecycle ec2decord@0.0.0~start: ec2decord@0.0.0
2022-01-11T13:32:50.736847320Z
2022-01-11T13:32:50.736860467Z > ec2decord@0.0.0 start /usr/src/app
2022-01-11T13:32:50.736866048Z > node ./bin/www
2022-01-11T13:32:50.736870352Z
2022-01-11T13:32:50.942642199Z /usr/src/app/node_modules/mongodb/lib/bson.js:10
2022-01-11T13:32:50.942672413Z catch { } // eslint-disable-line
2022-01-11T13:32:50.942713560Z ^
2022-01-11T13:32:50.942720170Z
2022-01-11T13:32:50.942724652Z SyntaxError: Unexpected token {
2022-01-11T13:32:50.942729245Z at createScript (vm.js:80:10)
2022-01-11T13:32:50.942734119Z at Object.runInThisContext (vm.js:139:10)
2022-01-11T13:32:50.942738589Z at Module._compile (module.js:588:28)
2022-01-11T13:32:50.942743088Z at Object.Module._extensions..js (module.js:635:10)
2022-01-11T13:32:50.942747755Z at Module.load (module.js:545:32)
2022-01-11T13:32:50.942752170Z at tryModuleLoad (module.js:508:12)
2022-01-11T13:32:50.942756565Z at Function.Module._load (module.js:500:3)
2022-01-11T13:32:50.942761052Z at Module.require (module.js:568:17)
2022-01-11T13:32:50.942765512Z at require (internal/module.js:11:18)
2022-01-11T13:32:50.942860519Z at Object.<anonymous> (/usr/src/app/node_modules/mongodb/lib/utils.js:11:16)
2022-01-11T13:32:50.946453911Z npm info lifecycle ec2decord@0.0.0~start: Failed to exec start script
2022-01-11T13:32:50.948021300Z npm ERR! code ELIFECYCLE
2022-01-11T13:32:50.948720427Z npm ERR! errno 1
2022-01-11T13:32:50.950013092Z npm ERR! ec2decord@0.0.0 start: `node ./bin/www`
2022-01-11T13:32:50.950444714Z npm ERR! Exit status 1
2022-01-11T13:32:50.950965318Z npm ERR!
2022-01-11T13:32:50.951403908Z npm ERR! Failed at the ec2decord@0.0.0 start script.
2022-01-11T13:32:50.951832958Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-01-11T13:32:50.956715128Z
2022-01-11T13:32:50.957215603Z npm ERR! A complete log of this run can be found in:
2022-01-11T13:32:50.957636442Z npm ERR! /root/.npm/_logs/2022-01-11T13_32_50_952Z-debug.log



```

**Comment by githubsaturn** [comment]
@Trung229  - this is an application error - meaning that there is an error with your own code.

CapRover simply runs a `docker build` command and deploys your app. What's the `captain-definition` or `Dockerfile` you're using?

**Comment by Trung229** [comment]
Hi @githubsaturn Thanks for your response,

I also noticed that I got a code error when I looked at the log of caprover, but now my local machine is running fine and there are no errors at all, only when I deploy it, it gives me an error.

this is my `captain-definition` file:

`
 {
  "schemaVersion": 2,
  "templateId": "node/8.7.0"
 }
 
`

**Comment by githubsaturn** [comment]
There could be anything that is different from your machine to your container. 
- Are you using Node 8.7 on your local machine? Maybe it's the node version. 
- Is this a frontend code or backend code?
- What's the command you use to run this on your machine? `npm start` or `npm run build` or ...

**Comment by Trung229** [comment]
- I am using node version `16.0.0`
- I think it is `BE` code
- The command I use is `yarn start`

**Comment by githubsaturn** [comment]
You're using Node 16 on your own machine, but you're deploying Node 8... that could be the issue

**Comment by githubsaturn** [comment]
Change your template to Node/16 and commit and redeploy
