### ISSUE TITLE
Cant get wildcard SSL! - already tried #1188 - Might be a Python issue

### ISSUE THREAD

**Issue by ebecaf** [caprover/caprover#1310]
Hi, my CapRover has been running for several months, no issues, however getting new SSLs seems to have an issue.

I followed https://github.com/caprover/caprover/issues/1188 and reset my SSL certificates, CapRover is now asking me to setup my root domain/ wildcard SSL on the dashboard.

When I do so, I simply get _"Something Bad Happened"_

I ran
```
docker service logs captain-captain --since 60m
```
and I saw a lot of stuff about python 3.8??

Does anyone have any similar experience with SSL issues?

Thanks for your help.

---

```
Ubuntu 20.04.3 (5.4.0-94-generic) 
```

Edit: `skipVerifyingDomains` has been set to `false` in case there was an issue there as per CapRover Docs error 1107 (though I did not get a 1107)

**Comment by ebecaf** [comment]
In my A/AAAA Records I have added subdomains for CapRover/LE to use, e.g. captain.app.example.com and *, _should I remove them_?

**Comment by ebecaf** [comment]
When running `docker exec -it $(docker ps --filter name=captain-certbot -q) certbot renew` from #1293 i get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2897, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2691, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2888, in _parsed_pkg_info
    return self._pkg_info
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2691, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3127, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2635, in requires
    dm = self._dep_map
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2899, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2908, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2890, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1798, in get_metadata
    raise KeyError("No metadata except PKG-INFO is available")
KeyError: 'No metadata except PKG-INFO is available'
```

This doesn't seem like a trivial issue... :/

**Comment by ebecaf** [comment]
```
docker service logs captain-captain --since 60m
```
Also gives:

captain-captain | at /usr/src/app/built/user/system/CertbotManager.js:97:19
captain-captain | at processTicksAndRejections (internal/process/task_queues.js:95:5)
captain-captain | POST /api/v2/user/system/enablessl 500 6737.562 ms - 21

Does this mean I need to update the Certbot Manager?

Thank you.

**Comment by githubsaturn** [comment]
The python errors that you pasted above are coming from [certbot](https://github.com/certbot/certbot), not caprover.


> Does this mean I need to update the Certbot Manager?

No.


What did you do to get into this state? Looks like your certs are completely broken now.

**Comment by ebecaf** [comment]
I followed 

> The python errors that you pasted above are coming from [certbot](https://github.com/certbot/certbot), not caprover.
> 
> > Does this mean I need to update the Certbot Manager?
> 
> No.
> 
> What did you do to get into this state? Looks like your certs are completely broken now.

I followed #1188, rebooted and that was the result I got, in fact I think I got that result before I even did 1188.

I tried to 'fix it' by deleting all the old certs in /captain/data/etc/letencrypt: /keys, /csr, /live etc. but that didn't do anything, so I put them back as I had backed them up as a tar.

Is there anything else I can do?

**Comment by githubsaturn** [comment]
#1188 is a very fragile process and it's for a specific problem. Why did you have to follow it in the first place?

Regardless, try this:
```
docker scale captain-captain=0
docker scale captain-certbot=0

cat /captain/data/config-captain.json | grep -i ssl
# do you see any "true" value here? They all must be "false"

rm -rf /captain/data/letencrypt
mkdir /captain/data/letencrypt



docker scale captain-certbot=1
docker scale captain-captain=1
```

**Comment by ebecaf** [comment]
Hi githubsaturn,

> Why did you have to follow it in the first place?

I followed it because I couldn't generate any new certs at all. Then just recently all my existing ones just ended and nothing had a valid cert. I found 1188 to be the closest to my current situation.

I manually edited and uploaded 'config-captain.json' via SFTP with the SSL values all changed to false, including the root domain.

I then ran 'caprover serversetup', it asked me for a new root domain and on the GUI I tried to get a wildcard SSL, but nothing.

Since I opened this issue I've upgraded my Ubuntu 20.04 to 21.10 in the hopes of fixing any issues related to 20.04, but that's still a no-go. 

I can still create 'apps', manage them etc. but nothing about SSL works.

I'll try your recommendations and report back, thank you.

**Comment by ebecaf** [comment]
I get:
`docker: 'scale' is not a docker command.`

**Comment by githubsaturn** [comment]
Ah, I had a typo. I edited the commands above. Run these and let me know what you're getting.

**Comment by ebecaf** [comment]
Hi, here is what I got:

```
my-user@app:/home/my-user# docker service scale captain-captain=0
captain-captain scaled to 0
overall progress: 0 out of 0 tasks 
verify: Service converged 
my-user@app:/home/my-user# docker service scale captain-certbot=0
captain-certbot scaled to 0
overall progress: 0 out of 0 tasks 
verify: Service converged 
my-user@app:/home/my-user# cat /captain/data/config-captain.json | grep -i ssl
        "hasRootSsl": false,
        "forceRootSsl": false,
                        "hasDefaultSubDomainSsl": false,
                        "forceSsl": false,
                        "hasDefaultSubDomainSsl": false,
                        "forceSsl": false,
                        "hasDefaultSubDomainSsl": false,
                        "forceSsl": false,
                        "hasDefaultSubDomainSsl": false,
                        "forceSsl": false,
                        "hasDefaultSubDomainSsl": false,
                        "forceSsl": false,
                        "hasDefaultSubDomainSsl": false,
                        "forceSsl": false,
                        "hasDefaultSubDomainSsl": false,
                        "forceSsl": false,
                        "hasDefaultSubDomainSsl": false,
                        "forceSsl": false,
my-user@app:/home/my-user# rm -rf /captain/data/letencrypt
my-user@app:/home/my-user# mkdir /captain/data/letencrypt
my-user@app:/home/my-user# docker service scale captain-certbot=1
captain-certbot scaled to 1
overall progress: 0 out of 1 tasks 
1/1: invalid mount config for type "bind": bind source path does not exist:
```

Currently in a loop on that last line.

**Comment by githubsaturn** [comment]
run `docker service scale captain-captain=1` first, then scale certbot

**Comment by ebecaf** [comment]
Sorry, I must have missed that.

I get:
`verify: Service converged`

Should I run caprover's CLI setup?

**Comment by githubsaturn** [comment]
What do you get when you run `docker ps` ?

**Comment by ebecaf** [comment]
A big list of the running dockers including certbot which is (possibly) sleeping.

**Comment by githubsaturn** [comment]
Check the uptime to make sure that `captain-*` containers aren't restarting, if everything is okay, run `caprover setup`.

If you see an error when you run `caprover setup`, on your server run `docker service logs captain-captain --since 5m` to see what's happening.

**Comment by ebecaf** [comment]
Looks like they aren't restarting, I just re-ran `docker ps` and they haven't restarted

<img width="1290" alt="Screenshot docker caprover" src="https://user-images.githubusercontent.com/91161208/149629088-1e24df85-b8c8-4c70-b978-cac75f1d9d8f.png">

**Comment by ebecaf** [comment]
Okay, so I've had this a few times, but it doesn't seem to solve anything:

`You may have already setup the server with root domain: (cap.example.com)! Use caprover login to log into an existing server.`

Then I go to the GUI and fill out this, but _always_ get `Something Bad Happened`
<img width="618" alt="Screenshot 2022-01-15 at 16 21 02" src="https://user-images.githubusercontent.com/91161208/149629307-3c67f523-5b6e-4895-bfcb-1222cf3f7877.png">

Here's the log:
```
  GET / 304 1.279 ms - -
  GET /static/js/2.a8870b67.chunk.js 304 1.237 ms - -
  GET /static/js/main.ee60e3c4.chunk.js 304 0.944 ms - -
  GET /icon-512x512.png 304 1.080 ms - -
  GET /dark-theme.css 304 0.857 ms - -
  GET /dark-theme.css 304 0.866 ms - -
  GET /light-theme.css 304 1.045 ms - -
  January 15th 2022, 4:20:27.367 pm    JsonWebTokenError: jwt must be provided
  JsonWebTokenError: jwt must be provided
      at Object.module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:53:17)
      at /usr/src/app/built/user/Authenticator.js:78:17
      at new Promise (<anonymous>)
      at Authenticator.decodeAuthToken (/usr/src/app/built/user/Authenticator.js:77:16)
      at /usr/src/app/built/injection/Injector.js:43:14
      at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
      at /usr/src/app/node_modules/express/lib/router/index.js:284:7
      at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
      at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
  GET /api/v2/user/system/info 200 2.622 ms - 62
  POST /api/v2/login 200 335.777 ms - 307
  GET /api/v2/user/system/info 200 6.896 ms - 129
  GET /api/v2/user/system/versioninfo 304 526.420 ms - -
  January 15th 2022, 4:21:05.649 pm    executeCommand Container: captain-certbot certbot register --email my-email@example.com --agree-tos --no-eff-email --non-interactive 
  January 15th 2022, 4:21:06.212 pm    Error: Unexpected output when registering with ACME Certbot 
   Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2897, in _dep_map
      return self.__dep_map
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2691, in __getattr__
      raise AttributeError(attr)
  AttributeError: _DistInfoDistribution__dep_map
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2888, in _parsed_pkg_info
      return self._pkg_info
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2691, in __getattr__
      raise AttributeError(attr)
  AttributeError: _pkg_info
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/bin/certbot", line 6, in <module>
      from pkg_resources import load_entry_point
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3127, in <module>
      def _initialize_master_working_set():
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
      f(*args, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
      working_set = WorkingSet._build_master()
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
      ws.require(__requires__)
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 898, in require
      needed = self.resolve(parse_requirements(requirements))
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
      new_requirements = dist.requires(req.extras)[::-1]
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2635, in requires
      dm = self._dep_map
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2899, in _dep_map
      self.__dep_map = self._compute_dependencies()
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2908, in _compute_dependencies
      for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2890, in _parsed_pkg_info
      metadata = self.get_metadata(self.PKG_INFO)
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1798, in get_metadata
      raise KeyError("No metadata except PKG-INFO is available")
  KeyError: 'No metadata except PKG-INFO is available'
  
  Error: Unexpected output when registering with ACME Certbot 
   Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2897, in _dep_map
      return self.__dep_map
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2691, in __getattr__
      raise AttributeError(attr)
  AttributeError: _DistInfoDistribution__dep_map
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2888, in _parsed_pkg_info
      return self._pkg_info
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2691, in __getattr__
      raise AttributeError(attr)
  AttributeError: _pkg_info
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/bin/certbot", line 6, in <module>
      from pkg_resources import load_entry_point
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3127, in <module>
      def _initialize_master_working_set():
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
      f(*args, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
      working_set = WorkingSet._build_master()
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
      ws.require(__requires__)
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 898, in require
      needed = self.resolve(parse_requirements(requirements))
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
      new_requirements = dist.requires(req.extras)[::-1]
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2635, in requires
      dm = self._dep_map
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2899, in _dep_map
      self.__dep_map = self._compute_dependencies()
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2908, in _compute_dependencies
      for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2890, in _parsed_pkg_info
      metadata = self.get_metadata(self.PKG_INFO)
    File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1798, in get_metadata
      raise KeyError("No metadata except PKG-INFO is available")
  KeyError: 'No metadata except PKG-INFO is available'
  
      at /usr/src/app/built/user/system/CertbotManager.js:97:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
  POST /api/v2/user/system/enablessl 500 575.604 ms - 21
```

**Comment by githubsaturn** [comment]
What's your OS? Are you self-hosting or using a vps? Which vps?

I'll look into this.

**Comment by githubsaturn** [comment]
After some investigation, it looks like it's similar to #1297

If you can send me your OS and your VPS provider, I can run some test to see what's going on.

**Comment by ebecaf** [comment]
Hi,

It's Ubuntu 21.10 5.13.0-25-generic x86_64 (upgraded from 20.04 - after this all started happening). Linode, 2GB VPS.

Thank you.

On a side note, after posting this issue, I created a fresh Ubuntu 21.10 Linode 1GB ('nanode'), redirected a new subdomain, installed docker and setup CapRover no problem. So now I'm just left a bit confused!

**Comment by githubsaturn** [comment]
Ah I see. It's not reproducible yet. That means it's not a CapRover issue, most likely there was an issue with that node, either a disk issue or an OS issue.

**Comment by ebecaf** [comment]
Ah, that's interesting. Could you help me understand how a disk issue would affect the container's ability to get an SSL? Maybe there's a way I can fix this.

**Comment by githubsaturn** [comment]
Disk issue was just a guess since other factors are out.
The CapRover's certbot-sleeping image hasn't been updated [in the past year](https://hub.docker.com/r/caprover/certbot-sleeping/tags). Hence it can't be just misbehaving on itself. Since you also fully cleaned up the directory and still it failed, it also invalidates possibility of some bad configuration that messed up your Let'sEncrypt files. 

What could be happening is that somehow the disk that was mapped to `/captain` directory was corrupted. Hence, Let's Encrypt files kept being corrupted even after a complete removal and restarting. 

If there was an issue with the image, creating a new instance should have resulted in the same issue.

**Comment by ebecaf** [comment]
Reopening this as now facing the same issue.

I created a new server at the time of my last post, Ubuntu 21.10 - I installed Docker and CapRover (using Linode). No issues.

I Restored a backup because the n8n app was having issues, and now this is happening:

```
1107 : Unexpected output when enabling SSL for flow.app.MYDOMAIN.com with ACME Certbot Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2897, in _dep_map return self.__dep_map File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2691, in __getattr__ raise AttributeError(attr) AttributeError: _DistInfoDistribution__dep_map During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2888, in _parsed_pkg_info return self._pkg_info File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2691, in __getattr__ raise AttributeError(attr) AttributeError: _pkg_info During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/bin/certbot", line 6, in <module> from pkg_resources import load_entry_point File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3127, in <module> def _initialize_master_working_set(): File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside f(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set working_set = WorkingSet._build_master() File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master ws.require(__requires__) File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 898, in require needed = self.resolve(parse_requirements(requirements)) File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve new_requirements = dist.requires(req.extras)[::-1] File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2635, in requires dm = self._dep_map File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2899, in _dep_map self.__dep_map = self._compute_dependencies() File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2908, in _compute_dependencies for req in self._parsed_pkg_info.get_all('Requires-Dist') or []: File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2890, in _parsed_pkg_info metadata = self.get_metadata(self.PKG_INFO) File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1798, in get_metadata raise KeyError("No metadata except PKG-INFO is available") KeyError: 'No metadata except PKG-INFO is available'
```

Perhaps this is a Linode issue? Has anyone else had issues with restoring??

**Comment by ebecaf** [comment]
In all of my apps I get the same message in the App Logs box:

`Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node v2o9ita4nj********a3zhb6c is not available`

Is there something I can do to _'reattach'_ the missing container/node?

**Comment by githubsaturn** [comment]
> Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node v2o9ita4nj********a3zhb6c is not available

This error is thrown by Docker, not CapRover. There are hundreds, if not thousands of reasons that could cause this. It could be a bad kernel (OS), or a disk or network problem. See this issue for example: https://github.com/moby/moby/issues/35011
