### ISSUE TITLE
[Question] Caprover won't start after restoring from backup

### ISSUE THREAD

**Issue by marcusique** [caprover/caprover#1373]
Hi,

Due to failure with internal storage on my Raspberry Pi (Ubuntu / aarch64) I re-imaged OS from backup onto a new internal storage. Now, the Caprover won't start due to a number of errors "failed to load container mount – mount does not exist". 
When I try to restart Caprover using _sudo docker service update captain-captain --force_, it throws "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

Here's some additional info

`sudo service docker status`
```
docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com

Mar 16 14:14:37 mrk-srv.local systemd[1]: Dependency failed for Docker Application Container Engine.
Mar 16 14:14:37 mrk-srv.local systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Mar 16 14:14:42 mrk-srv.local systemd[1]: Dependency failed for Docker Application Container Engine.
Mar 16 14:14:42 mrk-srv.local systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Mar 16 14:14:47 mrk-srv.local systemd[1]: Dependency failed for Docker Application Container Engine.
Mar 16 14:14:47 mrk-srv.local systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Mar 16 14:14:53 mrk-srv.local systemd[1]: Dependency failed for Docker Application Container Engine.
Mar 16 14:14:53 mrk-srv.local systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Mar 16 14:14:58 mrk-srv.local systemd[1]: Dependency failed for Docker Application Container Engine.
Mar 16 14:14:58 mrk-srv.local systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
```

`sudo dockerd`
```
INFO[2022-03-16T14:16:49.079249809+01:00] Starting up                                  
INFO[2022-03-16T14:16:49.082814891+01:00] libcontainerd: started new containerd process  pid=8719
INFO[2022-03-16T14:16:49.082963334+01:00] parsed scheme: "unix"                         module=grpc
INFO[2022-03-16T14:16:49.083002370+01:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2022-03-16T14:16:49.083071832+01:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2022-03-16T14:16:49.083132165+01:00] ClientConn switching balancer to "pick_first"  module=grpc
WARN[0000] deprecated version : `1`, please switch to version `2` 
INFO[2022-03-16T14:16:49.133711737+01:00] starting containerd                           revision=2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc version=1.5.10
INFO[2022-03-16T14:16:49.215302954+01:00] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2022-03-16T14:16:49.215544358+01:00] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
INFO[2022-03-16T14:16:49.221579112+01:00] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
INFO[2022-03-16T14:16:49.222370842+01:00] skip loading plugin "io.containerd.snapshotter.v1.btrfs"...  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs (ext4) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2022-03-16T14:16:49.222486822+01:00] loading plugin "io.containerd.snapshotter.v1.devmapper"...  type=io.containerd.snapshotter.v1
WARN[2022-03-16T14:16:49.222569080+01:00] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
INFO[2022-03-16T14:16:49.222641153+01:00] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2022-03-16T14:16:49.222802114+01:00] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2022-03-16T14:16:49.223369236+01:00] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2022-03-16T14:16:49.223992376+01:00] skip loading plugin "io.containerd.snapshotter.v1.zfs"...  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2022-03-16T14:16:49.224076393+01:00] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2022-03-16T14:16:49.224169985+01:00] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
INFO[2022-03-16T14:16:49.224236817+01:00] metadata content store policy set             policy=shared
INFO[2022-03-16T14:16:49.224754996+01:00] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2022-03-16T14:16:49.224845587+01:00] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2022-03-16T14:16:49.224995326+01:00] loading plugin "io.containerd.service.v1.introspection-service"...  type=io.containerd.service.v1
INFO[2022-03-16T14:16:49.225122398+01:00] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2022-03-16T14:16:49.225194749+01:00] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2022-03-16T14:16:49.225258581+01:00] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2022-03-16T14:16:49.225325210+01:00] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2022-03-16T14:16:49.225395876+01:00] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2022-03-16T14:16:49.225460468+01:00] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2022-03-16T14:16:49.225523467+01:00] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2022-03-16T14:16:49.225583336+01:00] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2022-03-16T14:16:49.226117033+01:00] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2022-03-16T14:16:49.226441084+01:00] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2022-03-16T14:16:49.227951379+01:00] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2022-03-16T14:16:49.228097655+01:00] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2022-03-16T14:16:49.228312671+01:00] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.228386373+01:00] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.228458317+01:00] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.228522946+01:00] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.228583797+01:00] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.228646963+01:00] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.231255761+01:00] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.231373723+01:00] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.231448296+01:00] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2022-03-16T14:16:49.231654034+01:00] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.231745885+01:00] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.231816532+01:00] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.231875087+01:00] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2022-03-16T14:16:49.232731649+01:00] serving...                                    address=/var/run/docker/containerd/containerd-debug.sock
INFO[2022-03-16T14:16:49.233044590+01:00] serving...                                    address=/var/run/docker/containerd/containerd.sock.ttrpc
INFO[2022-03-16T14:16:49.233271864+01:00] serving...                                    address=/var/run/docker/containerd/containerd.sock
INFO[2022-03-16T14:16:49.233347382+01:00] containerd successfully booted in 0.101934s  
INFO[2022-03-16T14:16:49.248203000+01:00] detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf 
INFO[2022-03-16T14:16:49.250215511+01:00] parsed scheme: "unix"                         module=grpc
INFO[2022-03-16T14:16:49.250340213+01:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2022-03-16T14:16:49.250410693+01:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2022-03-16T14:16:49.250452656+01:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2022-03-16T14:16:49.252528036+01:00] parsed scheme: "unix"                         module=grpc
INFO[2022-03-16T14:16:49.252612664+01:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2022-03-16T14:16:49.252754051+01:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}  module=grpc
INFO[2022-03-16T14:16:49.252802625+01:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2022-03-16T14:16:49.446300436+01:00] [graphdriver] using prior storage driver: overlay2 
WARN[2022-03-16T14:16:49.766050503+01:00] Your kernel does not support cgroup memory limit 
WARN[2022-03-16T14:16:49.766132872+01:00] Your kernel does not support CPU realtime scheduler 
WARN[2022-03-16T14:16:49.766166798+01:00] Your kernel does not support cgroup blkio weight 
WARN[2022-03-16T14:16:49.766198705+01:00] Your kernel does not support cgroup blkio weight_device 
INFO[2022-03-16T14:16:49.766662902+01:00] Loading containers: start.                   
ERRO[2022-03-16T14:16:49.773105984+01:00] failed to load container mount                container=d7cb4065a09def4d01cbfbbc565dc36c34e764daf7d11ef840116c96c420450b error="mount does not exist"
ERRO[2022-03-16T14:16:49.776435866+01:00] failed to load container mount                container=38025f49a9b18caf75c35dfff4804088f45774e1ec1909dc48ab24d3cfb1a977 error="mount does not exist"
ERRO[2022-03-16T14:16:49.777008247+01:00] failed to load container mount                container=a731efe109006eb8315aa13bdd66eace9c1a85b15747211164ebe95af015f8ed error="mount does not exist"
ERRO[2022-03-16T14:16:49.777742626+01:00] failed to load container mount                container=cb16c1d9df05a28723e763739b87e5c2cb3086711a5ccb8a6d0fa8bae7c02fac error="mount does not exist"
ERRO[2022-03-16T14:16:49.780205908+01:00] failed to load container mount                container=a53eb4631e9fd45da7ae35999a153b6c33b97cef224ccab117d25e5354b46adb error="mount does not exist"
INFO[2022-03-16T14:16:50.409018705+01:00] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2022-03-16T14:16:50.409050279+01:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
INFO[2022-03-16T14:16:50.409062094+01:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=moby
panic: page 2 already freed

goroutine 1 [running]:
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*freelist).free(0x400065fa80, 0x1d98a17, 0xffff806b3000)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/freelist.go:175 +0x39c
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*node).spill(0x400023d3b0, 0x4000e448a0, 0x1)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/node.go:359 +0x348
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*node).spill(0x400023d2d0, 0x40007a8990, 0x40010342e8)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/node.go:346 +0x9c
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Bucket).spill(0x40005951c0, 0x40007a8900, 0x40010344d8)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/bucket.go:570 +0x340
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Bucket).spill(0x4001178b78, 0x53e87924, 0xaaaad3dfce40)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/bucket.go:537 +0x2b8
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Tx).Commit(0x4001178b60, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/tx.go:160 +0xa8
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*DB).Update(0x4000f65c00, 0x4001034710, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/db.go:701 +0xe4
github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb.(*BoltDB).Put(0x4000c01b80, 0x400047d170, 0x23, 0xaaaad3e2c078, 0x0, 0x0, 0x40004aa5f0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb/boltdb.go:187 +0x194
github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*datastore).ensureParent(0x4000afcb80, 0x400047d170, 0x23, 0xffff8110bcf8, 0x40007a85d0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/datastore.go:507 +0xc4
github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*datastore).iterateKVPairsFromStore(0x4000afcb80, 0x400047d170, 0x23, 0xaaaad2ea4638, 0x40007a85d0, 0x40010348e8, 0x4000e36000, 0xaaaad3d58400)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/datastore.go:539 +0x70
github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*datastore).Map(0x4000afcb80, 0x400047d170, 0x23, 0xaaaad2ea4638, 0x40007a85d0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/datastore.go:578 +0xe0
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).getNetworksFromStore(0x40010dc500, 0xaaaad1a81c1c, 0x4000afcbc0, 0xaaaad24f55ca)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:140 +0x480
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).Networks(0x40010dc500, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:1023 +0x28
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).WalkNetworks(0x40010dc500, 0xaaaad2df6818)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:1034 +0x28
github.com/docker/docker/vendor/github.com/docker/libnetwork.New(0x4000164e00, 0x9, 0x10, 0x4000afe270, 0x4000f1eed0, 0x4000164e00, 0x9)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:240 +0x564
github.com/docker/docker/daemon.(*Daemon).initNetworkController(0x40008ec1e0, 0x4000120000, 0x4000f1eed0, 0x4000100280, 0x40008ec1e0, 0x40006d4c40, 0x4000f1eed0)
	/go/src/github.com/docker/docker/daemon/daemon_unix.go:855 +0x78
github.com/docker/docker/daemon.(*Daemon).restore(0x40008ec1e0, 0x4000afcac0, 0x40000502a0)
	/go/src/github.com/docker/docker/daemon/daemon.go:490 +0x3d8
github.com/docker/docker/daemon.NewDaemon(0xaaaad2e879d0, 0x4000afcac0, 0x4000120000, 0x4000afe270, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:1150 +0x20d8
main.(*DaemonCli).start(0x40004a9320, 0x4000102a20, 0x0, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:195 +0x588
main.runDaemon(...)
	/go/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:13
main.newDaemonCommand.func1(0x4000461080, 0xaaaad3e2c078, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:34 +0x78
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0x4000461080, 0x400004e210, 0x0, 0x0, 0x4000461080, 0x400004e210)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:850 +0x320
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4000461080, 0x0, 0x0, 0x7)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:958 +0x258
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:895
main.main()
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:97 +0x188
```

`sudo journalctl -xe`

```
Mar 16 14:23:23 mrk-srv.local systemd[1]: containerd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit containerd.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 2.
Mar 16 14:23:23 mrk-srv.local systemd[1]: containerd.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit containerd.service has entered the 'failed' state with result 'exit-code'.
Mar 16 14:23:23 mrk-srv.local systemd[1]: Failed to start containerd container runtime.
-- Subject: A start job for unit containerd.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit containerd.service has finished with a failure.
-- 
-- The job identifier is 91905 and the job result is failed.
Mar 16 14:23:23 mrk-srv.local systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: A start job for unit docker.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit docker.service has finished with a failure.
-- 
-- The job identifier is 91819 and the job result is dependency.
Mar 16 14:23:23 mrk-srv.local systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Mar 16 14:23:26 mrk-srv.local sudo[9941]:      mrk : TTY=pts/0 ; PWD=/ ; USER=root ; COMMAND=/usr/bin/journalctl -xe
Mar 16 14:23:26 mrk-srv.local sudo[9941]: pam_unix(sudo:session): session opened for user root by mrk(uid=0)
```

Please help me solve this.
Thank you!

**Comment by maietta** [comment]
From the errors I am seeing, your problem has nothing to do with Caprover.

You need to be verifying that Docker Engine is properly running and that you can manually run a docker container.

**Comment by githubsaturn** [comment]
+1 to what @maietta said.

To confirm, simply run this container and see if it works:
```
docker container run -d \
  -p 9000:9000 \
  -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer
```

**Comment by marcusique** [comment]
> +1 to what @maietta said.
> 
> To confirm, simply run this container and see if it works:
> 
> ```
> docker container run -d \
>   -p 9000:9000 \
>   -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer
> ```

This wouldn't work with the exact same `"Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"` error. I realized that something was completely off with Docker Engine and I tried to reinstall it. At first, I couldn't even uninstall docker-ce as apt would say that it's partially (???) installed and would try to reconfigure it, causing the exact same issue in the end.
What I did was to reinstall docker following the [official guide](https://docs.docker.com/engine/install/ubuntu/#uninstall-docker-engine), removing all dependencies and local configs. Only then I could install it again and start Caprover.
Unfortunately, I'd lost all my containers.

More importantly, do you @githubsaturn @maietta think that creating an OS image using `dd` and then restoring it would cause any issues with docker? I don't see how it would be a problem but after that issue I started questioning my strategy for backups. 
Thank you.

**Comment by maietta** [comment]
Hi, @marcusique.

Even though you are booting from a restored backup, there is some key information that is missing from my understanding of your scenario.

You said "Due to failure with internal storage on my Raspberry Pi (Ubuntu / aarch64) I re-imaged OS from backup onto a new internal storage. "

So my question is this:

What is your backup strategy, in a nutshell.

Are you physically taking the SD card out and creating a raw image? Or perhaps are you running a command to export the contents of your file system?

Answer that and also do the following:

Take a peek at output from the following commands:

```
 /usr/bin/dockerd -H unix:///var/run/docker.sock
```

and also:

```
journalctl -f
```

Either one of those commands should tell you more about what's causing the failure. I am suspecting your backups are exports of your file system but the underlying disk partitioning and file system type is different but that's just a guess without more info.

**Comment by marcusique** [comment]
Hi @maietta,

I have a cronjob with a script that runs `dd if=/dev/mmcblk0 of=${STORAGEPATH}/${IMAGENAME}-$(date +%Y-%m-%d).img bs=8MB` on a certain basis to create an image of RPi's SD card, then it runs [PiShrink](https://github.com/Drewsif/PiShrink) to reduce its size. Whenever needed I just flash that image onto a new SD card (using the official RPi imager). I've done it only twice in the last couple of years and everything worked just fine, but it was my first time restoring a system with docker running on it. I don't see how docker would break after flashing the exact same image onto a new SD card, but perhaps there's something I don't know. Would be great to clear that part out since rebuilding images from scratch is a pain.
