### ISSUE TITLE
"PayloadTooLargeError: request entity too large" when using github webhooks

### ISSUE THREAD

**Issue by TobiasWehrum** [caprover/caprover#1393]
### What is the problem?
We're using a special `deploy` branch in our repository, to which we push using fast-forward merging. Often there will be a lot of commits between each push to `deploy`. Once we push to the `deploy` branch then, the Github webhook sends information about all commits since the last push to `deploy`, causing a `PayloadTooLargeError: request entity too large` error in the `captain-captain` docker container, and no automatic deploy happens.

If that happened, I have two ways of deploying, both working just fine (if being a little annoying, especially since I first have to realize that the deploy failed):
- Logging into Caprover and clicking on `Force deploy`.
- Pushing a single commit to `deploy`, leading to a small-enough Github webhook payload.

An example when this happened was when the Github webhook payload was 176 KB big.

The error is:
```
today at 03:26:16POST /api/v2/user/apps/webhooks/triggerbuild?namespace=captain&token=[token censored] 500 3.048 ms - 21
today at 03:26:16April 21st 2022, 1:26:16.684 am    PayloadTooLargeError: request entity too large
today at 03:26:16PayloadTooLargeError: request entity too large
today at 03:26:16    at readStream (/usr/src/app/node_modules/raw-body/index.js:155:17)
today at 03:26:16    at getRawBody (/usr/src/app/node_modules/raw-body/index.js:108:12)
today at 03:26:16    at read (/usr/src/app/node_modules/body-parser/lib/read.js:77:3)
today at 03:26:16    at urlencodedParser (/usr/src/app/node_modules/body-parser/lib/types/urlencoded.js:116:5)
today at 03:26:16    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
today at 03:26:16    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
today at 03:26:16    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
today at 03:26:16    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
today at 03:26:16    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
today at 03:26:16    at jsonParser (/usr/src/app/node_modules/body-parser/lib/types/json.js:119:7)
```

### Steps to reproduce the problem:

1. Connect a repository to Caprover via webhooks.
2. Have a branch pointing to some old commit.
3. Update that branch to a much newer commit, with many commits with many changed files inbetween, thereby generating a Github webhook payload of 176 KB or more.

### Output of the following command on your server: `uname -a && lsb_release -a && free -h`

```
Linux call-of-prev-development 4.15.0-173-generic #182-Ubuntu SMP Fri Mar 18 15:53:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
              total        used        free      shared  buff/cache   available
Mem:            15G        7.5G        2.3G         23M        5.9G        8.1G
Swap:            0B          0B          0B
```

**Comment by mxdpeep** [comment]
*25 MB* is a limit of the webhook payload size on GitHub, so this must be a
caprover limitation

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*

**Comment by c43721** [comment]
25MB being the highest limit is quite a lot, but could be just restricted to this one endpoint. I will see if this is something I can PR.

**Comment by dust120125** [comment]
Having the same problem here.
Based on the error message and stack trace, it seems to be caused by `body-parser`.
According to the documentation of `body-parser`(https://github.com/expressjs/body-parser#bodyparserjsonoptions), the default size limit is 100kb, while my GitHub webhook payload size is approximately 113kb.

**Comment by githubsaturn** [comment]
I'm curious why the payload size is so large. Typically all my github actions are very small. Can you upload an example payload? 


Alternatively, you can just use github actions. Something like this should work:
```yaml
name: deploy on CapRover

on:
    push:
        branches:
            - master

jobs:
    deploy-on-caprover:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: |
                  curl -X POST https://captain.yourdomain.com/.....<webhook>
```

**Comment by githubsaturn** [comment]
Even better, you should start looking into this: https://github.com/caprover/deploy-from-github

**Comment by dust120125** [comment]
@githubsaturn
Thank you for your response. There's nothing special about my payload. The reason it is so large is because it merged a branch with over 100 commits.
I appreciate the solutions you provided; they are very helpful to me.

**Comment by TobiasWehrum** [comment]
> There's nothing special about my payload. The reason it is so large is because it merged a branch with over 100 commits.

Same for me - just a big pull request with lots of commits to merge. They are all mentioned in the "commits" section of the payload, so naturally at some point the resulting text will be over 100kb.

**Comment by maietta** [comment]
@TobiasWehrum I would be manually looking at the artifact holding your deploy files to see what is being included.

For example, my Node projects often get built at well over 150MB in size due to all the dependencies used. After performing the "npm ci --omit dev" command, that package size comes way down to just 1MB because that's only what's needed in production. Even at that, the entire project size including webserver, static images, CSS etc, et cetera peg my deploys around 3-4MB in size.

Some time might have to be spent in optimizing your build and deploys, depending on what kind of project you are working on.

**Comment by TobiasWehrum** [comment]
I don't actually need any other way of doing it right now. Most of the time this works fine, the few times where it fails I just trigger deploy manually, as described in my initial post. It's just a minor annoyance.

I imagine there are other people using Method 3 with webhooks though, and they might be surprised that it sometimes fails, so I opened a bug here.

**Comment by maietta** [comment]
There are multiple deploy options for the reason that there are many ways to deploy an application. Not every method will work for everyone and you'll have to adjust your workflow according to your needs.

If you are insistent on using Webhooks, perhaps another solution might work for you that involves building a docker image and pushing to a docker container registry of your choosing, then adding that registry to your CapRover instance. Because this involves building a docker image prior to having CapRover fetch it, it may still not be ideal for you in your particular scenario.  This process does not need to involve Github at all but it does let you continue to use webhooks.

**Comment by SteffenL** [comment]
I use "Method 3: Deploy from Github" and encountered this issue a number of few times. It was not obvious to me why it suddenly failed to deploy.

One can have many commits, many changed files, files with long paths, or a combination.

One of my recent pushes to GitHub produced a ~700 KiB / ~4500 LOC webhook payload. It was quite easy to achieve.

While working on migrating blogs into static files, I added hundreds of files, moved and retouched them a number of times. A few hundred imported assets originally had long paths as well.

In CapRover 1.14.1, the "Force build" button resolves the issue once.

Increasing the payload limit sounds reasonable to me.
