### ISSUE TITLE
Upgrade Issue - Error: There must be only one instance (not 0) of the service running to find node id. captain-certbot

### ISSUE THREAD

**Issue by joshstrange** [caprover/caprover#1395]
I just upgraded my caprover instance from the web UI and after initially being in a container restart loop due an older docker version I upgraded and now I have a new problem that I can't find any info about online.

I am running CapRover `caprover/caprover:1.10.1` and here are my server stats:

```
Linux caprover-ubuntu-01 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
              total        used        free      shared  buff/cache   available
Mem:           3.9G        844M        698M         21M        2.3G        2.7G
Swap:            0B          0B          0B
```

I saw another comment that mentioned disk space being an issue but that does not seem to be the case here:

```
root@caprover-ubuntu-01:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G     0  1.9G   0% /dev
tmpfs           395M  1.4M  394M   1% /run
/dev/vda1        49G   26G   23G  53% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda15      105M  6.7M   98M   7% /boot/efi
tmpfs           395M     0  395M   0% /run/user/0
overlay          49G   26G   23G  53% /var/lib/docker/overlay2/f281efa43214891ce34350b783216f4f046818dcf1cd2bc632ff066c9a782d6f/merged
overlay          49G   26G   23G  53% /var/lib/docker/overlay2/2262ddb023499072c852eaa466264cc946eabfe600530feff27dea3ce1a6d482/merged
overlay          49G   26G   23G  53% /var/lib/docker/overlay2/ec63fc54e93eb6b5ae9601d71a761d73b445700a53f6fda8e1af282dd7908808/merged
overlay          49G   26G   23G  53% /var/lib/docker/overlay2/f303cad106f25d57777549953b601dbc2cacaa27656394813f4cc689f1ef873a/merged
overlay          49G   26G   23G  53% /var/lib/docker/overlay2/303e37909d24883b46dda8b6ba43d3594c59e9fd6240e7066a4ae3d134d8e71e/merged
overlay          49G   26G   23G  53% /var/lib/docker/overlay2/9cac2e89a4961ac6d9e2277859a66c70d212c63e9bb861294dd84d0c80f8bf7a/merged
overlay          49G   26G   23G  53% /var/lib/docker/overlay2/7dbfda4f153e845f9610458fd50cb4f1a64dd697ea24fe7bd9bb5d72ef728b0e/merged
overlay          49G   26G   23G  53% /var/lib/docker/overlay2/69cede9f0c6ca8ada1e2babc69b03f58a8f6e492563f80dcf418c9937660c48e/merged
overlay          49G   26G   23G  53% /var/lib/docker/overlay2/f103db08e7400093bf96905d5f5663fc146e5c8b633b7b61c8e29c969bf6079a/merged
overlay          49G   26G   23G  53% /var/lib/docker/overlay2/58bdf74105ae8756d94401f6cecc9ade0ed597c8d29162208eee0c6d50262634/merged
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/docker/containers/b5b0aafa61067c8e1b99c9dd8b27c3d6c17dbf8986d1b953d308896991134c7a/mounts/secrets
overlay          49G   26G   23G  53% /var/lib/docker/overlay2/b2eceb692fecea02237b1f63453cf39b4e9dbb7b68b61a61fea8989db958998e/merged
```

Here is what I see over and over when I run `docker service logs captain-captain --tail 100 -f`
```
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | Captain Starting ...
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.511 pm    Emptying generated and temp folders.
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.519 pm    Ensuring directories are available on host. Started.
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.526 pm    Ensuring directories are available on host. Finished.
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.530 pm    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.536 pm    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.537 pm    Migration not needed, skipping.
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.542 pm    Copying fake certificates...
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.546 pm    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.547 pm    Locking NGINX configuration reloading...
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.560 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.564 pm    Captain Nginx is already running..
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.567 pm    Updating NGINX service...
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:17.577 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:22.582 pm    Pruning containers...
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:22.583 pm    NGINX is fully set up and working...
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:22.589 pm    Captain Certbot is already running..
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:25.594 pm    Retrying to get NodeID for captain-certbot retry count:0
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:28.602 pm    Retrying to get NodeID for captain-certbot retry count:1
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:31.609 pm    Retrying to get NodeID for captain-certbot retry count:2
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:34.616 pm    Retrying to get NodeID for captain-certbot retry count:3
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:37.623 pm    Retrying to get NodeID for captain-certbot retry count:4
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:40.630 pm    Retrying to get NodeID for captain-certbot retry count:5
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:43.636 pm    Retrying to get NodeID for captain-certbot retry count:6
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:46.643 pm    Retrying to get NodeID for captain-certbot retry count:7
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:49.649 pm    Retrying to get NodeID for captain-certbot retry count:8
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:52.655 pm    Retrying to get NodeID for captain-certbot retry count:9
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | April 22nd 2022, 4:47:52.659 pm    Error: There must be only one instance (not 0) of the service running to find node id. captain-certbot
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    | Error: There must be only one instance (not 0) of the service running to find node id. captain-certbot
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    |     at /usr/src/app/built/docker/DockerApi.js:97:23
captain-captain.1.x7xvyv7t52k9@caprover-ubuntu-01    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | Captain Starting ...
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.789 pm    Emptying generated and temp folders.
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.797 pm    Ensuring directories are available on host. Started.
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.805 pm    Ensuring directories are available on host. Finished.
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.815 pm    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.823 pm    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.825 pm    Migration not needed, skipping.
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.831 pm    Copying fake certificates...
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.835 pm    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.836 pm    Locking NGINX configuration reloading...
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.853 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.857 pm    Captain Nginx is already running..
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.860 pm    Updating NGINX service...
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:06.869 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:11.874 pm    Pruning containers...
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:11.875 pm    NGINX is fully set up and working...
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:11.879 pm    Captain Certbot is already running..
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:14.883 pm    Retrying to get NodeID for captain-certbot retry count:0
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:17.889 pm    Retrying to get NodeID for captain-certbot retry count:1
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:20.894 pm    Retrying to get NodeID for captain-certbot retry count:2
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:23.899 pm    Retrying to get NodeID for captain-certbot retry count:3
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:26.906 pm    Retrying to get NodeID for captain-certbot retry count:4
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:29.914 pm    Retrying to get NodeID for captain-certbot retry count:5
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:32.920 pm    Retrying to get NodeID for captain-certbot retry count:6
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:35.926 pm    Retrying to get NodeID for captain-certbot retry count:7
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:38.932 pm    Retrying to get NodeID for captain-certbot retry count:8
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:41.938 pm    Retrying to get NodeID for captain-certbot retry count:9
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | April 22nd 2022, 4:48:41.941 pm    Error: There must be only one instance (not 0) of the service running to find node id. captain-certbot
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    | Error: There must be only one instance (not 0) of the service running to find node id. captain-certbot
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    |     at /usr/src/app/built/docker/DockerApi.js:97:23
captain-captain.1.s1pnppkkevz3@caprover-ubuntu-01    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
captain-captain.1.mdu1jw3oulin@caprover-ubuntu-01    | Captain Starting ...
```

There seems to be an issue with `captain-certbot` but I'm unsure of how to fix this. Thankfully my apps are still up but I can't get to the CapRover web UI.

Any help is greatly appreciated. Thank you!

**Comment by joshstrange** [comment]
After digging some more I think my issue might be that certbot isn't running? I was just reading [this page in the docs](https://caprover.com/docs/certbot-config.html#first-step) and I tried to run the `docker service update captain-certbot` command and it complains:

```
root@caprover-ubuntu-01:~# docker service update captain-certbot
captain-certbot
overall progress: 0 out of 1 tasks
1/1: No such image: caprover/certbot-sleeping:v1.6.0
```

I'm going to pull that image and try again.

**Comment by joshstrange** [comment]
Well that didn't work:

```
root@caprover-ubuntu-01:~# docker pull caprover/certbot-sleeping:v1.6.0
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

I'm not sure if this the actual issue or if CapRover just thrashed docker until it used up the limits and now I'm stuck. I'll see about just paying for 1 month to get around this limit.

**Comment by joshstrange** [comment]
Well paying for docker hub and pulling that certbot container seems to have fixed it.
