### ISSUE TITLE
CapRover wont bind to port

### ISSUE THREAD

**Issue by kaaax0815** [caprover/caprover#1456]
What is the problem?

CapRover and Nginx fail constantly and thus wont bind to a port and thus all my services are unreachable

Steps to reproduce the problem:

I dont know. I just deployed 2 apps and played around to make the dockerfile work and know the whole service is down. It started that I could issue a ssl cert.

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```

```
Linux kaaaxcreators.de 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
              total        used        free      shared  buff/cache   available
Mem:          3.8Gi       2.2Gi       832Mi        44Mi       858Mi       1.3Gi
Swap:         4.0Gi        46Mi       4.0Gi
```

Logs:
```
# docker service ps captain-nginx --no-trunc
ID                          NAME                  IMAGE     NODE               DESIRED STATE   CURRENT STATE           ERROR                       PORTS
xuz4655zcwr5fckrdt3l69pur   captain-nginx.1       nginx:1   kaaaxcreators.de   Ready           Ready 2 seconds ago
hzd0fvypblmp961udmuxhsefs    \_ captain-nginx.1   nginx:1   kaaaxcreators.de   Shutdown        Failed 4 seconds ago    "task: non-zero exit (1)"
9uda5pvopawwvs81m21q2h0ch    \_ captain-nginx.1   nginx:1   kaaaxcreators.de   Shutdown        Failed 10 seconds ago   "task: non-zero exit (1)"
kjh8rds34u31kmjoqm07biqot    \_ captain-nginx.1   nginx:1   kaaaxcreators.de   Shutdown        Failed 16 seconds ago   "task: non-zero exit (1)"
4sn6fwlornu7rhcdx5gmlknhc    \_ captain-nginx.1   nginx:1   kaaaxcreators.de   Shutdown        Failed 22 seconds ago   "task: non-zero exit (1)"
```

```
# docker service logs captain-captain --since 5m
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | Captain Starting ...
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:13.031 am    Emptying generated and temp folders.
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:13.071 am    Ensuring directories are available on host. Started.
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:13.100 am    Ensuring directories are available on host. Finished.
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:13.106 am    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:13.124 am    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:13.134 am    Migration not needed, skipping.
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:13.141 am    Copying fake certificates...
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:13.157 am    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:13.157 am    Locking NGINX configuration reloading...
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:13.195 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:13.198 am    Captain Nginx is already running..
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:16.203 am    Retrying to get NodeID for captain-nginx retry count:0
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:16.205 am    Updating NGINX service...
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:16.215 am    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:21.215 am    Pruning containers...
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:21.216 am    NGINX is fully set up and working...
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:21.219 am    Captain Certbot is already running..
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:21.222 am    Updating Certbot service...
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:21.240 am    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:22.108 am    **** Captain is initialized and ready to serve you! ****
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:23.132 am    Error: Wrapped: Verification Failed for captain.server.kaaaxcreators.de
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | Error: Wrapped: Verification Failed for captain.server.kaaaxcreators.de
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:54:42)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at ClientRequest.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Socket.socketErrorListener (_http_client.js:475:9)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Socket.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at emitErrorNT (internal/streams/destroy.js:106:8)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:23.132 am    Error: Wrapped: Error        Error: connect ECONNREFUSED 62.68.75.16:80
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | Error: Wrapped: Error        Error: connect ECONNREFUSED 62.68.75.16:80
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:55:42)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at ClientRequest.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Socket.socketErrorListener (_http_client.js:475:9)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Socket.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at emitErrorNT (internal/streams/destroy.js:106:8)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:23.132 am    Error: Wrapped: body         undefined
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | Error: Wrapped: body         undefined
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:56:42)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at ClientRequest.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Socket.socketErrorListener (_http_client.js:475:9)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Socket.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at emitErrorNT (internal/streams/destroy.js:106:8)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:23.132 am    Error: Wrapped: randomUuid   36b8fafe-3bee-41b8-9b2b-311c070d813b
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | Error: Wrapped: randomUuid   36b8fafe-3bee-41b8-9b2b-311c070d813b
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:57:42)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at ClientRequest.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Socket.socketErrorListener (_http_client.js:475:9)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at Socket.emit (events.js:400:28)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    |     at emitErrorNT (internal/streams/destroy.js:106:8)
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:23.133 am    Captain health check failed: #0 at captain.server.kaaaxcreators.de
captain-captain.1.7y41swov3yhs@kaaaxcreators.de    | July 2nd 2022, 11:08:23.133 am    NGINX health check failed: #0
```

```
# docker service logs captain-nginx --since 5m
captain-nginx.1.k98k558i9oqc@kaaaxcreators.de    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
captain-nginx.1.k98k558i9oqc@kaaaxcreators.de    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
captain-nginx.1.k98k558i9oqc@kaaaxcreators.de    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
captain-nginx.1.k98k558i9oqc@kaaaxcreators.de    | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
captain-nginx.1.k98k558i9oqc@kaaaxcreators.de    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
captain-nginx.1.k98k558i9oqc@kaaaxcreators.de    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
captain-nginx.1.k98k558i9oqc@kaaaxcreators.de    | /docker-entrypoint.sh: Configuration complete; ready for start up
captain-nginx.1.k98k558i9oqc@kaaaxcreators.de    | 2022/07/02 11:08:51 [emerg] 1#1: directive "set" is not terminated by ";" in /etc/nginx/conf.d/captain.conf:296
captain-nginx.1.k98k558i9oqc@kaaaxcreators.de    | nginx: [emerg] directive "set" is not terminated by ";" in /etc/nginx/conf.d/captain.conf:296
```

**Comment by githubsaturn** [comment]
Did you make a change to nginx custom configuration? Try this: https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui

**Comment by kaaax0815** [comment]
Thank you very much! This fixed it
