### ISSUE TITLE
Remote Network Connection between App and Database located on two Caprover VPS projects.

### ISSUE THREAD

**Issue by ernesto-alberto** [caprover/caprover#1477]
Hello,
I have two VPS and on both I installed Caprover. One for my hosted Apps and other for my hosted databases. I would like to use remote connection for the comunication between my Apps and the Database located on the second caprover vps.

I have used the following configuration found [here](https://caprover.com/docs/one-click-apps#connecting-remotely) as example but I am geting the folowing error:
```
2022-07-28T16:16:37.231644253Z MongooseError: Operation `categories.estimatedDocumentCount()` buffering timed out after 10000ms
2022-07-28T16:16:37.231701768Z at Timeout.<anonymous> (/usr/src/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:151:23)
2022-07-28T16:16:37.231722890Z at listOnTimeout (node:internal/timers:559:17)
2022-07-28T16:16:37.231741532Z at processTimers (node:internal/timers:502:7)
2022-07-28T16:16:47.290460897Z Error: connect ETIMEDOUT
2022-07-28T16:16:47.318111473Z at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:168:41)
2022-07-28T16:16:47.318159848Z at Object.onceWrapper (node:events:641:28)
2022-07-28T16:16:47.318180264Z at Socket.emit (node:events:527:28)
2022-07-28T16:16:47.318199292Z at Socket._onTimeout (node:net:516:8)
2022-07-28T16:16:47.318218939Z at listOnTimeout (node:internal/timers:559:17)
2022-07-28T16:16:47.318237547Z at processTimers (node:internal/timers:502:7) {
2022-07-28T16:16:47.318256341Z errorno: 'ETIMEDOUT',
2022-07-28T16:16:47.318274851Z code: 'ETIMEDOUT',
2022-07-28T16:16:47.318293222Z syscall: 'connect'
2022-07-28T16:16:47.318311773Z }
2022-07-28T16:16:56.334136228Z node:internal/errors:465
2022-07-28T16:16:56.334214366Z ErrorCaptureStackTrace(err);
2022-07-28T16:16:56.334245371Z ^
2022-07-28T16:16:56.334270738Z
2022-07-28T16:16:56.334296539Z TypeError [ERR_INVALID_URL]: Invalid URL
2022-07-28T16:16:56.334319007Z at new NodeError (node:internal/errors:372:5)
2022-07-28T16:16:56.334337902Z at URL.onParseError (node:internal/url:553:9)
2022-07-28T16:16:56.334356103Z at new URL (node:internal/url:629:5)
2022-07-28T16:16:56.334374642Z at isAtlas (/usr/src/app/node_modules/mongoose/lib/helpers/topology/isAtlas.js:17:17)
2022-07-28T16:16:56.334393402Z at MongooseServerSelectionError.assimilateError (/usr/src/app/node_modules/mongoose/lib/error/serverSelection.js:35:35)
2022-07-28T16:16:56.334412383Z at /usr/src/app/node_modules/mongoose/lib/connection.js:825:36
2022-07-28T16:16:56.334430967Z at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2022-07-28T16:16:56.334449442Z input: 'my-ip:27017',
2022-07-28T16:16:56.334474323Z code: 'ERR_INVALID_URL'
2022-07-28T16:16:56.334492981Z }
```
I have mapped the ports of my databases as well as openned those ports on my vps Database firewall  and on my App vps Servers.

On my Caprover VPS dedicated for Database I have the following set:
```
Linux dbapp 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
               total        used        free      shared  buff/cache   available
Mem:           1.9Gi       447Mi       177Mi       1.0Mi       1.3Gi       1.3Gi
Swap:          7.0Gi       4.0Mi       7.0Gi
```

And on my Caprover VPS dedicated for App I have the following set:
```
Linux app 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
               total        used        free      shared  buff/cache   available
Mem:           5.8Gi       704Mi       3.2Gi       3.0Mi       1.9Gi       4.9Gi
Swap:          9.0Gi          0B       9.0Gi
```

I have tested and configure everything using one Caprover vps and it works fine. But as for the requiment of the project I need it to be configured on separated VPS.

I apologize if I have missed anything, but I would appreciate some additional steps that I may have missed to configure and get it to work perfectly.

Thank you.

**Comment by githubsaturn** [comment]
1- When you say 2 caprover instances, do you have two separate CapRover dashboards? Or you mean one dashboard but two nodes?

2- What's the connection string that you're using when you want to connect to your database?

3- Are you sure that all ports are open in your firewall?

4- Have you tested the ports being open by running `nc` for example? You can do so by running:
```
nc -zvw10 101.102.103.104 8080
        # remote IP       Port
```

**Comment by ernesto-alberto** [comment]
Hello Kasra,
Thank you for your feedback.


> 1- When you say 2 caprover instances, do you have two separate CapRover dashboards? Or you mean one dashboard but two nodes?

Yes, I have two Dashboards. One only for my Apps and the second one only for the Databases.


> 2- What's the connection string that you're using when you want to connect to your database?

I have the folling Environmental Variables on caprover App Configs which I created for connection string between my App and the Database:

```
DB_CLOUD=true
APP_WEB_URL=https://mywebsite.com
REDISCLOUD_URL=redis://:redis-password@123.123.123.123:9998/0
STORAGE_DRIVER=disk
CLOUD_NAME=my-git-cloud-name
API_KEY=my-api-key-number
API_SECRET=my-api-secret-number
SECURE_SESSION=production
SECRET_SESSION=my-secret-session-number
MONGODB_URI_CLOUD=mongodb://dbuser:dbpassword@123.123.123.123:9999/dbname?authSource=admin
ENVIRONMENT=production
```
Where my Database Server IP is 123.123.123.123 and my mapped port are 9999 for mongodb and 9998 for redis.


> 3- Are you sure that all ports are open in your firewall?

Yes, the ports are open on both VPS (App and DB).


> 4- Have you tested the ports being open by running nc for example? You can do so by running:

Running this command from my Caprover App VPS, I am able to get sucessfull connection to my Caprover Database VPS. But the reverse is not possible.

**Comment by githubsaturn** [comment]
Your setup looks okay. Perhaps you have a typo or something. 

Try connecting to mongo database from your local machine using a MongoDB GUI tool. Does it work if you use the exact connection string that you use in your app `mongodb://dbuser:dbpassword@123.123.123.123:9999/dbname?authSource=admin` ?

**Comment by ernesto-alberto** [comment]
Hello Kasra,
Thank you for your feedback. 

```
Your setup looks okay. Perhaps you have a typo or something.

Try connecting to mongo database from your local machine using a MongoDB GUI tool. Does it work if you use the exact connection string that you use in your app mongodb://dbuser:dbpassword@123.123.123.123:9999/dbname?authSource=admin ?
```

Yes, you are write. We just checked out all the configurations and we find out some Typos on Caprover Environmental Variables Configuration.

We have tested again and we can have access to our Caprover DB. We will keep monintoring it and ckeck if everything is working according to our plan.

Thank you for your support and attention.

Regards.
