### ISSUE TITLE
Peertube + iredmail + let's Encrypt

### ISSUE THREAD

**Issue by davidleebooth** [caprover/caprover#1560]
---

What is the problem?

Peertube cannot connect to iredmail SMTP, Throws error about a self signed cert on startTLS, iredmail requires startTLS, resolution looking at peertube is to add lines to the production.yaml to include the path to the CA file. How shall I do that so that I can connect mail? My first attempt was a failure, making peertube settings a persistent app and then adding the file path to to where capshare stores the cert file, unfortunately

Another alternative would be how to enable SSL 465 on iredmail since that comes out of the box disabled.

Steps to reproduce the problem:
install iredmail create an account
SSL with LE
install peertube enter account credentials as instructed by iredmail

Startup Error:

2022-11-14T01:07:27.534513528Z [davbot.media:443] 2022-11-14 01:07:27.533 error: Failed to connect to SMTP mail.davbot.media:587. {
2022-11-14T01:07:27.534544497Z "err": {
2022-11-14T01:07:27.534551347Z "stack": "Error: self signed certificate\n at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)\n at TLSSocket.emit (events.js:314:20)\n at TLSSocket.EventEmitter.emit (domain.js:483:12)\n at TLSSocket._finishInit (_tls_wrap.js:937:8)\n at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12)",
2022-11-14T01:07:27.534560225Z "message": "self signed certificate",

```
I am on ubuntu 18.04, caprover 1.10.1, Stable iredmail and latest buster for peertube.
```

**Comment by githubsaturn** [comment]
This forum is for CapRover bugs. For app specific bugs and questions please follow the guide here:

https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md#app-bugs
