### ISSUE TITLE
Health check failed, when reinstalling CapRover with same domain

### ISSUE THREAD

**Issue by JonathanDoelan** [caprover/caprover#1568]
I set up CapRover with docker and a domain like `*.foo.example.com`. (And I really enjoy it — so THANK YOU)

I have to switch to another server now and reinstall CapRover with the same domain (`*.foo.example.com`).
If I do so it does not work. In the front-end of CapRover I’ll get errors like `Something bad happened` or `CapRover isn’t ready yet` and in the container logs:

```
November 28th 2022, 8:48:24.854 am    Error: Wrapped: Verification Failed for captain.foo.example.com
Error: Wrapped: Verification Failed for captain.foo.example.com
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:54:42)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
November 28th 2022, 8:48:24.855 am    Error: Wrapped: Error        Error: connect ECONNREFUSED 116.203.243.220:80
Error: Wrapped: Error        Error: connect ECONNREFUSED 116.203.243.220:80
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:55:42)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
November 28th 2022, 8:48:24.855 am    Error: Wrapped: body         undefined
Error: Wrapped: body         undefined
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:56:42)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
November 28th 2022, 8:48:24.855 am    Error: Wrapped: randomUuid   85d2ca74-8b59-42f0-9e3c-6cbe5bd59579
Error: Wrapped: randomUuid   85d2ca74-8b59-42f0-9e3c-6cbe5bd59579
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:57:42)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
```
```
November 28th 2022, 8:48:24.855 am    Captain health check failed: #1 at captain.foo.example.com
November 28th 2022, 8:48:24.855 am    NGINX health check failed: #1
```

I’ve also tested it when the original server was down: same result.

So I’ve tried with a different domain like `*.bar.example.com` and the errors do not appear. So it works with a different domain.

The problem is that I want to use `*.foo.example.com` again for various reasons.

How can I achieve that?

**Comment by githubsaturn** [comment]
The problem is the DNS settings of `*.foo.example.com`. It must route to the new server IP.

Also, note that DNS takes some time to propagate, sometimes up to 24hr. 

You can use this tool to check if your DNS settings have been applied correctly everywhere: https://www.whatsmydns.net/

**Comment by JonathanDoelan** [comment]
@githubsaturn Thanks. You are right. So if the same happens again, I have to use the `Change Root Domain Anyways` button to change the domain temporarily, right? Or will I mess things up with it?

**Comment by githubsaturn** [comment]
Changing root domain invalidates all ssl certs.
