### ISSUE TITLE
Cannot access one click apps

### ISSUE THREAD

**Issue by lofiiboyy** [caprover/caprover#1722]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

Cant access one click apps
If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
Go to one click apps page

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h

Linux instance-1 5.15.0-1030-gcp #37-Ubuntu SMP Tue Feb 14 19:37:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
               total        used        free      shared  buff/cache   available
Mem:            15Gi       449Mi        10Gi       1.0Mi       4.3Gi        14Gi
Swap:             0B          0B          0B

```

Error:
```

captain-captain.1.vc2cd23tbq02@instance-1    | April 12th 2023, 5:01:06.704 pm    Error: Could not fetch app lists from oneclickapps.caprover.com
captain-captain.1.vc2cd23tbq02@instance-1    | Error: Could not fetch app lists from oneclickapps.caprover.com
captain-captain.1.vc2cd23tbq02@instance-1    |     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
captain-captain.1.vc2cd23tbq02@instance-1    |     at /usr/src/app/built/routes/user/oneclick/OneClickAppRouter.js:36:44
captain-captain.1.vc2cd23tbq02@instance-1    |     at runMicrotasks (<anonymous>)
captain-captain.1.vc2cd23tbq02@instance-1    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

**Comment by githubsaturn** [comment]
* Either the network was temporary down
* Or, your network is blocking the one click app repository 

If you curl the URL from the image, does it work?

```bash
curl https://oneclickapps.caprover.com/v4/list
```

**Comment by lofiiboyy** [comment]
no

**Comment by githubsaturn** [comment]
What commands did you run?

**Comment by lofiiboyy** [comment]
I ran it outside of my container, it works fine, but within my container:
`sudo docker exec -it 10a3bc5152eb curl https://oneclickapps.caprover.com/v4/list`

It times out and never gives an output.

**Comment by githubsaturn** [comment]
> perhaps its time for a container update?

What container are you referring to?

**Comment by stuffa** [comment]
First let me say,  great to get a responce same day (ie: within 24hrs)

Sorry I used the wrong term, an "image" update.
The caprover/captain image, currently the stable releaase is based on the node:14 image, which in turn is using Debian Sketch. 

Either update the node version in the docker file (assuming a higher version fo node works ok) or switch to another node version that supports a currently supported Debian version

This should fix the curl problem.  as I mentioned, it only seems to fail negotiating the https with the onclickapp store, in the captain-captain container.

I assume that curl is used behind the screen to fetch the the list of oneclick apps.  There is definatly a problem with the version of curl in the caprover/captain image accessing the oneclickapp list.

I have a fresh caprover install, everything works except fetching the list of oneclick apps.
I dont use onclick apps much as I find that it is out of date, but I recomend it to others who do, some have reported issues to me about accessing the oneclick apps from their systems.

**Comment by githubsaturn** [comment]
That shouldn't be the case. Thousands of CapRover instances are running worldwide and no one is reporting this issue. 

I just confirmed on all my own prod instances that one click apps feature is working fine.

Perhaps there is an issue with your host. What host and what OS are you using? Try using an Ubuntu 20 machine from DigitalOcean.

**Comment by stuffa** [comment]
I am self hosting on a rPi4 with 8G Ram and a 1TB driveRunning Ubuntu 22.04 (ARM) LTE, with the rPi extension modules to get the network driverLatest Docker engine,  Just rebuilt as It was no longer issuing certs. The certbot container would not start
As I said everything is fine except fetching oneclickapps
running curl on the host works fine, everywhererunning curl in the container hangs during the SSL handshake to oneclickappsrunning curl in the container works over SSL to www.google.com
I have not found another SSL location where it fails.  I am sure that there are others. I have only tested a handful of well know URLS

This is the debug output from curl in the container to https://oneclickapps.caprover.com/v4/list

```
root@88212178d4cf:/usr/src/app# curl -vvI https://oneclickapps.caprover.com/v4/list
*   Trying 185.199.109.153...
* TCP_NODELAY set
*   Trying 2606:50c0:8001::153...
* TCP_NODELAY set
* Immediate connect fail for 2606:50c0:8001::153: Cannot assign requested address
*   Trying 2606:50c0:8000::153...
* TCP_NODELAY set
* Immediate connect fail for 2606:50c0:8000::153: Cannot assign requested address
*   Trying 2606:50c0:8002::153...
* TCP_NODELAY set
* Immediate connect fail for 2606:50c0:8002::153: Cannot assign requested address
*   Trying 2606:50c0:8003::153...
* TCP_NODELAY set
* Immediate connect fail for 2606:50c0:8003::153: Cannot assign requested address
* Connected to oneclickapps.caprover.com (185.199.109.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
```
At this point it hangs.

As you can see it connects, but does not complete the SSL handshake

Here is the same going to https://www.google.com

```
root@88212178d4cf:/usr/src/app# curl -vvv https://oneclickapps.caprover.com/v4/list
*   Trying 185.199.109.153...
* TCP_NODELAY set
*   Trying 2606:50c0:8001::153...
* TCP_NODELAY set
* Immediate connect fail for 2606:50c0:8001::153: Cannot assign requested address
*   Trying 2606:50c0:8000::153...
* TCP_NODELAY set
* Immediate connect fail for 2606:50c0:8000::153: Cannot assign requested address
*   Trying 2606:50c0:8002::153...
* TCP_NODELAY set
* Immediate connect fail for 2606:50c0:8002::153: Cannot assign requested address
*   Trying 2606:50c0:8003::153...
* TCP_NODELAY set
* Immediate connect fail for 2606:50c0:8003::153: Cannot assign requested address
* Connected to oneclickapps.caprover.com (185.199.109.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to oneclickapps.caprover.com:443 
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to oneclickapps.caprover.com:443 
root@88212178d4cf:/usr/src/app# 
root@88212178d4cf:/usr/src/app# 
root@88212178d4cf:/usr/src/app# 
root@88212178d4cf:/usr/src/app# curl -vvI https://www.google.com                   
* Rebuilt URL to: https://www.google.com/
*   Trying 142.250.76.100...
* TCP_NODELAY set
* Connected to www.google.com (142.250.76.100) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=www.google.com
*  start date: May 19 12:58:13 2023 GMT
*  expire date: Aug 11 12:58:12 2023 GMT
*  subjectAltName: host "www.google.com" matched cert's "www.google.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0xaaaad9fb5b50)
> HEAD / HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.52.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
HTTP/2 200 
< content-type: text/html; charset=ISO-8859-1
content-type: text/html; charset=ISO-8859-1
< content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-astVGYYvu2Xh87r2CkfjHw' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-astVGYYvu2Xh87r2CkfjHw' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
< p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
< date: Thu, 08 Jun 2023 05:15:38 GMT
date: Thu, 08 Jun 2023 05:15:38 GMT
< server: gws
server: gws
< x-xss-protection: 0
x-xss-protection: 0
< x-frame-options: SAMEORIGIN
x-frame-options: SAMEORIGIN
< expires: Thu, 08 Jun 2023 05:15:38 GMT
expires: Thu, 08 Jun 2023 05:15:38 GMT
< cache-control: private
cache-control: private
< set-cookie: 1P_JAR=2023-06-08-05; expires=Sat, 08-Jul-2023 05:15:38 GMT; path=/; domain=.google.com; Secure
set-cookie: 1P_JAR=2023-06-08-05; expires=Sat, 08-Jul-2023 05:15:38 GMT; path=/; domain=.google.com; Secure
< set-cookie: AEC=AUEFqZfM9fpr8TkP4X2z13pKNZVAlhJFI6kulnnM_aZG1yn06p8hsTzRnQ; expires=Tue, 05-Dec-2023 05:15:38 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
set-cookie: AEC=AUEFqZfM9fpr8TkP4X2z13pKNZVAlhJFI6kulnnM_aZG1yn06p8hsTzRnQ; expires=Tue, 05-Dec-2023 05:15:38 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
< set-cookie: NID=511=kIAKU6WBVhYZOJH7OagfHHRLF5t-fDeTFvr6Z5nOEVvBMqv-Inon-5Y2SMU1ezobycsOKWFIzMmrauH12_UwMRtaTygOsLzUeSwsLz8F23VQEFROQGgr3kHhpOZ4DAJ9O6ILBvSquNGivzwn8vREeGpoJAPhWYYMbnRX8B6JW7w; expires=Fri, 08-Dec-2023 05:15:38 GMT; path=/; domain=.google.com; HttpOnly
set-cookie: NID=511=kIAKU6WBVhYZOJH7OagfHHRLF5t-fDeTFvr6Z5nOEVvBMqv-Inon-5Y2SMU1ezobycsOKWFIzMmrauH12_UwMRtaTygOsLzUeSwsLz8F23VQEFROQGgr3kHhpOZ4DAJ9O6ILBvSquNGivzwn8vREeGpoJAPhWYYMbnRX8B6JW7w; expires=Fri, 08-Dec-2023 05:15:38 GMT; path=/; domain=.google.com; HttpOnly
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

< 
* Curl_http_done: called premature == 0
* Connection #0 to host www.google.com left intact
```


TCP time out is probably still set at 2hrs,  I will reduce it and see what happens
I will also try an install on Linode.  I have an account there.

**Comment by maietta** [comment]
If your IP is a remote gateway, you need to enable ipv4 forwarding.

**Comment by maietta** [comment]
If your IP is a remote gateway, you need to enable ipv4 forwarding.

I see that you're using a Pi 4. I doubt you're using a directly assigned public ip. I suspect you're using Wireguard to a remote vps with a public facing ip.

Everything works, you can reach your instance, but your pi can't resolve some hostnames. 

On your vps, you need to enable ip4 forwarding so that traffic from your pi can reach the internet via your public facing static IP.

Am I in the ballpark?

**Comment by stuffa** [comment]
You are correct.  Today I am using a wireguard tunnel.  Other times I use a
DMZ host configuration.
and other times I run locally, as there is no internet connection, depends
where I am working

Routing works fine from the host, and the container.
dns resolution is also fine from the host and the container
I can successfully  ping oneclickapps, proving that routing and dns are all
ok

So routing, dns, etc are all good and I can curl "curl" and "wget"
destinations from all over the internet via SSL,  Just not oneclickapps
Note:  "wget" behaves the same as curl in the container.  ie: I can not
reach oneclick and only oneclick

I am beginning to think it is a SSL library problem.  And that the SSL
library does not like your certificate.
And that the SSL library problem is specific to ARM.

In the container, both curl and wget hang after a successful TCP connection
has been made to oneclickapps
from the host (rpi) both curl and wget work ok

Maybe I should try running "edge", but I don't know how to switch from
release to edge, and edge back to release.
perhaps I should build my own container from source, node:14 is now based
on buster not stretch, or even change to node:14-bullseye
This is the reason that I think an image update may be desirable

Cheers

--------------------------------------------------------
Chris Martin
m: +61 419 812 371
e: ***@***.***
--------------------------------------------------------

**Comment by maietta** [comment]
I deleted my previous response because I got to thinking, there's no way my edge case would apply in your case.

Anyway, I should not have deleted it.

In a nutshell, if you are hosting your Pi and one one of your Wireguard or other tunnel, you will also need to enable IPv4 forwarding on the server that hosts the entry point of your tunnel. (i.e., the side with the static IP)

While initially you may be able to reach some services with ping, curl, et cetera from your Pi, you'll discover that some services, such as from the containers may in fact not be able to reach the outside world without this IPv4 forwarding enabled.
