### ISSUE TITLE
[Deployment Issue] Issue with nginx container gone after restart

### ISSUE THREAD

**Issue by Svelte-Enthusiast** [caprover/caprover#1746]
What is the problem?
After restarting my server, Caprover no longer properly startus up and it seems like the nginx container has just disappeared. 

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
Linux arm-server 5.15.0-1034-oracle #40-Ubuntu SMP Wed Apr 19 16:10:04 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
               total        used        free      shared  buff/cache   available
Mem:            23Gi       3.7Gi       8.0Gi        11Mi        11Gi        19Gi
Swap:             0B          0B          0B
```
Running docker ps shows the following containers

```
CONTAINER ID   IMAGE                                          COMMAND                  CREATED         STATUS                 PORTS                                       NAMES
30a51a30e384   caprover/certbot-sleeping:v1.6.0               "/bin/sh -c 'sleep 9…"   7 minutes ago   Up 6 minutes           80/tcp, 443/tcp                             captain-certbot.1.pd0hsw5jc0u2uabtgbcttbxpo
3a5a71e742c9   caprover/caprover:latest                       "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes           0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   captain-captain.1.9xq5er2rs8aket79cutl3qqml
```
It seems like the nginx container is missing. 

Running docker logs on the caprover container results in the following

```
Captain Starting ...
Overriding skipVerifyingDomains from /captain/data/config-override.json
May 10th 2023, 11:50:32.901 pm    Emptying generated and temp folders.
May 10th 2023, 11:50:32.910 pm    Ensuring directories are available on host. Started.
May 10th 2023, 11:50:32.916 pm    Ensuring directories are available on host. Finished.
May 10th 2023, 11:50:32.923 pm    Network captain-overlay-network is already attached to service: captain-captain
May 10th 2023, 11:50:32.929 pm    captain-captain (service) has already been connected to secret: captain-salt
May 10th 2023, 11:50:32.931 pm    Migration not needed, skipping.
May 10th 2023, 11:50:32.942 pm    Copying fake certificates...
May 10th 2023, 11:50:32.946 pm    Updating Load Balancer - Setting up NGINX conf file...
May 10th 2023, 11:50:32.947 pm    Locking NGINX configuration reloading...
May 10th 2023, 11:50:32.978 pm    SUCCESS: UNLocking NGINX configuration reloading...
May 10th 2023, 11:50:32.980 pm    Captain Nginx is already running..
May 10th 2023, 11:50:35.984 pm    Retrying to get NodeID for captain-nginx retry count:0
May 10th 2023, 11:50:38.989 pm    Retrying to get NodeID for captain-nginx retry count:1
May 10th 2023, 11:50:41.993 pm    Retrying to get NodeID for captain-nginx retry count:2
May 10th 2023, 11:50:44.998 pm    Retrying to get NodeID for captain-nginx retry count:3
May 10th 2023, 11:50:48.001 pm    Retrying to get NodeID for captain-nginx retry count:4
May 10th 2023, 11:50:48.003 pm    Updating NGINX service...
May 10th 2023, 11:50:48.012 pm    Waiting for 5 seconds for nginx reload to take into effect
May 10th 2023, 11:50:53.013 pm    Pruning containers...
May 10th 2023, 11:50:53.014 pm    NGINX is fully set up and working...
May 10th 2023, 11:50:53.018 pm    Captain Certbot is already running..
May 10th 2023, 11:50:53.021 pm    Updating Certbot service...
May 10th 2023, 11:50:53.028 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive
May 10th 2023, 11:50:54.700 pm    **** Captain is initialized and ready to serve you! ****
May 10th 2023, 11:50:58.028 pm    Pruning containers...
May 10th 2023, 11:51:07.709 pm    Retrying to get containerId for captain-certbot retry count:0
May 10th 2023, 11:51:10.713 pm    Retrying to get containerId for captain-certbot retry count:1
May 10th 2023, 11:51:10.715 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive
May 10th 2023, 11:51:12.162 pm    executeCommand Container: captain-certbot certbot renew --non-interactive
May 10th 2023, 11:52:12.891 pm    Updating Load Balancer - renewAllCerts
May 10th 2023, 11:52:12.891 pm    Locking NGINX configuration reloading...
May 10th 2023, 11:52:12.920 pm    SUCCESS: UNLocking NGINX configuration reloading...
May 10th 2023, 11:52:12.920 pm    sendReloadSignal...
May 10th 2023, 11:52:15.923 pm    Retrying to get containerId for captain-nginx retry count:0
May 10th 2023, 11:52:18.927 pm    Retrying to get containerId for captain-nginx retry count:1
May 10th 2023, 11:52:21.930 pm    Retrying to get containerId for captain-nginx retry count:2
May 10th 2023, 11:52:24.935 pm    Retrying to get containerId for captain-nginx retry count:3
May 10th 2023, 11:52:27.938 pm    Retrying to get containerId for captain-nginx retry count:4
May 10th 2023, 11:52:30.942 pm    Retrying to get containerId for captain-nginx retry count:5
May 10th 2023, 11:52:33.945 pm    Retrying to get containerId for captain-nginx retry count:6
May 10th 2023, 11:52:36.949 pm    Retrying to get containerId for captain-nginx retry count:7
May 10th 2023, 11:52:39.952 pm    Retrying to get containerId for captain-nginx retry count:8
May 10th 2023, 11:52:39.955 pm    Kill HUP Container: ac126479b89be5f756c7e997b8f5defe94ad0650cf5d0fd15527250450d05824
May 10th 2023, 11:52:40.214 pm    Error: (HTTP code 409) unexpected - Cannot kill container: ac126479b89be5f756c7e997b8f5defe94ad0650cf5d0fd15527250450d05824: Container ac126479b89be5f756c7e997b8f5defe94ad0650cf5d0fd15527250450d05824 is not running
Error: (HTTP code 409) unexpected - Cannot kill container: ac126479b89be5f756c7e997b8f5defe94ad0650cf5d0fd15527250450d05824: Container ac126479b89be5f756c7e997b8f5defe94ad0650cf5d0fd15527250450d05824 is not running
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:315:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:345:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:314:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:286:14)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

How can I go about resolving this issue?

**Comment by maietta** [comment]
I feel like I've seen this before.

Have you gone through the troubleshooting guide?

Have you modified the Nginx config in any way?

**Comment by githubsaturn** [comment]
Run `docker service ps` and find out what's happening. Regardless, it's not CapRover keeping your nginx alive after a reboot, it's Docker swarm.

**Comment by Svelte-Enthusiast** [comment]
> I feel like I've seen this before.
> 
> Have you gone through the troubleshooting guide?
> 
> Have you modified the Nginx config in any way?

I had not modified the Nginx config and I also went through the troubleshooting guide. 



> Run `docker service ps captain-nginx --no-trunc` and find out what's happening. Regardless, it's not CapRover keeping your nginx alive after a reboot, it's Docker swarm.

I ran that command and it seems like that port 80 was already in use so the Nginx container could not properly bind to that port. 
```
sudo kill -9 `sudo lsof -t -i:80`
```
Running this command got caprover working again. Thanks 👍.
