### ISSUE TITLE
CapRover not responding after installation on VPS

### ISSUE THREAD

**Issue by AndreuSerraSastre** [caprover/caprover#1759]
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-125-generic x86_64)

I have rented an Ubuntu server on IONOS, a VPS, and opened the necessary ports in the firewall. I have installed Docker and CapRover, and everything seems to have gone well. However, when I try to access http://<your-server-ip-address>:3000, it doesn't respond.

To check if it was a port issue, I created a Node.js application and ran it on port 3000 without any problems. I have tried everything.

I followed the official installation guide step-by-step and made no modifications or unusual changes. The latest installation attempt I tried was:

Fresh Ubuntu 20.04.4 installation

Docker:
```
sudo apt update
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt update
sudo apt install docker-ce=5:19.03.15~3-0~ubuntu-$(lsb_release -cs)
docker --version
```
```
Docker version 19.03.15, build 99e3ed8919
```
Caprover
```
ufw status
Status: inactive

docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
Unable to find image 'caprover/caprover:latest' locally
latest: Pulling from caprover/caprover
af4c2580c6c3: Pull complete
4ea40d27a2cf: Pull complete
523d612e9cd2: Pull complete
8fee6a1847b0: Pull complete
60cce3519052: Pull complete
4bae1011637c: Pull complete
ecf48b6c1f43: Pull complete
856f69196742: Pull complete
e86a512b6f8c: Pull complete
cecbd06d956f: Pull complete
cdd679ff24b0: Pull complete
d60abbe06609: Pull complete
0ac0240c1a59: Pull complete
52d300ad83da: Pull complete
Digest: sha256:39c3f188a8f425775cfbcdc4125706cdf614cd38415244ccf967cd1a4e692b4f
Status: Downloaded newer image for caprover/caprover:latest
Captain Starting ...
Installing Captain Service ...

 Installation of CapRover is starting...
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html





 >>> Checking System Compatibility <<<
   Docker Version passed.
   Ubuntu detected.
   X86 CPU detected.
   Total RAM 16755 MB
Pulling: nginx:1
Pulling: caprover/caprover-placeholder-app:latest
Pulling: caprover/certbot-sleeping:v1.6.0
May 24th 2023, 6:19:01.164 am    Fresh installation!
May 24th 2023, 6:19:01.166 am    Starting swarm at 217.160.114.241:2377
Swarm started: q2eby4ne2wysuq9g7ozh36rb2
*** CapRover is initializing ***
Please wait at least 60 seconds before trying to access CapRover.
```

However, it's not working, and I don't know what else to do.

```
/captain/data/config-captain.json. :

{
	"namespace": "captain"
}
```

**Comment by githubsaturn** [comment]
Run these commands and copy the output here.

```
docker service ls
docker service logs captain-captain --since 5m
docker service ps captain-captain --no-trunc
```

**Comment by AndreuSerraSastre** [comment]
```
root@ubuntu:~# docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                              PORTS
r9w8lfqerljx        captain-captain     replicated          1/1                 caprover/caprover:1.10.1
wlacmh6a078t        captain-certbot     replicated          1/1                 caprover/certbot-sleeping:v1.6.0
s66i1p8dfcnj        captain-nginx       replicated          1/1                 nginx:1
root@ubuntu:~# docker service logs captain-captain --since 5m
captain-captain.1.pvrqic9c1dwx@ubuntu    | Captain Starting ...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.318 am    Emptying generated and temp folders.
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.322 am    Ensuring directories are available on host. Started.
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.326 am    Ensuring directories are available on host. Finished.
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.330 am    Network captain-overlay-network is already attached to service:                                                                                                   captain-captain
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.334 am    captain-captain (service) has already been connected to secret:                                                                                                   captain-salt
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.335 am    Migration not needed, skipping.
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.339 am    Copying fake certificates...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.341 am    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.342 am    Locking NGINX configuration reloading...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.346 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.348 am    No Captain Nginx service is running. Creating one on captain no                                                                                                  de...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:04.351 am    Waiting for 5 seconds for nginx to start up
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:09.357 am    Updating NGINX service...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:09.365 am    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:14.368 am    Pruning containers...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:14.370 am    NGINX is fully set up and working...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:14.374 am    No Captain Certbot service is running. Creating one...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:14.374 am    Creating Certbot service
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:14.378 am    Waiting for Certbot...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:26.397 am    Updating Certbot service...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:29.421 am    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:31.417 am    Pruning containers...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:32.425 am    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:35.432 am    Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:38.438 am    Retrying to get containerId for captain-certbot retry count:3
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:41.444 am    Retrying to get containerId for captain-certbot retry count:4
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:44.450 am    Retrying to get containerId for captain-certbot retry count:5
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:44.453 am    executeCommand Container: captain-certbot certbot certificates                                                                                                   --non-interactive
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:45.090 am    **** Captain is initialized and ready to serve you! ****
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:55:55.101 am    Creating dhparams for the first time - high CPU load is expecte                                                                                                  d.
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:36.839 am    Updating Load Balancer - ensureDhParamFileExists
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:36.840 am    Locking NGINX configuration reloading...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:36.846 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:36.846 am    sendReloadSignal...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:36.851 am    Kill HUP Container: 87ecacc2d4c90e37c7c37434fdf1571dfa6e8070911                                                                                                  afe120bd6a9307507d077
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:36.868 am    executeCommand Container: captain-certbot certbot certificates                                                                                                   --non-interactive
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:37.411 am    executeCommand Container: captain-certbot certbot renew --non-i                                                                                                  nteractive
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:37.934 am    Updating Load Balancer - renewAllCerts
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:37.934 am    Locking NGINX configuration reloading...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:37.937 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:37.937 am    sendReloadSignal...
captain-captain.1.pvrqic9c1dwx@ubuntu    | May 25th 2023, 5:56:37.939 am    Kill HUP Container: 87ecacc2d4c90e37c7c37434fdf1571dfa6e8070911                                                                                                  afe120bd6a9307507d077
root@ubuntu:~# docker service ps captain-captain --no-trunc
ID                          NAME                    IMAGE                      NODE                DESIRED STATE       CURRENT STATE            ERROR               PORTS
pvrqic9c1dwx433rr0j26q53c   captain-captain.1       caprover/caprover:1.10.1   ubuntu              Running             Running 3 minutes ago                        *:3000->3000/tcp
xdihaaig5dnpq4pv9n70y6anh    \_ captain-captain.1   caprover/caprover:1.10.1   ubuntu              Shutdown            Shutdown 4 minutes ago
q3tzmb6xjaubft9dsbzweebx6    \_ captain-captain.1   caprover/caprover:1.10.1   ubuntu              Shutdown            Shutdown 4 minutes ago

```

**Comment by AndreuSerraSastre** [comment]
That's the issue, everything seems correct, it looks like everything is working, but when I access the CapRover panel at http://[IP_OF_YOUR_SERVER]:3000 there's nothing there, it doesn't load, it doesn't respond. However, the ports are properly opened in the firewall and everywhere else. To test it, I installed a Node app on port 3000, and it worked, but when I installed CapRover, it didn't. It's as if it's not listening or not present at port 3000, even though it says it is.

**Comment by githubsaturn** [comment]
@AndreuSerraSastre 

On your server, run `curl -v http://localhost:3000`

What does it print?

**Comment by githubsaturn** [comment]
So it stalls... Run `docker service ls` and `docker service logs captain-captain --since 60m`

**Comment by AndreuSerraSastre** [comment]
@githubsaturn 

I've installed CapRover on this server several times, I've tried it in many ways, I just installed it again, it doesn't matter which version of Ubuntu I use, 18, 20, or 22, and I've tried different versions of Docker... and nothing. Two things always happen to me, if it installs, I can't access it, but there are times (many times), this happens:

```
 >>> Checking System Compatibility <<<
   Docker Version passed.
   Ubuntu detected.
   X86 CPU detected.
   Total RAM 16744 MB
Installation failed.
Error: Couldn't find your IP
    at /usr/src/app/node_modules/public-ip/index.js:172:10
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /usr/src/app/node_modules/public-ip/index.js:199:15
```

This is fixed by restarting the server once or twice, then it lets you install it.

I'm trying this out: https://gist.github.com/hivivo/20eb5355837533c968ecb9e684f85007

**Comment by githubsaturn** [comment]
> This is fixed by restarting the server once or twice, then it lets you install it.

If constant restarts fixes some issues, it's an indication that something is wrong on your server. What VPS provider are you using?

Try using well tested providers like DigitalOcean.

**Comment by AndreuSerraSastre** [comment]
@githubsaturn

IONOS 

Type: Virtual Machine
Size: VPS XL
CPU: 8 vCore
RAM: 16 GB
Data storage: 320 GB SSD

I've already purchased the machine, they say it's not their problem, I want to find out why this is happening because if it is their fault, they'll have to fix it or give me my money back.

I have successfully installed CapRover on more than 10 servers over the past 2 years, we have over 20 applications across all of them.

**Comment by githubsaturn** [comment]
It's very likely that the OS that they have is a modified version of Ubuntu and it's missing some kernels. Cheap providers do this all the time in hopes of optimizing their servers - but in reality they break many things (mostly on the networking layer)

**Comment by maietta** [comment]
@AndreuSerraSastre, I'm going to throw this out there, because it tends to be a common enough problem that you yourself might be running into. I myself have had issues getting the official install docs to work with Ubuntu 20.04.x. The convenience script however, does work.

Uninstall docker completely, per the official docs, then use their "convenience script" to re-install with the known working tooling Docker themselves have fully tested.

Fully remove docker:
`sudo apt-get remove docker docker-engine docker.io containerd runc`

Then fetch and run the convenience script:
`curl -fsSL https://get.docker.com -o get-docker.sh`

`sudo sh get-docker.sh`

You may not even need to re-install CapRover. It may simply work.

**Comment by AndreuSerraSastre** [comment]
@githubsaturn 

I've tried it, I even returned the server and got another one from IONOS, but I'm still getting the same result (I installed Docker as you instructed).

**Comment by githubsaturn** [comment]
If it's an Ubuntu kernel issue then getting a new server is not going to help because it has the same kernels

**Comment by maietta** [comment]
> 

Try a different VPS provider. Vultr, Digital Ocean are great choices and offer cheap servers, but also let you install your own ISO images if you'd like.

**Comment by SpaceIgniter** [comment]
I'm running into the exact same issue on a Webdock VPS. It's a pity, since I'm loving Webdock so far. I'll have to look for an alternative though. Really strange and apt that I was able to find the exact cause of my issues here. Thanks for the contributions. It makes my insanity bearable now.

**Comment by SpaceIgniter** [comment]
I'd like to respond with an update. Webdock informed me a while ago that the issue might be with the "type" of VPS I was deploying. They suggested I use a KVM VPS and not a LXD-based VPS. I setup Caprover today on a KVM instance with absolutely zero issues. Hopefully this will help anyone in future that has similar Caprover deployment issues.
