### ISSUE TITLE
Strapi projects not working (one-clicks apps or local development)

### ISSUE THREAD

**Issue by bymustfa** [caprover/caprover#1910]
Hello.
I can't get Starpi projects to run on CapRover. This includes Strapi applications found within one-click apps as well.
However, the issue I'm experiencing is quite confusing. First, let me show you the content of my captain-definition file, then the content of my Dockerfile, and finally the error I received.

**_Quick Summary:_**
When I deploy my project, developed with Strapi in my local environment, using a Dockerfile on my CapRover server, it throws very confusing and non-existent file-related errors at me. For example, it says "dist/config/._admin.js Unexpected token," but as you all know, there is no such file; there's only "admin.js." When I build with Docker on my computer, I don't encounter any issues, but whenever I upload it to CapRover, I face these problems. It either gives an error in "dist/config/._admin.js" or "src/api/blog/content-types/blog/.schema.json," but there is no file starting with "._" anywhere in the project.

I've been trying to solve this problem for weeks; please help.

captain-defination:
```json
 {
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile"
 }
```

Dockerfile:
```Dockerfile
FROM node:18.9.0-alpine as BUILD_IMAGE
WORKDIR /app
RUN npm cache clean --force
COPY package.json yarn.lock ./
RUN apk add --no-cache git
RUN yarn install --verbose
COPY . .
FROM node:18.9.0-alpine
WORKDIR /app
COPY --from=BUILD_IMAGE /app/package.json ./package.json
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules
COPY --from=BUILD_IMAGE /app/.cache ./.cache
COPY --from=BUILD_IMAGE /app/dist ./dist
COPY --from=BUILD_IMAGE /app/config ./config
COPY --from=BUILD_IMAGE /app/database ./database
COPY --from=BUILD_IMAGE /app/public ./public
COPY --from=BUILD_IMAGE /app/src ./src
COPY --from=BUILD_IMAGE /app/src/admin ./src/admin
COPY --from=BUILD_IMAGE /app/src/api ./src/api
COPY --from=BUILD_IMAGE /app/src/extensions ./src/extensions
COPY --from=BUILD_IMAGE /app/src/index.ts ./src/index.ts
COPY --from=BUILD_IMAGE /app/types ./types
COPY --from=BUILD_IMAGE /app/.env* ./
COPY --from=BUILD_IMAGE /app/.strapi-updater.json ./.strapi-updater.json
RUN chown -R 1001520000:1001520000 ./
EXPOSE 1337
CMD ["yarn", "start"]


```

Error:

```txt
2023-10-08T20:17:31.370316549Z yarn run v1.22.19
2023-10-08T20:17:31.412261318Z $ strapi start
2023-10-08T20:17:33.895403519Z [2023-10-08 20:17:33.893] debug: ⛔️ Server wasn't able to start properly.
2023-10-08T20:17:33.896638641Z [2023-10-08 20:17:33.895] error: /app/src/api/blog/content-types/blog/._schema.json: Unexpected token  in JSON at position 0
2023-10-08T20:17:33.896649034Z SyntaxError: /app/src/api/blog/content-types/blog/._schema.json: Unexpected token  in JSON at position 0
2023-10-08T20:17:33.896652237Z at JSON.parse (<anonymous>)
2023-10-08T20:17:33.896655045Z at Object._readFile (/app/node_modules/jsonfile/index.js:25:16)
2023-10-08T20:17:33.896657750Z at async loadDir (/app/node_modules/@strapi/strapi/dist/core/loaders/apis.js:141:36)
2023-10-08T20:17:33.896660466Z at async loadContentTypes (/app/node_modules/@strapi/strapi/dist/core/loaders/apis.js:122:29)
2023-10-08T20:17:33.896663170Z at async Promise.all (index 7)
2023-10-08T20:17:33.896665844Z at async loadAPI (/app/node_modules/@strapi/strapi/dist/core/loaders/apis.js:84:97)
2023-10-08T20:17:33.896668482Z at async Object.loadAPIs (/app/node_modules/@strapi/strapi/dist/core/loaders/apis.js:54:21)
2023-10-08T20:17:33.896671090Z at async Strapi.loadAPIs (/app/node_modules/@strapi/strapi/dist/Strapi.js:379:9)
2023-10-08T20:17:33.896673649Z at async Promise.all (index 5)
2023-10-08T20:17:33.896676060Z at async Strapi.register (/app/node_modules/@strapi/strapi/dist/Strapi.js:407:9)
2023-10-08T20:17:33.934823677Z error Command failed with exit code 1.
2023-10-08T20:17:33.935070274Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by githubsaturn** [comment]
> When I build with Docker on my computer, I don't encounter any issues

Quite likely you have some files that are not version checked. First, convert your repo to tar file, then extract that content and try to build using `docker build.....`. Does it work?

```
# first run this:
git archive --format tar --output ./output.tar master

## then move the tar file to a new directory and unpack the content

## finally run docker build
docker built -t my-test-image -f Dockerfile . 

docker run -it my-test-image
```

Does this work? Or do you see the error that happens on CapRover as well?

**Comment by bymustfa** [comment]
Hello. Yes, I did what you said, and Docker on my computer worked smoothly. But Caprover has an issue.

**Comment by githubsaturn** [comment]
Can you share a repo with me?

**Comment by githubsaturn** [comment]
You can create a simple plain strapi project that exhibits the same behavior. Meaning that it works successfully locally, but it fails on CapRover

**Comment by bymustfa** [comment]
I think it's because of the tar file.

**Comment by bymustfa** [comment]
I think it's because of the tar file.
