### ISSUE TITLE
[Question] Strapi problem on deploy

### ISSUE THREAD

**Issue by Hertak** [caprover/caprover#1916]
Hi, i´m trying install Strapi with naskio image from dockerhub but i cant. On logs i get a message running all time. I put bellow.  The message say that i need install pg the problem is that caprover create a container try deploy, destroy container and try again and everytime with a new name. That make i dont have time to search name of the contaiiner, enter and run npm -i pg.
I don´t have many experience with this things. What i`m making wrong? Is there a way to run commands on caprover?  Any help? Thanks. 

Here is the log 
```
2023-10-11T00:18:51.449107575Z Starting your app (with develop)...
2023-10-11T00:18:54.082663444Z Building your admin UI with development configuration...
2023-10-11T00:18:54.085298865Z Admin UI built successfully
2023-10-11T00:18:57.225411291Z Knex: run
2023-10-11T00:18:57.225437751Z $ npm install pg --save
2023-10-11T00:18:57.225443271Z Cannot find module 'pg'
2023-10-11T00:18:57.225447611Z Require stack:
2023-10-11T00:18:57.225451921Z - /srv/app/node_modules/knex/lib/dialects/postgres/index.js
2023-10-11T00:18:57.225456591Z - /srv/app/node_modules/knex/lib/dialects/index.js
2023-10-11T00:18:57.225460931Z - /srv/app/node_modules/knex/lib/knex-builder/internal/config-resolver.js
2023-10-11T00:18:57.225465251Z - /srv/app/node_modules/knex/lib/knex-builder/Knex.js
2023-10-11T00:18:57.225469581Z - /srv/app/node_modules/knex/lib/index.js
2023-10-11T00:18:57.225473801Z - /srv/app/node_modules/knex/knex.js
2023-10-11T00:18:57.225477971Z - /srv/app/node_modules/@strapi/database/lib/connection.js
2023-10-11T00:18:57.225482201Z - /srv/app/node_modules/@strapi/database/lib/index.js
2023-10-11T00:18:57.225486421Z - /srv/app/node_modules/@strapi/strapi/dist/Strapi.js
2023-10-11T00:18:57.225490711Z - /srv/app/node_modules/@strapi/strapi/dist/index.js
2023-10-11T00:18:57.225494951Z - /srv/app/node_modules/@strapi/strapi/dist/commands/actions/develop/action.js
2023-10-11T00:18:57.225499351Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/utils/helpers.js
2023-10-11T00:18:57.225505811Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/actions/admin/create-user/command.js
2023-10-11T00:18:57.225510241Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/index.js
2023-10-11T00:18:57.225514591Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/bin/strapi.js
2023-10-11T00:18:57.225518991Z Error: Cannot find module 'pg'
2023-10-11T00:18:57.225523181Z Require stack:
2023-10-11T00:18:57.225527411Z - /srv/app/node_modules/knex/lib/dialects/postgres/index.js
2023-10-11T00:18:57.225531671Z - /srv/app/node_modules/knex/lib/dialects/index.js
2023-10-11T00:18:57.225535901Z - /srv/app/node_modules/knex/lib/knex-builder/internal/config-resolver.js
2023-10-11T00:18:57.225540171Z - /srv/app/node_modules/knex/lib/knex-builder/Knex.js
2023-10-11T00:18:57.225544431Z - /srv/app/node_modules/knex/lib/index.js
2023-10-11T00:18:57.225548661Z - /srv/app/node_modules/knex/knex.js
2023-10-11T00:18:57.225552861Z - /srv/app/node_modules/@strapi/database/lib/connection.js
2023-10-11T00:18:57.225557091Z - /srv/app/node_modules/@strapi/database/lib/index.js
2023-10-11T00:18:57.225561351Z - /srv/app/node_modules/@strapi/strapi/dist/Strapi.js
2023-10-11T00:18:57.225565571Z - /srv/app/node_modules/@strapi/strapi/dist/index.js
2023-10-11T00:18:57.225587571Z - /srv/app/node_modules/@strapi/strapi/dist/commands/actions/develop/action.js
2023-10-11T00:18:57.225592171Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/utils/helpers.js
2023-10-11T00:18:57.225596551Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/actions/admin/create-user/command.js
2023-10-11T00:18:57.225600981Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/index.js
2023-10-11T00:18:57.225606511Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/bin/strapi.js
2023-10-11T00:18:57.225610901Z at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
2023-10-11T00:18:57.225615261Z at Module._load (node:internal/modules/cjs/loader:922:27)
2023-10-11T00:18:57.225619651Z at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-10-11T00:18:57.225623921Z at require (node:internal/modules/cjs/helpers:119:18)
2023-10-11T00:18:57.225628171Z at Client_PG._driver (/srv/app/node_modules/knex/lib/dialects/postgres/index.js:63:12)
2023-10-11T00:18:57.225632501Z at Client_PG.initializeDriver (/srv/app/node_modules/knex/lib/client.js:198:26)
2023-10-11T00:18:57.225636791Z at new Client (/srv/app/node_modules/knex/lib/client.js:83:12)
2023-10-11T00:18:57.225641031Z at new Client_PG (/srv/app/node_modules/knex/lib/dialects/postgres/index.js:21:5)
2023-10-11T00:18:57.225645331Z at knex (/srv/app/node_modules/knex/lib/knex-builder/Knex.js:16:28)
2023-10-11T00:18:57.225649681Z at createConnection (/srv/app/node_modules/@strapi/database/lib/connection.js:55:24)
2023-10-11T00:18:57.226795181Z Error: Knex: run
2023-10-11T00:18:57.226804521Z $ npm install pg --save
2023-10-11T00:18:57.226808331Z Cannot find module 'pg'
2023-10-11T00:18:57.226811721Z Require stack:
2023-10-11T00:18:57.226815141Z - /srv/app/node_modules/knex/lib/dialects/postgres/index.js
2023-10-11T00:18:57.226818571Z - /srv/app/node_modules/knex/lib/dialects/index.js
2023-10-11T00:18:57.226822011Z - /srv/app/node_modules/knex/lib/knex-builder/internal/config-resolver.js
2023-10-11T00:18:57.226825811Z - /srv/app/node_modules/knex/lib/knex-builder/Knex.js
2023-10-11T00:18:57.226829191Z - /srv/app/node_modules/knex/lib/index.js
2023-10-11T00:18:57.226832531Z - /srv/app/node_modules/knex/knex.js
2023-10-11T00:18:57.226835871Z - /srv/app/node_modules/@strapi/database/lib/connection.js
2023-10-11T00:18:57.226839271Z - /srv/app/node_modules/@strapi/database/lib/index.js
2023-10-11T00:18:57.226842631Z - /srv/app/node_modules/@strapi/strapi/dist/Strapi.js
2023-10-11T00:18:57.226845991Z - /srv/app/node_modules/@strapi/strapi/dist/index.js
2023-10-11T00:18:57.226849381Z - /srv/app/node_modules/@strapi/strapi/dist/commands/actions/develop/action.js
2023-10-11T00:18:57.226852851Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/utils/helpers.js
2023-10-11T00:18:57.226863001Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/actions/admin/create-user/command.js
2023-10-11T00:18:57.226866661Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/index.js
2023-10-11T00:18:57.226870121Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/bin/strapi.js
2023-10-11T00:18:57.226873551Z at Client_PG.initializeDriver (/srv/app/node_modules/knex/lib/client.js:202:13)
2023-10-11T00:18:57.226876981Z at new Client (/srv/app/node_modules/knex/lib/client.js:83:12)
2023-10-11T00:18:57.226880381Z at new Client_PG (/srv/app/node_modules/knex/lib/dialects/postgres/index.js:21:5)
2023-10-11T00:18:57.226883851Z at knex (/srv/app/node_modules/knex/lib/knex-builder/Knex.js:16:28)
2023-10-11T00:18:57.226887281Z at createConnection (/srv/app/node_modules/@strapi/database/lib/connection.js:55:24)
2023-10-11T00:18:57.226890711Z at new Database (/srv/app/node_modules/@strapi/database/lib/index.js:34:23)
2023-10-11T00:18:57.226894141Z at Database.init (/srv/app/node_modules/@strapi/database/lib/index.js:121:14)
2023-10-11T00:18:57.226897561Z at Strapi.bootstrap (/srv/app/node_modules/@strapi/strapi/dist/Strapi.js:440:45)
2023-10-11T00:18:57.226900991Z at Strapi.load (/srv/app/node_modules/@strapi/strapi/dist/Strapi.js:494:20)
2023-10-11T00:18:57.226904451Z at async workerProcess (/srv/app/node_modules/@strapi/strapi/dist/commands/actions/develop/action.js:100:28)
2023-10-11T00:19:03.283879282Z Starting your app (with develop)...
2023-10-11T00:19:05.911732589Z Building your admin UI with development configuration...
2023-10-11T00:19:05.913834290Z Admin UI built successfully
2023-10-11T00:19:08.987416687Z Knex: run
2023-10-11T00:19:08.987442137Z $ npm install pg --save
2023-10-11T00:19:08.987446777Z Cannot find module 'pg'
2023-10-11T00:19:08.987473267Z Require stack:
2023-10-11T00:19:08.987477267Z - /srv/app/node_modules/knex/lib/dialects/postgres/index.js
2023-10-11T00:19:08.987480867Z - /srv/app/node_modules/knex/lib/dialects/index.js
2023-10-11T00:19:08.987484327Z - /srv/app/node_modules/knex/lib/knex-builder/internal/config-resolver.js
2023-10-11T00:19:08.987487787Z - /srv/app/node_modules/knex/lib/knex-builder/Knex.js
2023-10-11T00:19:08.987491307Z - /srv/app/node_modules/knex/lib/index.js
2023-10-11T00:19:08.987494757Z - /srv/app/node_modules/knex/knex.js
2023-10-11T00:19:08.987498107Z - /srv/app/node_modules/@strapi/database/lib/connection.js
2023-10-11T00:19:08.987501507Z - /srv/app/node_modules/@strapi/database/lib/index.js
2023-10-11T00:19:08.987504878Z - /srv/app/node_modules/@strapi/strapi/dist/Strapi.js
2023-10-11T00:19:08.987508348Z - /srv/app/node_modules/@strapi/strapi/dist/index.js
2023-10-11T00:19:08.987511758Z - /srv/app/node_modules/@strapi/strapi/dist/commands/actions/develop/action.js
2023-10-11T00:19:08.987515258Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/utils/helpers.js
2023-10-11T00:19:08.987518818Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/actions/admin/create-user/command.js
2023-10-11T00:19:08.987522318Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/index.js
2023-10-11T00:19:08.987525768Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/bin/strapi.js
2023-10-11T00:19:08.987529198Z Error: Cannot find module 'pg'
2023-10-11T00:19:08.987547928Z Require stack:
2023-10-11T00:19:08.987551298Z - /srv/app/node_modules/knex/lib/dialects/postgres/index.js
2023-10-11T00:19:08.987554708Z - /srv/app/node_modules/knex/lib/dialects/index.js
2023-10-11T00:19:08.987558108Z - /srv/app/node_modules/knex/lib/knex-builder/internal/config-resolver.js
2023-10-11T00:19:08.987561578Z - /srv/app/node_modules/knex/lib/knex-builder/Knex.js
2023-10-11T00:19:08.987564998Z - /srv/app/node_modules/knex/lib/index.js
2023-10-11T00:19:08.987568358Z - /srv/app/node_modules/knex/knex.js
2023-10-11T00:19:08.987571698Z - /srv/app/node_modules/@strapi/database/lib/connection.js
2023-10-11T00:19:08.987575098Z - /srv/app/node_modules/@strapi/database/lib/index.js
2023-10-11T00:19:08.987578448Z - /srv/app/node_modules/@strapi/strapi/dist/Strapi.js
2023-10-11T00:19:08.987581808Z - /srv/app/node_modules/@strapi/strapi/dist/index.js
2023-10-11T00:19:08.987628318Z - /srv/app/node_modules/@strapi/strapi/dist/commands/actions/develop/action.js
2023-10-11T00:19:08.987632768Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/utils/helpers.js
2023-10-11T00:19:08.987636338Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/actions/admin/create-user/command.js
2023-10-11T00:19:08.987639868Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/dist/commands/index.js
2023-10-11T00:19:08.987644508Z - /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/bin/strapi.js
2023-10-11T00:19:08.987648078Z at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
2023-10-11T00:19:08.987651518Z at Module._load (node:internal/modules/cjs/loader:922:27)
2023-10-11T00:19:08.987655048Z at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-10-11T00:19:08.987658468Z at require (node:internal/modules/cjs/helpers:119:18)
2023-10-11T00:19:08.987661948Z at Client_PG._driver (/srv/app/node_modules/knex/lib/dialects/postgres/index.js:63:12)
2023-10-11T00:19:08.987665468Z at Client_PG.initializeDriver (/srv/app/node_modules/knex/lib/client.js:198:26)
2023-10-11T00:19:08.987668898Z at new Client (/srv/app/node_modules/knex/lib/client.js:83:12)
2023-10-11T00:19:08.987672328Z at new Client_PG (/srv/app/node_modules/knex/lib/dialects/postgres/index.js:21:5)
2023-10-11T00:19:08.987675778Z at knex (/srv/app/node_modules/knex/lib/knex-builder/Knex.js:16:28)
2023-10-11T00:19:08.987679208Z at createConnection (/srv/app/node_modules/@strapi/database/lib/connection.js:55:24)
2023-10-11T00:19:08.989413639Z Error: Knex: run
2023-10-11T00:19:08.989425399Z $ npm install pg --save
2023-10-11T00:19:08.989429699Z Cannot find module 'pg'
```

**Comment by Hertak** [comment]
I try with ` docker exec -it $(docker ps --filter name=srv-captain--backend-tecem -q) /bin/sh
 ` but say it´s not runing and when is running don´t giveme time to enter

**Comment by githubsaturn** [comment]
@Hertak - this is an application image, it has nothing to do with CapRover.

Just to confirm, try running the image without CapRover (use the same env vars and volumes), and you'll see the same error.

**Comment by githubsaturn** [comment]
Also, the reason that `docker exec` doesn't work is that your container fails to boot up! It's like you're trying to open a terminal on a machine that reboots as soon as it starts. 

Even if you run npm i pg in the container it doesn't last! 

You need to read more about how Docker and containers work:
https://medium.com/devops-in-depth/why-are-docker-containers-ephemeral-169c99d77455
