### ISSUE TITLE
Error in nginx

### ISSUE THREAD

**Issue by Dryrtan** [caprover/caprover#1934]
*What is the problem?*
During the CapRover deployment process, everything goes as it should, but when trying to configure the Root Domain, some errors occur that make it impossible to use CapRover. Using `caprover serversetup` an error 500 occurs when generating the SSL certificate, I tried to configure it directly using the dashboard, it accepts configuring the Root Domain but when accessing captain.xxxx.dev.br an error 502 is displayed. 

I tried to solve it using https://caprover.com/docs/troubleshooting.html#successful-deploy-but-502-bad-gateway-error but I don't think the solution applies to my problem because of the following observations I made:
On the dashboard page under Monitoring in Load Balancer Stats the following error occurs:
<img src='https://i.ibb.co/N1JPm9G/1.png'>
Apparently informed that it was not possible to connect to the captain.nginx-xxxxx container

I looked at the containers in the Portainer to see what was going on and noticed that the captain.captain-xxxxxx and captain.nginx-xxxxx containers were restarting relentlessly, from them and I noticed that the captain container does checkhealth which triggers captain.nginx-xxxxx doing an upstream "http://10.0.1.2:3000/checkhealth" even though the captain container is on another IP.

This creates an endless cycle:
The container captain.captain-xxxxxx checkshealth several times that the container captain.nginx-xxxxx tries to send everyone to "http://10.0.1.2:3000/checkhealth" which all fail because the IP of the container captain.captain-xxxxxx is different every time the container is restarted, after these attempts the containers are restarted returning to the cycle again. It is important to emphasize that in the logs of the captain.nginx-xxxxx container it always tries to upstream to "http://10.0.1.2:3000/checkhealth" regardless of the number of times it restarts.
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/11/03 17:43:36 [error] 20#20: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.31.0.1, server: captain.xxxx.dev.br, request: "GET /checkhealth HTTP/1.1", upstream: "http://10.0.1.2:3000/checkhealth", host: "captain.xxxx.dev.br"
2023/11/03 17:43:59 [error] 21#21: *5 connect() failed (113: No route to host) while connecting to upstream, client: 172.31.0.1, server: captain.xxxx.dev.br, request: "GET /checkhealth HTTP/1.1", upstream: "http://10.0.1.2:3000/checkhealth", host: "captain.xxxx.dev.br"
2023/11/03 17:44:22 [error] 21#21: *9 connect() failed (113: No route to host) while connecting to upstream, client: 172.31.0.1, server: captain.xxxx.dev.br, request: "GET /checkhealth HTTP/1.1", upstream: "http://10.0.1.2:3000/checkhealth", host: "captain.xxxx.dev.br"
```

*Steps to reproduce the problem:*
I don't know how to reproduce this error, because I followed https://caprover.com/docs/get-started.html#step-1-caprover-installation is a clean VPS, the only program that was installed on the VPS was Docker with the Portainer containers and the Nginx Proxy Manager (which I removed before trying to install it on CapRover).

*Output of the following command on your server:*
```
Linux infopoint 5.15.0-1042-kvm #47-Ubuntu SMP Fri Sep 8 11:59:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
               total        used        free      shared  buff/cache   available
Mem:            15Gi       1.6Gi       421Mi       145Mi        13Gi        13Gi
Swap:          2.0Gi        10Mi       2.0Gi
```

**Comment by githubsaturn** [comment]
Very likely your nginx container isn't running. What's the output of 

```
docker service ls

docker service ps captain-nginx --no-trunc

docker service logs captain-nginx
```

**Comment by Saifallak** [comment]
having same problem

```log
root@srv436801:~# docker service ls
ID             NAME              MODE         REPLICAS   IMAGE                              PORTS
zrocpm5q4two   captain-captain   replicated   1/1        caprover/caprover:1.11.1
rzvz22563lzj   captain-certbot   replicated   1/1        caprover/certbot-sleeping:v1.6.0
xzhq75m0fuf7   captain-nginx     replicated   1/1        nginx:1.24
```
```log
root@srv436801:~# docker service ps captain-nginx --no-trunc
ID                          NAME                  IMAGE        NODE        DESIRED STATE   CURRENT STATE             ERROR     PORTS
s6u9s8gx453oj3uhgglovh8ob   captain-nginx.1       nginx:1.24   srv436801   Running         Running 16 minutes ago              *:443->443/tcp,*:443->443/tcp,*:80->80/tcp,*:80->80/tcp
m4vtbb81aosce12tg12grxrca    \_ captain-nginx.1   nginx:1.24   srv436801   Shutdown        Shutdown 16 minutes ago
u0a9dck9nky6ezhje79t26ozo    \_ captain-nginx.1   nginx:1.24   srv436801   Shutdown        Shutdown 17 minutes ago
ws3u25rjwuahf4fitxgc67xp9    \_ captain-nginx.1   nginx:1.24   srv436801   Shutdown        Shutdown 19 minutes ago
kk9czb37dyowb00nqxv4dd941    \_ captain-nginx.1   nginx:1.24   srv436801   Shutdown        Shutdown 21 minutes ago
```
```log
root@srv436801:~# docker service logs captain-nginx
captain-nginx.1.s6u9s8gx453o@srv436801    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
captain-nginx.1.s6u9s8gx453o@srv436801    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
captain-nginx.1.s6u9s8gx453o@srv436801    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
captain-nginx.1.s6u9s8gx453o@srv436801    | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
captain-nginx.1.s6u9s8gx453o@srv436801    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
captain-nginx.1.s6u9s8gx453o@srv436801    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
captain-nginx.1.s6u9s8gx453o@srv436801    | /docker-entrypoint.sh: Configuration complete; ready for start up
```

**Comment by githubsaturn** [comment]
@Saifallak - you probably have a different problem. 

1- what's your VPS provider? 
2- what base image you're using? plain Ubuntu?
3- what do you see when trying to curl into nginx from captain-captain?
```
docker exec -it $(docker ps --filter name=captain-nginx -q) curl -v captain-captain:3000
```

**Comment by Dryrtan** [comment]
> Very likely your nginx container isn't running. What's the output of
> 
> ```
> docker service ls
> 
> docker service ps captain-nginx --no-trunc
> 
> docker service logs captain-nginx
> ```

_**docker service ls**_
```
ID             NAME              MODE         REPLICAS   IMAGE                              PORTS
ty6t4e8kllkv   captain-captain   replicated   1/1        caprover/caprover:1.11.1
ly1znd3kltce   captain-certbot   replicated   1/1        caprover/certbot-sleeping:v1.6.0
0tjtubbxncqe   captain-nginx     replicated   1/1        nginx:1.24
```

_**docker service ps captain-nginx --no-trunc**_
```
ID                          NAME                  IMAGE        NODE        DESIRED STATE   CURRENT STATE                 ERROR     PORTS
jp3nrgiuumemxxhldvd6lgtid   captain-nginx.1       nginx:1.24   infopoint   Running         Running about a minute ago              *:443->443/tcp,*:443->443/tcp,*:80->80/tcp,*:80->80/tcp
yfs7w8g0u44bc4ox2oevwq9ff    \_ captain-nginx.1   nginx:1.24   infopoint   Shutdown        Shutdown about a minute ago
t4l0j0iw5ev202cmsbcvzsyd3    \_ captain-nginx.1   nginx:1.24   infopoint   Shutdown        Shutdown 3 minutes ago
kwz32yr2e8m7uima1ty3l7bnu    \_ captain-nginx.1   nginx:1.24   infopoint   Shutdown        Shutdown 5 minutes ago
xon4u173yo5h3cdmsphmz4qa5    \_ captain-nginx.1   nginx:1.24   infopoint   Shutdown        Shutdown 20 minutes ago
```

_**docker service logs captain-nginx**_
```
captain-nginx.1.2oohx9v4u42s@infopoint    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
captain-nginx.1.2oohx9v4u42s@infopoint    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
captain-nginx.1.2oohx9v4u42s@infopoint    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
captain-nginx.1.2oohx9v4u42s@infopoint    | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
captain-nginx.1.2oohx9v4u42s@infopoint    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
captain-nginx.1.2oohx9v4u42s@infopoint    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
captain-nginx.1.2oohx9v4u42s@infopoint    | /docker-entrypoint.sh: Configuration complete; ready for start up
captain-nginx.1.2oohx9v4u42s@infopoint    | 2023/11/06 12:11:04 [error] 20#20: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.31.0.1, server: captain.infopoint.dev.br, request: "GET /checkhealth HTTP/1.1", upstream: "http://10.0.1.2:3000/checkhealth", host: "captain.infopoint.dev.br"
captain-nginx.1.2oohx9v4u42s@infopoint    | 2023/11/06 12:11:27 [error] 21#21: *5 connect() failed (113: No route to host) while connecting to upstream, client: 172.31.0.1, server: captain.infopoint.dev.br, request: "GET /checkhealth HTTP/1.1", upstream: "http://10.0.1.2:3000/checkhealth", host: "captain.infopoint.dev.br"
captain-nginx.1.2oohx9v4u42s@infopoint    | 2023/11/06 12:11:50 [error] 21#21: *9 connect() failed (113: No route to host) while connecting to upstream, client: 172.31.0.1, server: captain.infopoint.dev.br, request: "GET /checkhealth HTTP/1.1", upstream: "http://10.0.1.2:3000/checkhealth", host: "captain.infopoint.dev.br"
captain-nginx.1.2oohx9v4u42s@infopoint    | 2023/11/06 12:12:13 [error] 21#21: *12 connect() failed (113: No route to host) while connecting to upstream, client: 172.31.0.1, server: captain.infopoint.dev.br, request: "GET /checkhealth HTTP/1.1", upstream: "http://10.0.1.2:3000/checkhealth", host: "captain.infopoint.dev.br"
```

_**docker service logs captain-captain**_
```
captain-captain.1.i49rrb0q0j3i@infopoint    | Captain Starting ...
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.088 pm    Emptying generated and temp folders.
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.096 pm    Ensuring directories are available on host. Started.
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.104 pm    Ensuring directories are available on host. Finished.
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.109 pm    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.116 pm    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.118 pm    Migration not needed, skipping.
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.123 pm    Copying fake certificates...
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.128 pm    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.128 pm    Locking NGINX configuration reloading...
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.134 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.137 pm    Captain Nginx is already running..
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.141 pm    Updating NGINX service...
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:37.149 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:42.151 pm    Pruning containers...
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:42.153 pm    NGINX is fully set up and working...
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:42.157 pm    Captain Certbot is already running..
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:42.160 pm    Updating Certbot service...
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:45.175 pm    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:47.171 pm    Pruning containers...
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:48.181 pm    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:51.187 pm    Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:54.191 pm    Retrying to get containerId for captain-certbot retry count:3
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:10:57.198 pm    Retrying to get containerId for captain-certbot retry count:4
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:11:00.203 pm    Retrying to get containerId for captain-certbot retry count:5
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:11:00.206 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:11:01.027 pm    **** Captain is initialized and ready to serve you! ****
captain-captain.1.i49rrb0q0j3i@infopoint    | GET /api/v2/user/system/loadbalancerinfo 200 10.810 ms - 101
captain-captain.1.i49rrb0q0j3i@infopoint    | GET /api/v2/user/system/netdata 200 10.013 ms - 101
captain-captain.1.i49rrb0q0j3i@infopoint    | POST /api/v2/login 200 18.602 ms - 307
captain-captain.1.i49rrb0q0j3i@infopoint    | POST /api/v2/login 200 2.062 ms - 307
captain-captain.1.i49rrb0q0j3i@infopoint    | GET /api/v2/user/system/netdata 200 6.000 ms - 197
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:11:04.285 pm    Captain health check failed: #0 at captain.infopoint.dev.br
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:11:04.989 pm
captain-captain.1.i49rrb0q0j3i@infopoint    | Error: Wrapped: Error        Error: connect EHOSTUNREACH 10.0.1.6:80
captain-captain.1.i49rrb0q0j3i@infopoint    | Error: Wrapped: Error        Error: connect EHOSTUNREACH 10.0.1.6:80
captain-captain.1.i49rrb0q0j3i@infopoint    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at Logger.e (/usr/src/app/built/utils/Logger.js:27:21)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at Request._callback (/usr/src/app/built/user/system/LoadBalancerManager.js:262:38)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at Request.emit (node:events:514:28)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at ClientRequest.emit (node:events:514:28)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at Socket.socketErrorListener (node:_http_client:501:9)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at Socket.emit (node:events:514:28)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at emitErrorNT (node:internal/streams/destroy:151:8)
captain-captain.1.i49rrb0q0j3i@infopoint    | November 6th 2023, 12:11:04.990 pm
captain-captain.1.i49rrb0q0j3i@infopoint    | Error: Request to nginx Failed.
captain-captain.1.i49rrb0q0j3i@infopoint    | Error: Request to nginx Failed.
captain-captain.1.i49rrb0q0j3i@infopoint    |     at ApiStatusCodes.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at Request._callback (/usr/src/app/built/user/system/LoadBalancerManager.js:263:53)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at Request.emit (node:events:514:28)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at ClientRequest.emit (node:events:514:28)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at Socket.socketErrorListener (node:_http_client:501:9)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at Socket.emit (node:events:514:28)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at emitErrorNT (node:internal/streams/destroy:151:8)
captain-captain.1.i49rrb0q0j3i@infopoint    |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
captain-captain.1.i49rrb0q0j3i@infopoint    | GET /api/v2/user/system/loadbalancerinfo 200 3089.855 ms - 66
```

**Comment by Saifallak** [comment]
> @Saifallak - you probably have a different problem.
> 
> 1- what's your VPS provider? 2- what base image you're using? plain Ubuntu? 3- what do you see when trying to curl into nginx from captain-captain?
> 
> ```
> docker exec -it $(docker ps --filter name=captain-nginx -q) curl -v captain-captain:3000
> ```

I have the same error `Error: connect EHOSTUNREACH 10.0.1.6:80` and `Error: Request to nginx Failed` as @Dryrtan 

my VPS is using KVM virtualization, from [Hostinger.com](https://www.hostg.xyz/SH5WO)

**Comment by Dryrtan** [comment]
My VPS is also on Hostinger as @Saifallak

**Comment by Saifallak** [comment]
For Reference.

This https://github.com/caprover/caprover/issues/1594 using [Hostinger.com](https://www.hostg.xyz/SH5WO) too but with no solution

this https://github.com/caprover/caprover/issues/1831 mentions [Hostinger.com](https://www.hostg.xyz/SH5WO) too with no solution

this https://github.com/caprover/caprover/issues/1796 mentions [Hostinger.com](https://www.hostg.xyz/SH5WO) too with no solution

in https://github.com/caprover/caprover/issues/1900 using [Hostinger.com](https://www.hostg.xyz/SH5WO) too the solution was
> I just installed debian 11 on my vps and worked, Idk if I will get any problems, but works fine.

i haven't tried the solution til now, if you can try and tell us @Dryrtan

**Comment by githubsaturn** [comment]
ah yes! Hostinger and their modified kernel... 

Yes, there's no solutions to suboptimal OS distributions that these providers use by default. You have to use a standard OS. What happens is that these people think they can optimize Linux better than the maintainers!! They end up removing some kernel modules and it breaks the network layer. Please raise the issue with Hostinger.

**Comment by Dryrtan** [comment]
@Saifallak @githubsaturn - The problem really was the modified OS, I formatted and installed the pure Debian 11 OS available in the administration panel and it worked perfectly, I tried using Ubuntu 22.04 before that, but being in the "pure OS" list it didn't work. Thanks for the help :)
