### ISSUE TITLE
caprover container not starting after updating to v1.12.0

### ISSUE THREAD

**Issue by daniel-trevino** [caprover/caprover#2117]
## What is the problem?

After updating to the latest caprover version, my caprover container is not starting properly. These are the logs I can extract from the container before it dies.
I tried to restart my whole server and see if something was glitching and it is still not working.

```
Captain Starting ...
August 20th 2024, 4:56:05.867 pm    Docker API Version on host: 1.41
August 20th 2024, 4:56:07.386 pm
Error: (HTTP code 400) unexpected - client version 1.43 is too new. Maximum supported API version is 1.41
Error: (HTTP code 400) unexpected - client version 1.43 is too new. Maximum supported API version is 1.41
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:343:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:373:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:342:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:310:16)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

-----

**uname -a && lsb_release -a && free -h**

```
Linux musk 5.15.0-118-generic #128-Ubuntu SMP Fri Jul 5 09:28:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
               total        used        free      shared  buff/cache   available
Mem:           125Gi       3.3Gi       115Gi       298Mi       6.6Gi       120Gi
Swap:          4.0Gi          0B       4.0Gi
```

**EDIT: I managed to make it work by rollbacking to the previous release with this command: `docker service update captain-captain --image caprover/caprover:1.11.1`**

**Comment by shahonseven** [comment]
You need to upgrade docker API first before upgrading caprover

**Comment by daniel-trevino** [comment]
> You need to upgrade docker API first before upgrading caprover

Indeed, that was the issue. I also noticed that on the release notes of that version. Thanks!
