### ISSUE TITLE
502 Bad Gateway nginx on fresh install (ssh port not 22)

### ISSUE THREAD

**Issue by johndodev** [caprover/caprover#2132]
Hello,

I have a hard 502 bad gateway from nginx on the url http://captain.xx.yy.com.

- Fresh install of everything on ubuntu 22.04.
- Already done successful and same installations multiple times on amazon servers (lightsail)
- Server here is VM from work, the dude which install just changed ssh port, I don't know if it can be related.

Everything works fine until `caprover serversetup`, step "Enabling SSL" : output is `Error: StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"`

Trying "caprover login", set url to http:// (no https), letting "captain-01" as machine name (not sure about what it's really mean): output is 
```
Something bad happened: cannot save captain-01 at http://captain.xx.yy.com.
502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```

Trying  "caprover login" with https, output is : 
```
Something bad happened: cannot save captain-01 at https://captain.xx.yy.com.
Error: self signed certificate
```

In browser : 

Accessing http://captain.xx.yy.com/ is the hard 502.
Accessing https://captain.xx.yy.com/ is the caprover 502 (Nothing here yet).
Accessing http://[IP]:3000 seems to works (didn't try to create and accessing webapp, shoul'd I ?).

tested with echo `"{"skipVerifyingDomains":"true"}" > ...`, output is `verify: Service captain-captain converged`, problems are the same.

docker service ls seems fine
```
qn4cuu2n6ekp   captain-captain   replicated   1/1        caprover/caprover:1.12.0
ogw7s2ybt90f   captain-certbot   replicated   1/1        caprover/certbot-sleeping:v2.11.0
g0os9b1n69tt   captain-nginx     replicated   1/1        nginx:1.24
```

Output of `docker service logs captain-nginx --since 5m -f` when I'm trying to access http://captain.xx.yy.com

```
captain-nginx.1.08jvbqsxxawo@search    | 2024/09/05 10:27:45 [error] 27#27: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 212.85.141.19, server: captain.xx.yy.com, request: "GET / HTTP/1.1", upstream: "http://10.0.1.2:3000/", host: "captain.xx.yy.com"
captain-nginx.1.08jvbqsxxawo@search    | 212.85.141.19 - - [05/Sep/2024:10:27:45 +0000] "captain.xx.yy.com" "GET / HTTP/1.1" 502 552 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0" "-"
captain-nginx.1.08jvbqsxxawo@search    | 2024/09/05 10:27:45 [error] 27#27: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 212.85.141.19, server: captain.xx.yy.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://10.0.1.2:3000/favicon.ico", host: "captain.xx.yy.com", referrer: "http://captain.xx.yy.com/"
captain-nginx.1.08jvbqsxxawo@search    | 212.85.141.19 - - [05/Sep/2024:10:27:45 +0000] "captain.xx.yy.com" "GET /favicon.ico HTTP/1.1" 502 552 "http://captain.xx.yy.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0" "-"
captain-nginx.1.08jvbqsxxawo@search    | 185.191.126.213 - - [05/Sep/2024:10:28:26 +0000] "91.198.105.49" "GET / HTTP/1.1" 200 2401 "-" "-" "-"
```

I saw issue https://github.com/caprover/caprover/issues/1252 and tried to follow, but it seems a little bit different.

The server dude on my work is not really available and not in same location than me, and not very good actually, especially don't know anything about docker or else (me neither but it's not my job, I'm a webdev). I have the root ssh access tho.

Please help !

**Comment by githubsaturn** [comment]
Get the logs:

```
docker service logs captain-captain
```

**Comment by johndodev** [comment]
I see nothing particular, some stuff like

```
captain-captain.1.hzzvpdo6jf4q@search    | Captain Starting ...
captain-captain.1.hzzvpdo6jf4q@search    | Overriding skipVerifyingDomains from /captain/data/config-override.json
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:10.704 am    Docker API Version on host: 1.47
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.203 am    Emptying generated and temp folders.
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.208 am    Ensuring directories are available on host. Started.
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.213 am    Ensuring directories are available on host. Finished.
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.218 am    Network captain-overlay-network is already attached to service: captain-ca                     ptain
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.223 am    captain-captain (service) has already been connected to secret: captain-sa                     lt
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.224 am    Migration not needed, skipping.
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.229 am    Copying fake certificates...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.236 am    Captain Nginx is already running..
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.239 am    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.239 am    Locking NGINX configuration reloading...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.247 am    executeCommand Container: captain-nginx nginx -t
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.331 am    sendReloadSignal...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.333 am    Kill HUP Container: 798654a30ce0038f1cc1c420f0923749d9e10891d75fe6d2a87d9f                     669ebfe729
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.344 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.344 am    Updating NGINX service...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:12.350 am    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:17.354 am    Pruning containers...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:17.355 am    NGINX is fully set up and working...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:17.358 am    Captain Certbot is already running..
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:17.368 am    Updating Certbot service...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:20.392 am    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:22.385 am    Pruning containers...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:23.395 am    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:26.397 am    Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:29.403 am    Retrying to get containerId for captain-certbot retry count:3
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:32.409 am    Retrying to get containerId for captain-certbot retry count:4
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:35.414 am    Retrying to get containerId for captain-certbot retry count:5
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:35.417 am    executeCommand Container: captain-certbot certbot certificates --non-inter                     active
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:36.032 am    **** Captain is initialized and ready to serve you! ****
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:46.039 am    executeCommand Container: captain-certbot certbot certificates --non-inter                     active
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:46.462 am    executeCommand Container: captain-certbot certbot renew --non-interactive
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:46.877 am    Updating Load Balancer - renewAllCerts
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:46.877 am    Locking NGINX configuration reloading...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:46.885 am    executeCommand Container: captain-nginx nginx -t
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:46.969 am    sendReloadSignal...
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:46.971 am    Kill HUP Container: 2b458bef42a45782f6e96ceb39f2964ae75b35b5bcd3d3fd37ca60                     9c2765e5e1
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:16:46.980 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.hzzvpdo6jf4q@search    | GET / 304 9.114 ms - -
captain-captain.1.hzzvpdo6jf4q@search    | GET /static/js/main.2df2ac77.js 304 2.401 ms - -
captain-captain.1.hzzvpdo6jf4q@search    | GET /static/css/main.d278b36e.css 304 1.355 ms - -
captain-captain.1.hzzvpdo6jf4q@search    | GET /icon-512x512.png 304 0.465 ms - -
captain-captain.1.hzzvpdo6jf4q@search    | September 5th 2024, 10:36:44.554 am
captain-captain.1.hzzvpdo6jf4q@search    | JsonWebTokenError: jwt must be provided
captain-captain.1.hzzvpdo6jf4q@search    | JsonWebTokenError: jwt must be provided
captain-captain.1.hzzvpdo6jf4q@search    |     at module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:53:17)
captain-captain.1.hzzvpdo6jf4q@search    |     at /usr/src/app/built/user/Authenticator.js:86:17
captain-captain.1.hzzvpdo6jf4q@search    |     at new Promise (<anonymous>)
captain-captain.1.hzzvpdo6jf4q@search    |     at Authenticator.decodeAuthToken (/usr/src/app/built/user/Authenticator.js:85:16)
captain-captain.1.hzzvpdo6jf4q@search    |     at /usr/src/app/built/injection/Injector.js:47:14
captain-captain.1.hzzvpdo6jf4q@search    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
captain-captain.1.hzzvpdo6jf4q@search    |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
captain-captain.1.hzzvpdo6jf4q@search    |     at /usr/src/app/node_modules/express/lib/router/index.js:286:9
captain-captain.1.hzzvpdo6jf4q@search    |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
captain-captain.1.hzzvpdo6jf4q@search    |     at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
captain-captain.1.hzzvpdo6jf4q@search    | GET /api/v2/user/system/info 200 6.775 ms - 62
captain-captain.1.hzzvpdo6jf4q@search    | GET /manifest.json 304 0.421 ms - -
captain-captain.1.hzzvpdo6jf4q@search    | GET /icon-512x512.png 304 0.383 ms - -
captain-captain.1.hzzvpdo6jf4q@search    | POST /api/v2/login 200 19.774 ms - 307
captain-captain.1.hzzvpdo6jf4q@search    | GET /icon-512x512.png 304 0.569 ms - -
captain-captain.1.hzzvpdo6jf4q@search    | GET /api/v2/user/system/info 200 1.866 ms - 150
captain-captain.1.hzzvpdo6jf4q@search    | GET /api/v2/user/system/versioninfo 304 508.622 ms - -
```

When I refresh the 502 page nothing new is logged here.

**Comment by johndodev** [comment]
Nevermind, I just learn that server dude use proxmox and LXC images, so not compatible with caprover, sorry.
