### ISSUE TITLE
[Question] how to change domain?

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#2133]
Hi there, 

what is the best way to move the whole caprover instance to a new server with a new IP and domain?

Currently i am wondering how Certificates would be handled.

Thanks a lot!

EDIT: What i tried is to open /captain/data/config-captain.json
and changed all force-ssl and has-ssl to false as well as changed the domain to the new one. i now get this as error logs when i docker logs -f [caproverContainerID]:

```
September 5th 2024, 12:14:05.893 pm    Captain health check failed: #0 at captain.new.domain.com
September 5th 2024, 12:14:05.894 pm    NGINX health check failed: #0
September 5th 2024, 12:14:09.105 pm    Pruning containers...
September 5th 2024, 12:14:17.887 pm    Retrying to get containerId for captain-certbot retry count:0
September 5th 2024, 12:14:20.890 pm    Retrying to get containerId for captain-certbot retry count:1
September 5th 2024, 12:14:20.895 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive 
September 5th 2024, 12:14:21.671 pm    executeCommand Container: captain-certbot certbot renew --non-interactive 
September 5th 2024, 12:14:25.971 pm    Updating Load Balancer - renewAllCerts
September 5th 2024, 12:14:25.971 pm    Locking NGINX configuration reloading...
September 5th 2024, 12:14:25.986 pm    SUCCESS: UNLocking NGINX configuration reloading...
September 5th 2024, 12:14:25.987 pm    sendReloadSignal...
September 5th 2024, 12:14:26.901 pm    Error: Wrapped: Verification Failed for captain.new.domain.com
Error: Wrapped: Verification Failed for captain.new.domain.com
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:54:42)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
September 5th 2024, 12:14:26.901 pm    Error: Wrapped: Error        Error: connect ECONNREFUSED #NEWIP#:80
Error: Wrapped: Error        Error: connect ECONNREFUSED #NEWIP#:80
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:55:42)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
September 5th 2024, 12:14:26.901 pm    Error: Wrapped: body         undefined
Error: Wrapped: body         undefined
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:56:42)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
September 5th 2024, 12:14:26.901 pm    Error: Wrapped: randomUuid   ccad60da-3721-4e81-8c66-1589d7ef5aa4
Error: Wrapped: randomUuid   ccad60da-3721-4e81-8c66-1589d7ef5aa4
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:57:42)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
September 5th 2024, 12:14:26.902 pm    Captain health check failed: #1 at captain.new.domain.com
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
```

**Comment by pcace** [comment]
I think i have solved it: 

0. stop all docker containers
1. change all force-ssl and has-ssl in the config to false. 
2. also change has rootssl to false
3. remove /captain/data/letsencrypt
4. start docker containers
5. open captain by its ip address
6. change root domain
7. enable ssl for all containers manually again

seems to work for now ;)

**Comment by githubsaturn** [comment]
For future reference, this is not a stable way to do this. The proper way to do this is to create a backup and restore.
