### ISSUE TITLE
Install caprover when 80/443 are already taken? 

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#2180]
Hi there, i have a server wich runs some services, mainly web and mailservers. so 443 and 80 8080 are already taken. 
is it possible to install caprover anyways? 
what i tried is to this: 

```bash
root@mail:/opt/scripts/geodata_db_updater# docker run -p 8082:80 -p 4431:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
Captain Starting ...
Installing Captain Service ...
     
 Installation of CapRover is starting...     
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html
     
     
October 30th 2024, 12:01:21.382 pm    Docker API Version on host: 1.47
 
 
 
 >>> Checking System Compatibility <<<
   Docker Version passed.
******* Warning *******    CapRover and Docker work best on Ubuntu - specially when it comes to storage drivers.
   Total RAM 25199 MB
 
 
Are you trying to run CapRover on a local machine or a machine without a public IP?
In that case, you need to add this to your installation command:
    -e MAIN_NODE_IP_ADDRESS='127.0.0.1'   
 
 
 
Otherwise, if you are running CapRover on a VPS with public IP:
Your firewall may have been blocking an in-use port: 80
A simple solution on Ubuntu systems is to run "ufw disable" (security risk)
Or [recommended] just allowing necessary ports:
ufw allow 80,443,3000,996,7946,4789,2377/tcp; ufw allow 7946,4789,2377/udp; 
     
     
See docs for more details on how to fix firewall issues
 
Finally, if you are an advanced user, and you want to bypass this check (NOT RECOMMENDED),
you can append the docker command with an addition flag: -e BY_PASS_PROXY_CHECK='TRUE'
 
 
Installation failed.
Error: Port seems to be closed: 80
    at Request._callback (/usr/src/app/built/utils/CaptainInstaller.js:145:24)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (node:events:517:28)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

but i get this seems to be closed error. even if i wnat it to listen to 8082. 
Is there any environment var i am missing? or is there just no chance for this to work? 

Cheers and thanks!

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover/issues/1166#issuecomment-2430704491

This new functionality is just added, so you have to use the edge image as expected in the linked comment.
