### ISSUE TITLE
Safari Only: Cannot deploy one-click-apps

### ISSUE THREAD

**Issue by juicejs** [caprover/caprover#385]
What is the problem?
After updating to CapRover One-Click-Apps can't be created.

Steps to reproduce the problem:
running update script from https://caprover.com/docs/cdd-migration.html

Whatever kind of app I use, this problem always occurs:
<img width="541" alt="Screen Shot 2019-03-14 at 22 35 26" src="https://user-images.githubusercontent.com/48195761/54346544-245d7500-46aa-11e9-9034-d1efee6bdba0.png">

There's definitely enough RAM and disk space available.

**Comment by githubsaturn** [comment]
This is not a bug, it simply means that your network connection to the server is unsteady. During deployment, your connection needs to stay alive for 60secs. If you have a unstable connection this fails. 


Please retry again with a stable connection and let me know if the problem persists.

**Comment by juicejs** [comment]
I‘m pretty sure my network connection is very stable. We never had any network errors with deployments. Normal apps that are deployed via caprover-cli are working fine. It’s just the one-click-apps.

A one-clock-app is entirely setup on the server. Nothing needs to be transferred between my computer and the server. How can it be that a network error occurs?

**Comment by githubsaturn** [comment]
One-click apps use long polling, meaning that it keeps the connection open for the 30 seconds or more. So it's more sensitive to unstable connections. 

You can open developer options in Google Chrome and monitor the Network to see if indeed the connection drops.


Another possibility is that the server crashes during the deployment of the one-click app, but you mentioned there is enough RAM/CPU on your machine. To make sure that this server crash is not happening at all, try this:
- Deploy your one-click app
- **As soon as** you see the error saying that there was a Network Error, click on Settings, or Cluster or any other page. 
- If your server had crashed during the build, you will see an error saying that "Captain is not ready...."
- If everything works, and you don't see the Captain Not Ready error, then it means that there was no crash during the build.


If you are sure that your network connection is solid, and you have confirmed that the server is not crashing during the deployment, please run `docker service logs captain-captain --since 5m` to get the logs of CapRover during the deployment and copy and paste logs here for further debugging.

**Comment by githubsaturn** [comment]
@juicejs 
Any update on this? Let me know if you're still experiencing the issue.

**Comment by juicejs** [comment]
Hi there, 

I tried it with Chrome and then it was working fine. Probably a safari bug?

**Comment by mromanuk** [comment]
Hi, I happened to have the same issue, I couldn't even delete the apps correctly, because they got stuck with the following error:

```
captain-captain.1.w7bzjvkfw5r0@mercury    | March 18th 2019, 1:00:57.358 pm    Error: (HTTP code 404) no such service - service srv-captain--postgres-db not found
captain-captain.1.w7bzjvkfw5r0@mercury    | Error: (HTTP code 404) no such service - service srv-captain--postgres-db not found
captain-captain.1.w7bzjvkfw5r0@mercury    |     at /usr/src/app/node_modules/docker-modem/lib/modem.js:257:17
captain-captain.1.w7bzjvkfw5r0@mercury    |     at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:287:7)
captain-captain.1.w7bzjvkfw5r0@mercury    |     at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:256:5)
captain-captain.1.w7bzjvkfw5r0@mercury    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:232:14)
captain-captain.1.w7bzjvkfw5r0@mercury    |     at IncomingMessage.emit (events.js:194:15)
captain-captain.1.w7bzjvkfw5r0@mercury    |     at endReadableNT (_stream_readable.js:1103:12)
captain-captain.1.w7bzjvkfw5r0@mercury    |     at process._tickCallback (internal/process/next_tick.js:63:19)
captain-captain.1.w7bzjvkfw5r0@mercury    | GET /api/v2/user/apps/appData/postgres-db/logs?encoding=hex 500 5.188 ms - 21
```

As a workaround I've restarted captain and after that it deployed successfully:

```
docker service update captain-captain --force
```

**Comment by githubsaturn** [comment]
Thanks for reporting this. Is the issue only applicable to one-click apps?

**Comment by mromanuk** [comment]
@githubsaturn yes, I can create and deploy apps without issues

**Comment by githubsaturn** [comment]
Unfortunately, I can't replicate the issue as I don't own a Mac. I have to wait for a contributor to pick this up.

However, as the first step, we should just add a compatibility warning of some sort for safari.

**Comment by mromanuk** [comment]
The plot thickens, I've installed caprover dev on my mac and the one-click app was deployed successfully using Safari! Which was unexpected

**Comment by githubsaturn** [comment]
What a bummer... Maybe Safari treats localhost connections differently (?) So maybe try running the backend on a remove server and run the frontend on your local machine.

This might work:
- Install CapRover on a test server, use https://caprover.com/docs/play-with-docker.html
- After installation is done, run `docker update captain-captain --env-add CAPTAIN_IS_DEBUG='true'`
- Then on your frontend code, edit `ApiManager.ts` and change `BASE_DOMAIN` to the play-with-docker URL (taken from step 1)

**Comment by tuefekci** [comment]
I have a mac available so i tested it.

It is an Network Error in the Wordpress OneClick for example the request to https://captain.domain.com/api/v2/user/apps/appData/test-wordpress failed and the response is empty.
![image](https://user-images.githubusercontent.com/2657626/55575089-580e4680-570e-11e9-8a2e-ffc183916203.png)

im not used to the safari dev tools so its kinda hard for me to decipher whats going on but could it be just a timing issue that the request for the container gets send immidiatly after the update request which is just not done yet or is it something with how caching is handled in safari?

Its also weird because if i click on go back and try again and let it run again it works also the containers get created anyway and work even if the reponse while creating shows an error. 

I could only reproduce the error once all subsequent tests worked out fine so its a weird one.

Im on Safari 12.0.2 (14606.3.4) it would be helpful to know the version people with problems use to reproduce.

**Comment by r-chris** [comment]
I deployed a handful of One-Click-Apps via Safari Version 13.1 recently and did not see this issue occurring.

**Comment by r-chris** [comment]
Was this fixed in #385 ?

**Comment by r-chris** [comment]
I meant: Was this fixed in: #481?

**Comment by githubsaturn** [comment]
That's a slightly different issue. The issue here happens when the long poll connection takes too long. This happens when your server has a slow connection that results in a longer than usual time for building images.

**Comment by edcous** [comment]
Is this issue still a thing with the new version of safari?

**Comment by githubsaturn** [comment]
I haven't seen this issue in a long time. Hence, I'll close this issue. Feel free to reopen if it's still a thing.

**Comment by bibstha** [comment]
Just a note: the bug still exists but works in chrome.

**Comment by eikaramba** [comment]
FYI: I had the same problem on FF, used chromium and it works
_Environemnt: ubuntu 22.04 on hyper-v VM on windows 10 (good for testing caprover out)_

**Comment by sixhobbits** [comment]
I got this on Safari too but works fine for Firefox -- would be nice to add a Safari warning at least if it can't be fixed as it took me a while to find this

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover-frontend/blob/c28107f530ef23a87aee503cc2ac815a822edeee/src/containers/apps/oneclick/selector/OneClickAppSelector.tsx#L199-L205

There is supposed to be a warning on Safari, but I guess it's not working?

**Comment by uhlhosting** [comment]
I can replicate this too on Safari.

**Comment by mapxn** [comment]
Have the same issue.

**Comment by ZainRizvi** [comment]
Safari on mobile reproduces this for me as well

**Comment by Emilien-Lambert** [comment]
Aaah it took me so long to figure out that I had exactly this problem. It's a real shame that the message :

"You seem to be using Safari. Deployment of one-click apps may be unstable on Safari. Using Chrome is recommended"

it's at the very bottom of the application list, almost impossible to see 😅

**Comment by githubsaturn** [comment]
@Emilien-Lambert - thanks for noting this! I moved the warning to the top for the next release! Very good catch!

**Comment by boutterudy** [comment]
Hi everyone 👋 

I've also encountered the same problem, but on Chrome: 
<img src="https://github.com/user-attachments/assets/4f3c2425-c395-4696-af50-55b3875ba4c8" height="500px" />

I'm using version `125.0.6422.113 (Official Build) (arm64)` of Chrome.

I had a really hard time trying to get it to work, I thought it was my VPS that was having problems, but after checking everywhere, everything was fine in terms of configuration and network (both my VPS and my computer).

After stumbling across this issue, I thought it might be a good idea to try it out on another browser, so I gave it a go with Firefox (version `127.0.2 (64 bits)`), and strangely enough, it worked without any error messages on the first try 🤔 

I have a hypothesis as to why it might not work on certain browsers: 
- The browser I use every day is Chrome
- I have a lot of tabs open all the time on my usual browser _(yes I know it's bad to do that 🫠)_
- I never use Firefox, so I don't have any tabs open on that browser when I use it
- I assume that every browser keeps open connections in recently visited tabs (or something like that)
- I therefore assume that the network allocated to the CapRover server tab is not sufficient

I don't particularly have any advanced knowledge of web browsers, but it seems to me to be a plausible cause for this error - people naturally use the browser they're used to using, but by extension it's also the one where there's most likely to be lots of tabs open at the same time, where when they change browser, it's often for the one they only use occasionally 🤔 

What do you think?

**Comment by githubsaturn** [comment]
@boutterudy - the problem you're experiencing seems to be a bit different from what this thread is about. This particular open issue is about the timeout issue on Safari which happens on the "depoloyment" step. Whereas in your screenshot, you're showing that it fails on app registration which is almost instant. So it's not a timeout issue. Can you try opening the network tab on your browser and click on the failed request and take the screenshot?
