### ISSUE TITLE
Can't install on Ubuntu server 18.04 with official guide

### ISSUE THREAD

**Issue by mnlbox** [caprover/caprover#450]
Hi guys,
I try to install Caprover n my Ubuntu server 18.04 based on bellow command:
```
docker run -e DEFAULT_PASSWORD='my password'  -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

But it's not working when I try to access it through `http://<my server IP>:3000
When I try to access CapRover logs with bellow command I see some error in logs:
```
docker service logs captain-captain --follow

| 
| > caprover@0.0.0 start /usr/src/app
| > node ./bin/www
| 
| Captain Starting ...
| June 24th 2019, 10:08:34.087 am    Emptying generated and temp folders.
| June 24th 2019, 10:08:34.102 am    Ensuring directories are available on host. Started.
| June 24th 2019, 10:08:34.114 am    Ensuring directories are available on host. Finished.
| June 24th 2019, 10:08:34.124 am    Network captain-overlay-network is already attached to service: captain-captain
| June 24th 2019, 10:08:34.136 am    captain-captain (service) has already been connected to secret: captain-salt
| June 24th 2019, 10:08:34.155 am    Setting up NGINX conf file...
| June 24th 2019, 10:08:34.158 am    Locking NGINX configuration reloading...
| June 24th 2019, 10:08:34.167 am    SUCCESS: UNLocking NGINX configuration reloading...
| June 24th 2019, 10:08:34.173 am    Captain Nginx is already running.. 
| June 24th 2019, 10:08:37.181 am    Retrying to get NodeID for captain-nginx retry count:0
| June 24th 2019, 10:08:40.190 am    Retrying to get NodeID for captain-nginx retry count:1
| June 24th 2019, 10:08:43.196 am    Retrying to get NodeID for captain-nginx retry count:2
| June 24th 2019, 10:08:46.203 am    Retrying to get NodeID for captain-nginx retry count:3
| June 24th 2019, 10:08:49.210 am    Retrying to get NodeID for captain-nginx retry count:4
| June 24th 2019, 10:08:52.221 am    Retrying to get NodeID for captain-nginx retry count:5
| June 24th 2019, 10:08:55.230 am    Retrying to get NodeID for captain-nginx retry count:6
| June 24th 2019, 10:08:58.237 am    Retrying to get NodeID for captain-nginx retry count:7
| June 24th 2019, 10:09:01.247 am    Retrying to get NodeID for captain-nginx retry count:8
| June 24th 2019, 10:09:04.256 am    Retrying to get NodeID for captain-nginx retry count:9
| June 24th 2019, 10:09:04.264 am    Error: There must be only one instance (not 0) of the service running to find node id. captain-nginx
| Error: There must be only one instance (not 0) of the service running to find node id. captain-nginx
|     at /usr/src/app/built/docker/DockerApi.js:82:23
|     at process._tickCallback (internal/process/next_tick.js:68:7)
| 
| > caprover@0.0.0 start /usr/src/app
| > node ./bin/www
| 
| Captain Starting ...
...
```
This is also `docker version` output:
```
docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Can you help me to fix this?

**/CC:** @githubsaturn

**Comment by githubsaturn** [comment]
Please run this and copy the output here
```
docker service ps captain-nginx --no-trunc
```

**Comment by mnlbox** [comment]
This is output:
```
k6av1sinzuuwfeok7sgxvvusl   captain-nginx.1       nginx:1             ubuntu              Ready               Preparing 2 seconds ago                              
vavap8js2ye45jfdvczr1vctb    \_ captain-nginx.1   nginx:1             ubuntu              Shutdown            Rejected 6 seconds ago    "No such image: nginx:1"   
2rb6klfjsjgiew1pjt4kfbs4z    \_ captain-nginx.1   nginx:1             ubuntu              Shutdown            Rejected 11 seconds ago   "No such image: nginx:1"   
tf5ypmi0xt2nwrbrt8n4xe6zz    \_ captain-nginx.1   nginx:1             ubuntu              Shutdown            Rejected 15 seconds ago   "No such image: nginx:1"   
fbgs8id21vxn4uk7x6xb5hh8w    \_ captain-nginx.1   nginx:1             ubuntu              Shutdown            Rejected 21 seconds ago   "No such image: nginx:1"   

```

**Comment by githubsaturn** [comment]
Your Docker installation has problems. You should uninstall and reinstall it. 

As a workaround you can run:
docker pull nginx:1

**Comment by mnlbox** [comment]
@githubsaturn I installed my docker like this:
```
curl -fsSL get.docker.com -o get-docker.sh
sh get-docker.sh
```
Is it OK or I need other stuff?

**Comment by mnlbox** [comment]
@githubsaturn I try to install my docker again based on this tutorial:
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04
My error change a little. Now when I run below command I got an error about firewall I also try to disable ufw and add some rule but still error exist.
```
docker run -e DEFAULT_PASSWORD='bizi@baz'  -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```
```
Installation failed.
Error: Port seems to be closed: 80
    at Request._callback (/usr/src/app/built/utils/CaptainInstaller.js:148:24)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

This is my first try ufw status:
```
root@ubuntu:~# sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW IN    Anywhere                  
80,443,996,2377,3000,4789,7946/tcp ALLOW IN    Anywhere                  
2377,4789,7946/udp         ALLOW IN    Anywhere                  
22/tcp (v6)                ALLOW IN    Anywhere (v6)             
80,443,996,2377,3000,4789,7946/tcp (v6) ALLOW IN    Anywhere (v6)             
2377,4789,7946/udp (v6)    ALLOW IN    Anywhere (v6)
```

Next I try to disable ufw with (`ufw disable`) and reboot my system and run docker again this time docker run done but still I don't see anything in `http://<server ip>:3000`. This is my ufw status:
```
root@ubuntu:~# ufw disable
Firewall stopped and disabled on system startup
root@ubuntu:~# reboot

root@ubuntu:~# sudo ufw status verbose
Status: inactive

```

**Comment by mnlbox** [comment]
@githubsaturn Can you help me to fix this?

**Comment by mnlbox** [comment]
I also try to remove all with below command and install again but it's still not working:
```
docker service rm $(docker service ls -q)
docker swarm leave --force
docker system prune -a
rm -rf /captain
docker run -e DEFAULT_PASSWORD='my passowrd'  -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover

docker service ps captain-nginx --no-trunc
ID                          NAME                  IMAGE               NODE                DESIRED STATE       CURRENT STATE                 ERROR               PORTS
xm9cb6sfbpy1fqgszptpcihy9   captain-nginx.1       nginx:1             ubuntu              Running             Preparing 9 seconds ago                           
pak7x2kcd3gqxkt1kt6truru8    \_ captain-nginx.1   nginx:1             ubuntu              Shutdown            Shutdown 9 seconds ago                            
i3ut8hza7k2ya16tpb9d164n3    \_ captain-nginx.1   nginx:1             ubuntu              Shutdown            Shutdown about a minute ago                       
iqhpkg12r1x9amd0irtszngqn    \_ captain-nginx.1   nginx:1             ubuntu              Shutdown            Shutdown about a minute ago                       
miw8ts481h6xmhg3w1nekn0k5    \_ captain-nginx.1   nginx:1             ubuntu              Shutdown            Shutdown 2 minutes ago
```

**Comment by githubsaturn** [comment]
So just to be clear the error that you're now getting is the one that says the port is closed, right?

In that case, is your server a local server behind a private network or a server with public ip address?

Who is your server peovider? AWS? Digital ocean?

**Comment by mnlbox** [comment]
@githubsaturn Thanks for your attention,
No now it's not port issue, I have a VPS from RamNode with public IP Address,
I completely remove docker and reinstall that again then reinstall CapRover this time login page show but when I enter password and click login button I see this error message in my browser:
 ```
1001 : Captain is not ready yet...
```
I also see this error in Firefox console:
```
Error: "Captain is not ready yet..."
    value ErrorFactory.ts:23
    value HttpClient.ts:79
```

I also see some log in my server with bellow command:
```
root@ubuntu:~# docker service logs captain-captain --follow
captain-captain.1.jlebajp8exug@ubuntu    | 
captain-captain.1.jlebajp8exug@ubuntu    | > caprover@0.0.0 start /usr/src/app
captain-captain.1.jlebajp8exug@ubuntu    | > node ./bin/www
captain-captain.1.jlebajp8exug@ubuntu    | 
captain-captain.1.jlebajp8exug@ubuntu    | Captain Starting ...
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:15.340 am    Emptying generated and temp folders.
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:15.358 am    Ensuring directories are available on host. Started.
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:15.370 am    Ensuring directories are available on host. Finished.
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:15.379 am    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:15.392 am    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:15.406 am    Setting up NGINX conf file...
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:15.409 am    Locking NGINX configuration reloading...
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:15.418 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:15.424 am    Captain Nginx is already running.. 
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:15.430 am    Updating NGINX service...
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:15.464 am    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:20.469 am    NGINX is fully set up and working...
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:20.472 am    Migration not needed, skipping.
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:20.486 am    Captain Certbot is already running.. 
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:20.491 am    Updating Certbot service...
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:23.521 am    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:26.529 am    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:29.539 am    Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:32.547 am    Retrying to get containerId for captain-certbot retry count:3
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:35.560 am    Retrying to get containerId for captain-certbot retry count:4
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:38.569 am    Retrying to get containerId for captain-certbot retry count:5
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:41.579 am    Retrying to get containerId for captain-certbot retry count:6
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:44.592 am    Retrying to get containerId for captain-certbot retry count:7
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:47.599 am    Retrying to get containerId for captain-certbot retry count:8
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:50.611 am    Retrying to get containerId for captain-certbot retry count:9
captain-captain.1.jlebajp8exug@ubuntu    | June 26th 2019, 11:11:50.617 am    Error: No containerId is found
captain-captain.1.jlebajp8exug@ubuntu    | Error: No containerId is found
captain-captain.1.jlebajp8exug@ubuntu    |     at /usr/src/app/built/docker/DockerApi.js:668:19
captain-captain.1.jlebajp8exug@ubuntu    |     at process._tickCallback (internal/process/next_tick.js:68:7)
captain-captain.1.qqw24lmdtsgm@ubuntu    | 
captain-captain.1.qqw24lmdtsgm@ubuntu    | > caprover@0.0.0 start /usr/src/app
captain-captain.1.qqw24lmdtsgm@ubuntu    | > node ./bin/www
captain-captain.1.qqw24lmdtsgm@ubuntu    | 
```

**Comment by mnlbox** [comment]
@githubsaturn Is CapRover is ready for production usage? :thinking:

**Comment by mnlbox** [comment]
@githubsaturn any idea ? :thinking:

**Comment by githubsaturn** [comment]
Your install script seems legit. My guess is that your Docker installation has problems. Specifically it cannot pull the correct images and that's why it cannot start up some of the containers.

Can you try installing CapRover on a tested and trusted VPS, like digital ocean?

**Comment by mnlbox** [comment]
@githubsaturn can you guide me how we can uninstall docker completly and install again?? (I try some approach but that error still exist)
Unfortunately I can't pay for digital ocean in my country.

**Comment by cyclops24** [comment]
@githubsaturn I have same issue in my Iran server. If you want I can provide a test server for you to see this issue in action. Just tell me you email address.

**Comment by githubsaturn** [comment]
More reports of this issue are coming out. But I can't reproduce this on my end. Just to be clear, CapRover constantly fails because CertBot image refuses to wake up.
```
################### THIS LINE KEEPS REPEATING
Retrying to get containerId for captain-certbot retry count
```

To help me debug this, can you please run this command and copy the output here:
```
docker service ps captain-certbot --no-trunc
```

**Comment by githubsaturn** [comment]
Also, you may try running the following commands:
 ```
docker pull caprover/certbot-sleeping
docker pull caprover/certbot-sleeping:v0.29.1
docker pull nginx
docker pull nginx:1 
```

Hopefully this will resolve the issue.

**Comment by mnlbox** [comment]
@githubsaturn This is my `docker service ps captain-certbot --no-trunc` output:
```
ID                          NAME                    IMAGE                               NODE                DESIRED STATE       CURRENT STATE          ERROR                                                              PORTS
u1qnqnqx71845q6yoonycyrue   captain-certbot.1       caprover/certbot-sleeping:v0.29.1   ubuntu              Running             Running 12 days ago                                                                       
8ounuwj332mv1pd43lkq5mb8i    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   ubuntu              Shutdown            Failed 12 days ago     "No such container: captain-certbot.1.8ounuwj332mv1pd43lkq5mb8i"   
9krsx5zbkop791snq60lioysg    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   ubuntu              Shutdown            Shutdown 12 days ago                                                                      
rxq9te2x67181bdkc3b5va5xj    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   ubuntu              Shutdown            Failed 12 days ago     "No such container: captain-certbot.1.rxq9te2x67181bdkc3b5va5xj"   
lmd1seim608j4taq60qvlkpyy    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   ubuntu              Shutdown            Shutdown 12 days ago
```

**Comment by mnlbox** [comment]
@githubsaturn My CapRover installed successfully after run these commands:
```
docker pull caprover/certbot-sleeping
docker pull caprover/certbot-sleeping:v0.29.1
docker pull nginx
docker pull nginx:1 
```
I think maybe it's better to add this to install page or here: https://caprover.com/docs/get-started.html
Thanks for your help :wink:

**Comment by githubsaturn** [comment]
Sounds great!! These commands should not be necessary in normal installation of CapRover. As Docker is supposed to automatically pick them up. However, for your installation, Docker somehow fails to pull automatically.

I'll do some refactoring in the installation script so that these are forcefully pulled.

**Comment by mnlbox** [comment]
@githubsaturn Thanks bro,
So please keep this issue open until refactoring.

**Comment by githubsaturn** [comment]
Done. This feature will be available in the next release. For now, it's available on edge image:
https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version
