### ISSUE TITLE
[Deployment Issue] 1107 : Verification Failed

### ISSUE THREAD

**Issue by DBWebdiensten** [caprover/caprover#502]
**What is the problem?**
I want to attach another (sub)domain to one of the apps I've created, but am unable to and get "**1107 : Verification Failed**" and have taken a look at https://caprover.com/docs/troubleshooting.html#cannot-verify-domain

**Steps to reproduce the problem:**
I've firstly ( *and already a while back* ) attached sendy.rootsafe.nl as a CNAME to sendy.caprover.rootsafe.nl which works as intended.
I now want to CNAME nieuwsbrief.glasvezelzuidenveld.nl to sendy.rootsafe.nl as described by Sendy and Caprover.

The DNS is propogated succesfully looking at:

1. https://www.whatsmydns.net/#CNAME/nieuwsbrief.glasvezelzuidenveld.nl
2. https://dns.google.com/query?name=nieuwsbrief.glasvezelzuidenveld.nl

For both rootsafe.nl and glasvezelzuidenveld.nl we use CloudFlare, which have been set to 'DNS Only' instead of 'Proxying'.

https://sendy.rootsafe.nl works as intended.
http://nieuwsbrief.glasvezelzuidenveld.nl seems to reach the server, but isn't rewriten to the right app it seems and therefor I'm unable to request SSL for nieuwsbrief.glasvezelzuidenveld.nl and use it for the newsletter actions as a custom domain in Sendy. 

Answers to the following questions if applicable:
- Your OS and version? = Ubuntu 18.04.3 LTS
- RAM? = 4Gb

`docker service logs captain-captain -f` and actively trying to get HTTPS for the subdomain shows:

```
captain-captain.1.4wqjb37dqmo4@caprover    | September 10th 2019, 8:18:42.374 pm    Verifying Captain owns domain: nieuwsbrief.glasvezelzuidenveld.nl
captain-captain.1.4wqjb37dqmo4@caprover    | September 10th 2019, 8:18:43.424 pm    Error: Wrapped: Verification Failed for nieuwsbrief.glasvezelzuidenveld.nl
captain-captain.1.4wqjb37dqmo4@caprover    | Error: Wrapped: Verification Failed for nieuwsbrief.glasvezelzuidenveld.nl
captain-captain.1.4wqjb37dqmo4@caprover    |     at errorize (/usr/src/app/built/utils/Logger.js:9:16)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Function.e (/usr/src/app/built/utils/Logger.js:31:19)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:61:32)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.emit (events.js:198:13)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.emit (events.js:198:13)
captain-captain.1.4wqjb37dqmo4@caprover    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Object.onceWrapper (events.js:286:20)
captain-captain.1.4wqjb37dqmo4@caprover    |     at IncomingMessage.emit (events.js:203:15)
captain-captain.1.4wqjb37dqmo4@caprover    | September 10th 2019, 8:18:43.425 pm    Error: Wrapped: Error        null
captain-captain.1.4wqjb37dqmo4@caprover    | Error: Wrapped: Error        null
captain-captain.1.4wqjb37dqmo4@caprover    |     at errorize (/usr/src/app/built/utils/Logger.js:9:16)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Function.e (/usr/src/app/built/utils/Logger.js:31:19)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:62:32)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.emit (events.js:198:13)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.emit (events.js:198:13)
captain-captain.1.4wqjb37dqmo4@caprover    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Object.onceWrapper (events.js:286:20)
captain-captain.1.4wqjb37dqmo4@caprover    |     at IncomingMessage.emit (events.js:203:15)
captain-captain.1.4wqjb37dqmo4@caprover    | September 10th 2019, 8:18:43.425 pm    Error: Wrapped: body         64d00656-4234-481a-bd33-aa2d9029d3e9
captain-captain.1.4wqjb37dqmo4@caprover    | Error: Wrapped: body         64d00656-4234-481a-bd33-aa2d9029d3e9
captain-captain.1.4wqjb37dqmo4@caprover    |     at errorize (/usr/src/app/built/utils/Logger.js:9:16)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Function.e (/usr/src/app/built/utils/Logger.js:31:19)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:63:32)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.emit (events.js:198:13)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.emit (events.js:198:13)
captain-captain.1.4wqjb37dqmo4@caprover    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Object.onceWrapper (events.js:286:20)
captain-captain.1.4wqjb37dqmo4@caprover    |     at IncomingMessage.emit (events.js:203:15)
captain-captain.1.4wqjb37dqmo4@caprover    | September 10th 2019, 8:18:43.426 pm    Error: Wrapped: randomUuid   0c2ad6f8-fc08-4599-9e1e-1610b2e38435
captain-captain.1.4wqjb37dqmo4@caprover    | Error: Wrapped: randomUuid   0c2ad6f8-fc08-4599-9e1e-1610b2e38435
captain-captain.1.4wqjb37dqmo4@caprover    |     at errorize (/usr/src/app/built/utils/Logger.js:9:16)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Function.e (/usr/src/app/built/utils/Logger.js:31:19)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:64:32)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.emit (events.js:198:13)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.emit (events.js:198:13)
captain-captain.1.4wqjb37dqmo4@caprover    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Object.onceWrapper (events.js:286:20)
captain-captain.1.4wqjb37dqmo4@caprover    |     at IncomingMessage.emit (events.js:203:15)
captain-captain.1.4wqjb37dqmo4@caprover    | September 10th 2019, 8:18:43.427 pm    Error: Verification Failed.
captain-captain.1.4wqjb37dqmo4@caprover    | Error: Verification Failed.
captain-captain.1.4wqjb37dqmo4@caprover    |     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:65:47)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.emit (events.js:198:13)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Request.emit (events.js:198:13)
captain-captain.1.4wqjb37dqmo4@caprover    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
captain-captain.1.4wqjb37dqmo4@caprover    |     at Object.onceWrapper (events.js:286:20)
captain-captain.1.4wqjb37dqmo4@caprover    |     at IncomingMessage.emit (events.js:203:15)
captain-captain.1.4wqjb37dqmo4@caprover    |     at endReadableNT (_stream_readable.js:1129:12)
captain-captain.1.4wqjb37dqmo4@caprover    | POST /api/v2/user/apps/appDefinitions/enablecustomdomainssl 200 1054.203 ms - 62
```

**Comment by solomon23** [comment]
Can you try doing a `curl http://nieuwsbrief.glasvezelzuidenveld.nl/.well-known/captain-identifier` the expected result is that it return the guid above `64d00656-4234-481a-bd33-aa2d9029d3e9`

Try it from the host running CapRover

**Comment by DBWebdiensten** [comment]
@solomon23 thanks for you're answer, locally from the CapRover host I get:

```
curl http://nieuwsbrief.glasvezelzuidenveld.nl/.well-known/captain-identifier
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.17.3</center>
</body>
</html>
```

From my desktop I get:
```
curl http://nieuwsbrief.glasvezelzuidenveld.nl/.well-known/captain-identifier
64d00656-4234-481a-bd33-aa2d9029d3e9
```

Is this some kind of routing issue?

**Comment by iFloris** [comment]
@DBWebdiensten also see https://github.com/caprover/caprover-cli/issues/34, perhaps you can test the same thing?

**Comment by solomon23** [comment]
From my desktop i now get the nginx error from your box now too where i used to get the  guid.  The other thing you can do is a `curl http://nieuwsbrief.glasvezelzuidenveld.nl/.well-known/captain-identifier -v` which will give you the ip address of the server that's responding.

**Comment by DBWebdiensten** [comment]
@solomon23 excuse me for my late reply, I've just ran the command and get the same result as before:

```
root@caprover:~# curl  -H 'Cache-Control: no-cache' http://nieuwsbrief.glasvezelzuidenveld.nl/.well-known/captain-identifier -v
*   Trying 94.130.176.215...
* TCP_NODELAY set
* Connected to nieuwsbrief.glasvezelzuidenveld.nl (94.130.176.215) port 80 (#0)
> GET /.well-known/captain-identifier HTTP/1.1
> Host: nieuwsbrief.glasvezelzuidenveld.nl
> User-Agent: curl/7.58.0
> Accept: */*
> Cache-Control: no-cache
>
< HTTP/1.1 404 Not Found
< Server: nginx/1.17.3
< Date: Sat, 14 Sep 2019 07:08:37 GMT
< Content-Type: text/html
< Content-Length: 153
< Connection: keep-alive
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.17.3</center>
</body>
</html>
* Connection #0 to host nieuwsbrief.glasvezelzuidenveld.nl left intact
```

**Comment by solomon23** [comment]
From some research is seems like what is happening is that the nginx container isn't getting the mounts it needs.  You can verify this with `docker container list` and finding the id of your nginx container and then `docker inspect <nginx id>`.  Then look for `Mounts: []`.  If it's an empty array, then you've found the problem.

One repro was if you had the snap or older version of docker installed at one point, removed it, and then installed the newer docker you would see the issue.  If that's the case, rebooting the box *might* fix you up.  You'll also want to make sure you have the latest docker from apt-get.

**Comment by DBWebdiensten** [comment]
@solomon23 there are two 'Mounts' array's and both are filled with seemingly the right data:
```
root@caprover:~# docker inspect c7ba163512e8
[
    {
        "Id": "c7ba163512e819e8afadcf135ed489ca1199db1997437b88b956c0023d649cd2",
        "Created": "2019-09-11T09:42:51.807949703Z",
        "Path": "nginx",
        "Args": [
            "-g",
            "daemon off;"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 11163,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-09-11T09:42:55.716525221Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:5a3221f0137beb960c34b9cf4455424b6210160fd618c5e79401a07d6e5a2ced",
        "ResolvConfPath": "/var/lib/docker/containers/c7ba163512e819e8afadcf135ed489ca1199db1997437b88b956c0023d649cd2/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/c7ba163512e819e8afadcf135ed489ca1199db1997437b88b956c0023d649cd2/hostname",
        "HostsPath": "/var/lib/docker/containers/c7ba163512e819e8afadcf135ed489ca1199db1997437b88b956c0023d649cd2/hosts",
        "LogPath": "/var/lib/docker/containers/c7ba163512e819e8afadcf135ed489ca1199db1997437b88b956c0023d649cd2/c7ba163512e819e8afadcf135ed489ca1199db1997437b88b956c0023d649cd2-json.log",
        "Name": "/captain-nginx.1.x874jjzuq9jnmlsdrkt69mszj",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-size": "512m"
                }
            },
            "NetworkMode": "default",
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "default",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "bind",
                    "Source": "/captain/generated/static",
                    "Target": "/usr/share/nginx"
                },
                {
                    "Type": "bind",
                    "Source": "/captain/generated/nginx/fake-certs-self-signed",
                    "Target": "/etc/nginx/fake-certs"
                },
                {
                    "Type": "bind",
                    "Source": "/captain/generated/nginx/nginx.conf",
                    "Target": "/etc/nginx/nginx.conf"
                },
                {
                    "Type": "bind",
                    "Source": "/captain/generated/nginx/conf.d",
                    "Target": "/etc/nginx/conf.d"
                },
                {
                    "Type": "bind",
                    "Source": "/captain/data/letencrypt/etc",
                    "Target": "/letencrypt/etc"
                },
                {
                    "Type": "bind",
                    "Source": "/captain/data/nginx-shared",
                    "Target": "/nginx-shared"
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/93999d322ffd73a99ebf0eb716f5100e434a98b10dff595dc3e6a115b2dc0180-init/diff:/var/lib/docker/overlay2/09e1d5f56453c209af8f17a0dcac12c41f64b516a9278beb21deba9e623e532d/diff:/var/lib/docker/overlay2/9ce63ee4dc9d43025f77314965f9354ebc619e242d20536b0d43b247fc67346c/diff:/var/lib/docker/overlay2/c44aa7b8edc6b0e24a71b33d2cbdc42ca1f7c220cde2a476617fa331584fa307/diff",
                "MergedDir": "/var/lib/docker/overlay2/93999d322ffd73a99ebf0eb716f5100e434a98b10dff595dc3e6a115b2dc0180/merged",
                "UpperDir": "/var/lib/docker/overlay2/93999d322ffd73a99ebf0eb716f5100e434a98b10dff595dc3e6a115b2dc0180/diff",
                "WorkDir": "/var/lib/docker/overlay2/93999d322ffd73a99ebf0eb716f5100e434a98b10dff595dc3e6a115b2dc0180/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/captain/generated/nginx/conf.d",
                "Destination": "/etc/nginx/conf.d",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/captain/data/letencrypt/etc",
                "Destination": "/letencrypt/etc",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/captain/data/nginx-shared",
                "Destination": "/nginx-shared",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/captain/generated/static",
                "Destination": "/usr/share/nginx",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/captain/generated/nginx/fake-certs-self-signed",
                "Destination": "/etc/nginx/fake-certs",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/captain/generated/nginx/nginx.conf",
                "Destination": "/etc/nginx/nginx.conf",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "c7ba163512e8",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.17.3",
                "NJS_VERSION=0.3.5",
                "PKG_RELEASE=1~buster"
            ],
            "Cmd": [
                "nginx",
                "-g",
                "daemon off;"
            ],
            "ArgsEscaped": true,
            "Image": "nginx:1",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.swarm.node.id": "qviwn7cf1nt92l2qj76agjvfv",
                "com.docker.swarm.service.id": "a5kzc59pr5d0pi1x6rmyfg1yy",
                "com.docker.swarm.service.name": "captain-nginx",
                "com.docker.swarm.task": "",
                "com.docker.swarm.task.id": "x874jjzuq9jnmlsdrkt69mszj",
                "com.docker.swarm.task.name": "captain-nginx.1.x874jjzuq9jnmlsdrkt69mszj",
                "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
                "randomLabelForceUpdate": "b7fc212d-1c4d-43d7-ac34-ce0a46f432b4"
            },
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "737b227bc2c6cfb5f978a481dec8ef1aeed6324ad6b56e50a817fd05c8a37f16",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/737b227bc2c6",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "captain-overlay-network": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.0.160"
                    },
                    "Links": null,
                    "Aliases": [
                        "c7ba163512e8"
                    ],
                    "NetworkID": "o91fnmqeaccf5njkkih21tlrs",
                    "EndpointID": "d3076942184aa7a031714fa6d72425c9dc5ff3149b2a965416951c35444d986a",
                    "Gateway": "",
                    "IPAddress": "10.0.0.160",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:00:a0",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

`apt` doesn't give me any updates at this stage, the version I'm running:

```
root@caprover:~# docker --version
Docker version 18.09.7, build 2d0083d
```

Looking at https://docs.docker.com/engine/release-notes/ it's a few version behind, would it be worth trying to update to the latest version by adding docker's own repository? ( e.g. https://docs.docker.com/install/linux/docker-ce/ubuntu/ )

**Comment by solomon23** [comment]
It looks like you're running into another problem then :/

**Comment by DBWebdiensten** [comment]
@solomon23 thanks for you're help in this case!

Updating to the latest docker-ce resolved the problem luckily!

**Comment by shazron** [comment]
> From some research is seems like what is happening is that the nginx container isn't getting the mounts it needs. You can verify this with `docker container list` and finding the id of your nginx container and then `docker inspect <nginx id>`. Then look for `Mounts: []`. If it's an empty array, then you've found the problem.

@solomon23 I have the 1107 issue and my docker image `Mounts` is an empty array. I have the latest docker via `apt-get upgrade`, rebooted the server, etc. I am using the sample `node.tar` web-app here as a test: https://github.com/caprover/caprover/tree/master/captain-sample-apps

**Comment by githubsaturn** [comment]
@shazron 
If you `Mounts` is empty, you can't even setup the root domain on the dashboard. Can you confirm if you have set your root domain up on your dashboard?

**Comment by shazron** [comment]
@githubsaturn yup I have my root domain set up, as well as several other wordpress sites that are running, their images have Mounts set up as well, it's only this image deployed by uploading `node.tar` doesn't have it. I updated to caprover 1.7.1 just a couple of hours ago, but the image deployed via uploading `node.tar` was already installed before the upgrade.

**Comment by githubsaturn** [comment]
Of course that image doesn't have it. The `Mounts` that are discussed above is for `captain-nginx` not your app.

**Comment by shazron** [comment]
ok, but I still get 1107 verification failed I thought that was the root of the issue from the above comments. 

SSH'ing into my server and running `curl http://mydomain.com/.well-known/captain-identifier` (mydomain.com is an example) does get me a GUID, but when I try to add the domain in the Caprover UI, I keep getting the 1107 error (verified in the logs as well, going to the same url above). 

I've verified that the DNS has been propagated everywhere via all the domain tools for the domain, pointing to my server.

**Comment by githubsaturn** [comment]
The DNS is probably cached on your container. Either you have to wait a few hours and retry. Or you can simply turn off the domain verification.. Just run this on your server:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by shazron** [comment]
that did the trick, thank you!
To undo, I just delete `/captain/data/config-override.json` right?

**Comment by githubsaturn** [comment]
Yes.

**Comment by ashishdotme** [comment]
I was getting the verification failed error after the upgrade but setting the root domain again fixed it for me though

**Comment by dankore** [comment]
I reboot my server `Sudo reboot` and it worked!

**Comment by sergioisidoro** [comment]
Restarting the captain container (without changing the config) also worked for me. Maybe because it flushed the DNS cache of the container. It's better than rebooting the server, which will create downtime on the other services

**Comment by kinsomicrote** [comment]
Rebooting my server worked for me.
