### ISSUE TITLE
[Deployment Issue] Trying to deploy etherpad-lite

### ISSUE THREAD

**Issue by JanSeW** [caprover/caprover#515]
What is the problem?
Today I tried to deploy my first application with Caprover. For testing I wanted to use Etherpad Lite. Since a configuration file is required, I couldn't deploy it directly from the Dockerfile, so I cloned the Github repository first, created the captain definition and set up the CLI tool. However, the following error message appears:

```
? select the CapRover machine name you want to deploy to: xxx
Ensuring authentication...
? select the app name you want to deploy to: pad
? git branch name to be deployed: (master) (node:9335) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at InputPrompt.onError (/usr/lib/node_modules/caprover/node_modules/inquirer/lib/prompts/input.js:95:35)
    at SafeSubscriber._next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Observable.js:66:21)
    at SafeSubscriber.__tryOrUnsub (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeUntilSubscriber.Subscriber._next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:89:26)
    at TakeUntilSubscriber.Subscriber.next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:66:18)
    at FilterSubscriber._next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/operators/filter.js:52:30)
    at FilterSubscriber.Subscriber.next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:66:18)
    at RefCountSubscriber.Subscriber._next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:89:26)
    at RefCountSubscriber.Subscriber.next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subject.js:60:25)
    at ConnectableSubscriber.Subscriber._next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:89:26)
    at ConnectableSubscriber.Subscriber.next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/usr/lib/node_modules/caprover/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /usr/lib/node_modules/caprover/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:9335) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9335) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If applicable, content of `captain-definition` file:

```  
{
  "schemaVersion": 2,
  "dockerfilePath": "docker/Dockerfile"
 } 
```

Steps to reproduce the problem:

1. Clone the git repository from https://github.com/ether/etherpad-lite
2. Edit the `settings.json.template` and copy it as `settings.json` in the `docker` subfolder.
3. Create the `captain-definition` in the git root as above and run `caprover deploy`

Answers to the following questions if applicable:
- Server: Debain 10; Desktop Manjaro 18.1.0
- 4 GB

**Comment by Hazzard17h** [comment]
Which version of the CLI did you used?
Did you committed the captain-definition file before start deployment? And from which branch?
By default cloning that repo you are in develop branch, but if you didn't specified otherwise, the CLI try to deploy master branch.
