### ISSUE TITLE
Fresh installation, but 1000 : Parser Failed. See internal logs on Monitoring

### ISSUE THREAD

**Issue by tsaqib** [caprover/caprover#550]
A freshly installed CapRover v1.5.2 shows _1000 : Parser Failed. See internal logs_ when navigated to **Monitoring** tab. The stacktrace is as below: 

TypeError: Cannot read property 'trim' of undefined
at Request._callback (/usr/src/app/built/user/system/LoadBalancerManager.js:255:75)
at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
at Request.emit (events.js:198:13)
at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1129:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

Error: Parser Failed. See internal logs...
at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
GET /api/v2/user/system/loadbalancerinfo 304 2.769 ms - -
at Request._callback (/usr/src/app/built/user/system/LoadBalancerManager.js:266:43)
at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
at Request.emit (events.js:198:13)
at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1129:12)

**Comment by JoeX84** [comment]
### Same here. Self hosted on Ubuntu 18.04.3 LTS. Fresh install.

TypeError: Cannot read property 'trim' of undefined
at Request._callback (/usr/src/app/built/user/system/LoadBalancerManager.js:255:75)
at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
at Request.emit (events.js:198:13)
at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1129:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by githubsaturn** [comment]
Fixed in https://github.com/caprover/caprover/commit/faf7940c4d858dd3d76a96a9416f6ae40c84c804

Will be released soon in the next version. Meanwhile, you can go to settings, under "NGINX Configurations", manually apply the same change as seen in the commit above in the config.
