### ISSUE TITLE
Fresh installation, got error in 'Monitoring' Dashboard

### ISSUE THREAD

**Issue by locvfx** [caprover/caprover#565]
What is the problem?
Fresh installation, got an error in 'Monitoring' Dashboard
Please see screenshot here : https://paste.pics/6b605b63601da6b18e00116065c1abe8

Steps to reproduce the problem:
- Fresh installation on new Droplet (Digital Ocean), navigate to 'Monitoring' on web browser
- Additional note: Node JS  v12.13.1
- Your OS and version? : Centos 7.6
- RAM? 1GB

**Error log:**
2019-12-08T16:24:50.769424250Z GET /api/v2/user/system/loadbalancerinfo 304 6.659 ms - -
2019-12-08T16:25:10.792357336Z December 8th 2019, 4:25:10.789 pm    TypeError: Cannot read property 'trim' of undefined
2019-12-08T16:25:10.792411104Z TypeError: Cannot read property 'trim' of undefined
2019-12-08T16:25:10.792422361Z     at Request._callback (/usr/src/app/built/user/system/LoadBalancerManager.js:255:75)
2019-12-08T16:25:10.792430619Z     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
2019-12-08T16:25:10.792438274Z     at Request.emit (events.js:198:13)
2019-12-08T16:25:10.792456192Z     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
2019-12-08T16:25:10.792465036Z     at Request.emit (events.js:198:13)
2019-12-08T16:25:10.792472236Z     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
2019-12-08T16:25:10.792479997Z     at Object.onceWrapper (events.js:286:20)
2019-12-08T16:25:10.792487047Z     at IncomingMessage.emit (events.js:203:15)
2019-12-08T16:25:10.792495372Z     at endReadableNT (_stream_readable.js:1129:12)
2019-12-08T16:25:10.792502836Z     at process._tickCallback (internal/process/next_tick.js:63:19)
2019-12-08T16:25:10.792510321Z December 8th 2019, 4:25:10.789 pm    Error: Parser Failed. See internal logs...
2019-12-08T16:25:10.792518132Z Error: Parser Failed. See internal logs...
2019-12-08T16:25:10.792525299Z     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
2019-12-08T16:25:10.792532801Z     at Request._callback (/usr/src/app/built/user/system/LoadBalancerManager.js:266:43)
2019-12-08T16:25:10.792540199Z     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
2019-12-08T16:25:10.792548129Z     at Request.emit (events.js:198:13)
2019-12-08T16:25:10.792572742Z     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
2019-12-08T16:25:10.792590415Z     at Request.emit (events.js:198:13)
2019-12-08T16:25:10.792601483Z     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
2019-12-08T16:25:10.792612673Z     at Object.onceWrapper (events.js:286:20)
2019-12-08T16:25:10.792622790Z     at IncomingMessage.emit (events.js:203:15)
2019-12-08T16:25:10.792635701Z     at endReadableNT (_stream_readable.js:1129:12)
2019-12-08T16:25:10.792672380Z GET /api/v2/user/system/loadbalancerinfo 304 9.313 ms - -

**Comment by locvfx** [comment]
please help. I don't know what to do to fix this issue, it was a fresh installation.

**Comment by githubsaturn** [comment]
Duplicated of https://github.com/caprover/caprover/issues/550

Already fixed - not released yet. Will be released in 1.6.0
