### ISSUE TITLE
"1000 : Parser Failed. See internal logs" on Monitoring page

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [caprover/caprover#613]
**What is the problem?**
See title - these are the logs:
```
March 6th 2020, 10:36:44.833 am    TypeError: Cannot read property 'trim' of undefined
TypeError: Cannot read property 'trim' of undefined
    at Request._callback (/usr/src/app/built/user/system/LoadBalancerManager.js:255:75)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
March 6th 2020, 10:36:44.834 am    Error: Parser Failed. See internal logs...
Error: Parser Failed. See internal logs...
    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
    at Request._callback (/usr/src/app/built/user/system/LoadBalancerManager.js:266:43)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
```

**Steps to reproduce the problem:**
I didn't do anything in particular (that I am aware of). It just suddenly popped up when I wanted to check netdata.

**Comment by s-h-a-d-o-w** [comment]
Ah, never mind - I just looked at the nginx config that was changed to resolve this and realized that I still had an old one. Maybe I overrode it at some point.
