### ISSUE TITLE
Setup on .dev domain

### ISSUE THREAD

**Issue by marines** [caprover/caprover#621]
**What is the problem?**

Domain verification fails during `serversetup` on a `.dev` TLD. DNS entries are there and caprover doesn't load because of certs. `.dev` domains require HTTPS so no wonder the request from logs 
is failing:

```POST /api/v2/login 200 4.000 ms - 307
GET /api/v2/user/system/info 200 4.680 ms - 95
March 14th 2020, 6:08:39.123 pm    Sending request to http://69cbbff4-d868-4f7c-9941-046f19589daa.[dummydomain].dev:80/.well-known/captain-identifier
March 14th 2020, 6:08:59.148 pm    Error: Verification Failed.
Error: Verification Failed.
    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:88:43)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
POST /api/v2/user/system/changerootdomain 200 20029.859 ms - 62
```

When I curl the URL with certs validation disabled it fetches the file contents. 

Not entirely sure if that can be fixed or it's my fault.

**If applicable, content of `captain-definition` file:**

n/a

**Steps to reproduce the problem:**

- run fresh installation of caprover
- get a .dev domain
- run `caprover serversetup` and follow the setup instructions

**Answers to the following questions where applicable:**
- Your OS and version? Ubuntu 18.04 Server
- RAM? 8G

**Comment by marines** [comment]
It was actually my fault. The container wasn't connected to the same network my DNS server is.
