### ISSUE TITLE
Caprover not booting anymore - Certbot returning `task: non-zero exit (1)`

### ISSUE THREAD

**Issue by jabouchleih** [caprover/caprover#693]
What is the problem?

For the second time now, Caprover crashed and is not starting anymore, even though no configuration was changed and the server has been running for months. 
This results in a "CONNECTION_REFUSED" message, when calling any deployed service or the Caprover UI itself.

`docker service logs captain-certbot -f` does not contain any messages but certbot is always finishing with an error: `task: non-zero exit (1)`.

This is the `docker service ps captain-certbot --no-trunc` output:
```
ID                          NAME                    IMAGE                               NODE                         DESIRED STATE       CURRENT STATE            ERROR                                                              PORTS
ss34pggi3v5o0o5znhagcyls2   captain-certbot.1       caprover/certbot-sleeping:v0.29.1   my.node.my.host   Ready               Ready 1 second ago
ml1oopciy4naz2629psxa1vgq    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   my.node.my.host   Shutdown            Failed 2 seconds ago     "No such container: captain-certbot.1.ml1oopciy4naz2629psxa1vgq"
31vx8p3tjv8af7lzf8uqednhw    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   my.node.my.host   Shutdown            Shutdown 2 seconds ago
vmnts7vm0bpuclshp5o5ufo51    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   my.node.my.host   Shutdown            Failed 2 minutes ago     "No such container: captain-certbot.1.vmnts7vm0bpuclshp5o5ufo51"
mkz18dg8g2tmibcexjygc32g4    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   my.node.my.host   Shutdown            Shutdown 2 minutes ago 
```

These are my logs for the main captain-captain service: 
```
docker service logs captain-captain -f
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | > caprover@0.0.0 start /usr/src/app
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | > node ./bin/www
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | Captain Starting ...
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:08.447 am    Emptying generated and temp folders.
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:08.459 am    Ensuring directories are available on host. Started.
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:08.468 am    Ensuring directories are available on host. Finished.
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:08.475 am    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:08.482 am    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:08.491 am    Copying fake certificates...
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:08.496 am    Setting up NGINX conf file...
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:08.499 am    Locking NGINX configuration reloading...
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:08.526 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:08.530 am    Captain Nginx is already running..
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:11.537 am    Retrying to get NodeID for captain-nginx retry count:0
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:11.542 am    Updating NGINX service...
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:11.556 am    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:16.559 am    NGINX is fully set up and working...
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:16.561 am    Migration not needed, skipping.
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:16.566 am    Captain Certbot is already running..
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:16.572 am    Updating Certbot service...
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:16.596 am    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:18.913 am    **** Captain is initialized and ready to serve you! ****
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:19.924 am    Error: Wrapped: Verification Failed for my.subdomain.domain
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | Error: Wrapped: Verification Failed for my.subdomain.domain
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at errorize (/usr/src/app/built/utils/Logger.js:9:16)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Function.e (/usr/src/app/built/utils/Logger.js:31:19)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:61:32)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Request.emit (events.js:198:13)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at ClientRequest.emit (events.js:198:13)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Socket.socketErrorListener (_http_client.js:392:9)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Socket.emit (events.js:198:13)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at emitErrorNT (internal/streams/destroy.js:91:8)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:33:19.925 am    Error: Wrapped: Error        Error: connect ECONNREFUSED 1.2.3.4:80
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | Error: Wrapped: Error        Error: connect ECONNREFUSED 1.2.3.4:80
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at errorize (/usr/src/app/built/utils/Logger.js:9:16)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Function.e (/usr/src/app/built/utils/Logger.js:31:19)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:62:32)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Request.emit (events.js:198:13)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at ClientRequest.emit (events.js:198:13)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Socket.socketErrorListener (_http_client.js:392:9)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at Socket.emit (events.js:198:13)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    |     at emitErrorNT (internal/streams/destroy.js:91:8)
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:34:02.562 am    Captain health check failed: #1 at my.subdomain.domain
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:34:02.562 am    NGINX health check failed: #1
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:34:18.909 am    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:34:21.244 am    executeCommand Container: captain-certbot certbot renew --non-interactive
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | May 25th 2020, 6:34:23.571 am    Error: Wrapped: Verification Failed for my.subdomain.domain
...
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:29.796 am    Retrying to get NodeID for captain-nginx retry count:4
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:29.800 am    Updating NGINX service...
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:29.811 am    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:34.815 am    NGINX is fully set up and working...
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:34.817 am    Migration not needed, skipping.
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:34.822 am    Captain Certbot is already running..
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:37.829 am    Retrying to get NodeID for captain-certbot retry count:0
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:40.835 am    Retrying to get NodeID for captain-certbot retry count:1
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:40.840 am    Updating Certbot service...
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:43.857 am    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:43.862 am    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:50:46.291 am    **** Captain is initialized and ready to serve you! ****
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:51:46.289 am    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.mw2qs7iltcmb@my.node.my.host    | May 25th 2020, 6:51:48.484 am    executeCommand Container: captain-certbot certbot renew --non-interactive
```
The output above repeats and the service is never starting up.

Steps to reproduce the problem:
 - No configuration changes were made.
 - The node and docker services were running for 34 days now: 
`08:38:50 up 34 days, 17:25,  1 user,  load average: 0.99, 1.32, 1.43`

Answers to the following questions where applicable:
- Your OS and version?
   Debian GNU/Linux 9 (stretch)
- RAM?  
   32GB on a virtual machine

**Comment by githubsaturn** [comment]
What's your disk stats? Do you have enough disk space? 

Can you reboot the system and see if the problem persists?

Last but not least, this line is concerning:
```
captain-captain.1.ms4lvoi5lyr2@my.node.my.host    | Error: Wrapped: Verification Failed for my.subdomain.domain
```

Is your domain server behind a NAT or did you change any DNS settings? Try temporarily disabling the domain verification and see if resolves the problem:
```
docker service scale captain-captain=0

echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json

docker service scale captain-captain=1
```

**Comment by jabouchleih** [comment]
Disk stats are OK, roughly 3/4th used but still more than a 150GB free. 
`overlay        overlay   786G  582G  167G  78% ...`

I just rebooted, didn't have any effect unfortunately. I also tried to remove the certbot and caprover image and restarting from scratch - but that didn't fix it either.

The strange this is, that the logs show that Caprover is ready:
```
captain-captain.1.05deeynetzqg@vmd29421.contaboserver.net    | May 25th 2020, 3:31:30.056 pm    **** Captain is initialized and ready to serve you! ****
captain-captain.1.05deeynetzqg@vmd29421.contaboserver.net    | May 25th 2020, 3:32:30.059 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.05deeynetzqg@vmd29421.contaboserver.net    | May 25th 2020, 3:32:31.971 pm    executeCommand Container: captain-certbot certbot renew --non-interactive
``` 
But curling localhost:443 or :80 results in a CONNECTION_REFUSED. Port 3000 is callable, though. 

I'm still pretty sure that there's something wrong with the captain-certbot service. But without logs I can only guess. 

There were no DNS changes and there's no NAT. `nslookup` inside a container also shows that name resolution is working properly.

**Comment by githubsaturn** [comment]
If certbot keys are corrupted, nginx won't be able to load them. Get the logs from nginx service and see if there is anything that stops nginx from loading up.
```
docker service logs captain-nginx --since 10m
```




PS: instead of curling on `localhost:80` try curling from your local machine to `http://captain.rootdomain.com:80`... The reason is that Docker manipulates the IP table and something localhost:80 doesn't work.

**Comment by jabouchleih** [comment]
That was it, there was an issue with the captain.conf (some invalid cache directive) keeping the NGINX container from starting correctly. 
I don't know why the issue suddenly arose, since the mentioned changes were done a few weeks ago - but that is something I have to take a look at.
Thank you very much 👍

**Comment by rylincoln** [comment]
I think I have a similar issue as @jabouchleih did.  I have the same output for `docker service ps captain-certbot --no-trunc` and for `captain-captain` logs.

My issue began immediately upon a failed one-click app install of n8n with `0.108.0` as the tag for docker.

So maybe it's not exactly same issue - however I have the same output in my logs which led me to this post.

I am not sure where to find the `captain.conf` file in order to look at it - is that inside nginx container and I need to `docker exec -it captain-nginx /bin/bash` to edit it? 

Things I've tried:
`sudo docker service scale  captain-captain=0`
disable `forceRootSsl` config in /captain/data/config-captain.json
`sudo docker service scale  captain-captain=1`
login to myipaddress:3000 and remove the n8n apps via the UI
And then scale=0 re-enable the forceRootSsl config scale=1

Thanks for any direction on getting my captain server back up and running.

**Comment by githubsaturn** [comment]
Try this: https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui

**Comment by rylincoln** [comment]
Thanks - I gave that a try just now to no avail :(

here is output from `docker service logs captain-captain`
```
ubuntu@myipaddress:~$ sudo docker service logs captain-captain 
captain-captain.1.bpiy9lospimo@myipaddress    | 
captain-captain.1.bpiy9lospimo@myipaddress    | > caprover@0.0.0 start /usr/src/app
captain-captain.1.bpiy9lospimo@myipaddress    | > node ./built/server.js
captain-captain.1.bpiy9lospimo@myipaddress    | 
captain-captain.1.bpiy9lospimo@myipaddress    | Captain Starting ...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.608 am    Emptying generated and temp folders.
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.620 am    Ensuring directories are available on host. Started.
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.627 am    Ensuring directories are available on host. Finished.
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.632 am    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.639 am    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.641 am    Migration not needed, skipping.
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.647 am    Copying fake certificates...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.651 am    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.652 am    Locking NGINX configuration reloading...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.680 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.683 am    Captain Nginx is already running.. 
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.700 am    Updating NGINX service...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:06.715 am    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:11.718 am    Pruning containers...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:11.719 am    NGINX is fully set up and working...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:11.723 am    Captain Certbot is already running.. 
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:11.725 am    Updating Certbot service...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:11.734 am    executeCommand Container: captain-certbot certbot certificates --non-interactive 
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:14.236 am    **** Captain is initialized and ready to serve you! ****
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:16.732 am    Pruning containers...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:27.239 am    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:29.236 am    Captain health check failed: #0 at captain.sudomain.rootdomain.com
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:29.237 am    NGINX health check failed: #0
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:30.242 am    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:30.245 am    executeCommand Container: captain-certbot certbot certificates --non-interactive 
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:32.076 am    executeCommand Container: captain-certbot certbot renew --non-interactive 
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:40.374 am    Updating Load Balancer - renewAllCerts
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:40.374 am    Locking NGINX configuration reloading...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:40.398 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:40.399 am    sendReloadSignal...
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:08:40.401 am    Kill HUP Container: 69920acd95601a00ec4be858b96b6ebf5a30e41f4db6d4fd489ab7ae06426c3b
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:09:04.243 am    Captain health check failed: #1 at captain.sudomain.rootdomain.com
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:09:04.243 am    NGINX health check failed: #1
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:09:39.278 am    Captain health check failed: #2 at captain.sudomain.rootdomain.com
captain-captain.1.bpiy9lospimo@myipaddress    | February 16th 2021, 12:09:39.278 am    NGINX health check failed: #2
```

Output from `docker service ps captain-certbot --no-trunc`
 
```
ID                          NAME                    IMAGE                              NODE                DESIRED STATE       CURRENT STATE            ERROR                                                              PORTS
xg3qivqlovc7h8jt5jto3hbvr   captain-certbot.1       caprover/certbot-sleeping:v1.6.0   ip-10-252-151-227   Running             Running 2 minutes ago                                                                       
cdweo4ez6seyjq8steu8661gt    \_ captain-certbot.1   caprover/certbot-sleeping:v1.6.0   ip-10-252-151-227   Shutdown            Failed 2 minutes ago     "No such container: captain-certbot.1.cdweo4ez6seyjq8steu8661gt"   
h3rafcf953nya95nvfv0eail0    \_ captain-certbot.1   caprover/certbot-sleeping:v1.6.0   ip-10-252-151-227   Shutdown            Shutdown 2 minutes ago                                                                      
p669eemup470ysjj52cbadqob    \_ captain-certbot.1   caprover/certbot-sleeping:v1.6.0   ip-10-252-151-227   Shutdown            Failed 5 minutes ago     "No such container: captain-certbot.1.p669eemup470ysjj52cbadqob"   
oyg02x04rm36kyoor4qww90jo    \_ captain-certbot.1   caprover/certbot-sleeping:v1.6.0   ip-10-252-151-227   Shutdown            Shutdown 5 minutes ago 
```

**Comment by githubsaturn** [comment]
What do you see for this?
```
docker service ps captain-nginx --no-trunc
```
and
```
docker service logs captain-nginx
```

**Comment by rylincoln** [comment]
```
➜  ubuntu docker service ps captain-nginx --no-trunc
ID                          NAME                  IMAGE               NODE                DESIRED STATE       CURRENT STATE                 ERROR               PORTS
xh4898tm6wyqh3tf3y4rcgh2z   captain-nginx.1       nginx:1             ipaddress   Running             Running about a minute ago                        *:80->80/tcp,*:443->443/tcp
szkuhgrvv2zi43n6w5pqvpbxl    \_ captain-nginx.1   nginx:1             ipaddress   Shutdown            Shutdown about a minute ago                       
fxe6tx1ec5qlzikje2a5na16t    \_ captain-nginx.1   nginx:1             ipaddress   Shutdown            Shutdown 4 minutes ago                            
iwd4zzkxw6yr12ejozef5qjhe    \_ captain-nginx.1   nginx:1             ipaddress   Shutdown            Shutdown 11 minutes ago                           
pjsqnxt9afqjgmja79yuo6emb    \_ captain-nginx.1   nginx:1             ipaddress   Shutdown            Shutdown 14 minutes ago
```

and

```
➜  ubuntu docker service logs captain-nginx
captain-nginx.1.xh4898tm6wyq@ipaddress    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
captain-nginx.1.xh4898tm6wyq@ipaddress    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
captain-nginx.1.xh4898tm6wyq@ipaddress    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
captain-nginx.1.xh4898tm6wyq@ipaddress    | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
captain-nginx.1.xh4898tm6wyq@ipaddress    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
captain-nginx.1.xh4898tm6wyq@ipaddress    | /docker-entrypoint.sh: Configuration complete; ready for start up
captain-nginx.1.xh4898tm6wyq@ipaddress    | 2021/02/16 00:35:24 [warn] 1#1: conflicting server name "surveys.subdomain.rootdomain.com" on 0.0.0.0:80, ignored
captain-nginx.1.xh4898tm6wyq@ipaddress    | nginx: [warn] conflicting server name "surveys.subdomain.rootdomain.com" on 0.0.0.0:80, ignored
captain-nginx.1.xh4898tm6wyq@ipaddress    | 2021/02/16 00:36:46 [warn] 1#1: conflicting server name "surveys.subdomain.rootdomain.com" on 0.0.0.0:80, ignored
```

**Comment by githubsaturn** [comment]
"conflicting server name" is a bit suspicious. But it doesn't seem like it's causing any major issues. 

Try disabling the healthchecks and see if you can access the dashboard:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by rylincoln** [comment]
Yeah that does smell suspcious.
I had tried the
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

I tried it again just now and cannot access dash or any hosted app via browser.

I can only access dashboard if i set `forceRootSsl: false` - and then use ipaddress:3000

**Comment by githubsaturn** [comment]
Okay, then, there is something fishy going on with your nginx container...

First, see if you have any custom nginx directives here:
```
cat /captain/data/config-captain.json | grep nginx
```

If above is empty, then something in your nginx is broken. Either a network config broke the port mapping, or a firewall etc...

**Comment by rylincoln** [comment]
Yep that is empty. I had gone through the `config-captain.json` file and checked for any custom directives. I suppose this is not actually the same issue as this original post.  Just smelled similar because nginx is broke and similar log output.

**Comment by rylincoln** [comment]
No idea what happened and I'm not nginx / docker savvy enough to diagnose it so - just to close this thread back out - i ended up going for the jugular and resetting up caprover on a new instance. It's all working.  

None of my apps have persistent data so this was actually pretty easy and done faster than all the troubleshooting and whatnot I was trying to do.

thanks @githubsaturn  for trying to help me.

**Comment by githubsaturn** [comment]
Yea, it's really hard to tell what was going wrong in your case as everything looked fine. 

Feel free to file a new issue if you can reproduce the problem.
