### ISSUE TITLE
Installation does not work on different ports.

### ISSUE THREAD

**Issue by LastedGuide** [caprover/caprover#803]
I have a few apps running on docker already, behind an nginx proxy running on the host, and I wanted to run caprover on different ports from 80,443 and 3000. So I first tried to run caprover with this command:
`docker run -p 8002:80 -p 4432:443 -p 3001:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover`

Which didn't work and gave me the error:
```
Installation failed.
Error: Port seems to be closed: 80
    at Request._callback (/usr/src/app/built/utils/CaptainInstaller.js:149:24)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
Which would be expected, so I tried to run it with the `BY_PASS_PROXY_CHECK='TRUE'` variable, which also didn't work and gave me the error:
```
[eval]:1
BY_PASS_PROXY_CHECK=TRUE
^

ReferenceError: TRUE is not defined
    at [eval]:1:1
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:315:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at evalScript (internal/process/execution.js:92:25)
    at internal/main/eval_string.js:23:3
```
Alright, maybe docker removes the apostrophe, so I ran it with this variable: `BY_PASS_PROXY_CHECK="'TRUE'"`
And it runs, but the container immediately exits with nothing in its logs.

So, it suggests a "bad" env variable to set, and when setting it to what may be correct, it wont run at all. I tried stopping nginx and the service that was using port 3000, and it worked completely fine.

**Comment by githubsaturn** [comment]
CapRover only works with the default port. Let's Encrypt relies on these ports to create the SSL certificate.
