### ISSUE TITLE
I can restore backups

### ISSUE THREAD

**Issue by xnardo** [caprover/caprover#819]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

When i try to restore the backup in one new server, i receive this error:

Pulling: caprover/certbot-sleeping:v1.5.0
September 1st 2020, 5:36:18.773 pm    Resuming restoration from backup...
September 1st 2020, 5:36:18.779 pm    Processing the restoration instructions...
September 1st 2020, 5:36:18.780 pm    ***       MULTI-NODE RESTORATION DETECTED        ***
September 1st 2020, 5:36:18.781 pm    *** THIS ERROR IS EXPECTED. SEE DOCS FOR DETAILS ***
September 1st 2020, 5:36:18.782 pm    See backup docs! You must replace the place holder: replace-me-with-new-ip-or-empty-see-docs in /captain/restoring/restore-instructions.json
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! caprover@0.0.0 start: `node ./built/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the caprover@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

In the new server:

1. mkdir /captain
2. cp backup.tar /captain
3. docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover

Answers to the following questions where applicable:

And i would like to know if is possible to make one backup from console (cli), because is necessary for automatisation the change of the server.

**Comment by githubsaturn** [comment]
Did you follow this guide? https://caprover.com/docs/backup-and-restore.html#multi-nodes

**Comment by xnardo** [comment]
Yes, of course, i pass the file backup, generated with the gui from server A (old) to server B (new), and execute: 

mkdir /captain
cp backup.tar /captain
docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover

**Comment by githubsaturn** [comment]
That's the ask! See here:
```
September 1st 2020, 5:36:18.781 pm    *** THIS ERROR IS EXPECTED. SEE DOCS FOR DETAILS ***
September 1st 2020, 5:36:18.782 pm    See backup docs! You must replace the place holder: replace-me-with-new-ip-or-empty-see-docs in /captain/restoring/restore-instructions.json
```

"THIS ERROR IS EXPECTED". You just need to edit this file and enter your info: `/captain/restoring/restore-instructions.json`

**Comment by xnardo** [comment]
Thanks for your answer, but i modify the file and execute again the command and appear the mistake again:

`nano /captain/restoring/restore-instructions.json`

I modified this line with the new IP, server B:

`replace-me-with-new-ip-or-empty-see-docs = NEW IP`

And execute again:
`docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover`

But nothing : (

**Comment by githubsaturn** [comment]
> But nothing : (

What do you mean by nothing? What's the output when you run the command again?

Also, did you copy your private key to the server as well?

**Comment by xnardo** [comment]
Yes, i copied the ssh private key:

`cp .ssh/id_rsa /captain`

And appear the same mistake.

There is way that i can generate my own backup from server A, since console? Maybe i can check the details of the process and try to fix it.

**Comment by xnardo** [comment]
I had try everting and nothing, i leave one video gif with the process, before video i did this (is a cluster):

1. Make one backup from server A, and rename the file to backup.tar
2. Pass the backup to server B (/captain)
3. Pass the id_rsa from server A to B (/captain)
4. Execute the commands in this video > https://lflpt70283qobbf.belugacdn.link/i/97e7pg841544sck0ck8kcw0gccwgg4.gif

**Comment by xnardo** [comment]
Yes, you are right, but now i have this mistake:

```
Pulling: caprover/certbot-sleeping:v1.5.0
September 2nd 2020, 4:08:14.686 pm    Resuming restoration from backup...
September 2nd 2020, 4:08:14.693 pm    Processing the restoration instructions...
September 2nd 2020, 4:08:14.695 pm    Processing restoration instructions is done
September 2nd 2020, 4:08:14.696 pm    Starting swarm at 46.101.127.217:2377
Swarm started: 6f22ilwne62ekrl4ep4csb7qs
September 2nd 2020, 4:08:14.888 pm    Starting restoration, phase-1.
September 2nd 2020, 4:08:14.899 pm    Joining other node to swarm started
September 2nd 2020, 4:08:14.900 pm    Joining other node to swarm: 
September 2nd 2020, 4:08:14.937 pm    Error: connect ECONNREFUSED 127.0.0.1:22
Error: connect ECONNREFUSED 127.0.0.1:22
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
Installation failed.
CaptainError: SSH Connection error!!
    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
    at Client.<anonymous> (/usr/src/app/built/docker/DockerUtils.js:20:53)
    at Client.emit (events.js:314:20)
    at Socket.<anonymous> (/usr/src/app/node_modules/ssh2/lib/client.js:307:10)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  captainErrorType: 1000,
  apiMessage: 'SSH Connection error!!'
}

```

**Comment by githubsaturn** [comment]
It's simply an SSH connection error. Your IP address is incorrect, "127.0.0.1" is localhost. 

Copy the output of `cat /captain/restoring/restore-instructions.json` if you want more help.

**Comment by xnardo** [comment]
Thanks for your answer, of course, is this:

```
{
  "nodesMapping": [
    {
      "newIp": "",
      "oldIp": "46.101.127.199",
      "privateKeyPath": "/captain/id_rsa",
      "user": "root"
    },
    {
      "newIp": "CURRENT_NODE_DONT_CHANGE",
      "oldIp": "46.101.127.90",
      "privateKeyPath": "",
      "user": ""
    }
  ],
  "oldNodesForReference": [
    {
      "nodeData": {
        "nodeId": "epf0djkbgs0q1qacb27txb6hf",
        "type": "worker",
        "isLeader": false,
        "hostname": "test-node1",
        "architecture": "x86_64",
        "operatingSystem": "linux",
        "nanoCpu": 1000000000,
        "memoryBytes": 1033043968,
        "dockerEngineVersion": "19.03.12",
        "ip": "46.101.127.199",
        "state": "ready",
        "status": "active"
      },
      "appsLockOnThisNode": [
        "test-db",
        "test-wordpress"
      ]
    },
    {
      "nodeData": {
        "nodeId": "k23sm0bf3i2sy0z3dt5y5tza3",
        "type": "manager",
        "isLeader": true,
        "hostname": "test-master",
        "architecture": "x86_64",
        "operatingSystem": "linux",
        "nanoCpu": 1000000000,
        "memoryBytes": 1033043968,
        "dockerEngineVersion": "19.03.12",
        "ip": "46.101.127.90",
        "state": "ready",
        "status": "active"
      },
      "appsLockOnThisNode": []
    }
  ]
}

```

**Comment by githubsaturn** [comment]
`"newIp": "46.101.127.217"` is wrong. You need to indicate the IP address of the second node.

**Comment by xnardo** [comment]
The ip "46.101.127.217" is from server B (or new). You say the second node in the cluster, the slave?

**Comment by githubsaturn** [comment]
You had two old servers:
- 46.101.127.199
- 46.101.127.90 [leader]

Now you need two nodes to recreate the cluster. From your logs, you're running the restoration script on "46.101.127.217" which is going to replace your "46.101.127.90". 

Does that make sense?

**Comment by githubsaturn** [comment]
```
"nodesMapping": [
    {
      "newIp": "",    <<<<< ENTER THE NEW SECOND NODE IP HERE
      "oldIp": "46.101.127.199",
      "privateKeyPath": "/captain/id_rsa",
      "user": "root"
    },
    {
      "newIp": "CURRENT_NODE_DONT_CHANGE",
      "oldIp": "46.101.127.90",
      "privateKeyPath": "",
      "user": ""
    }
  ],
```

**Comment by xnardo** [comment]
Tranks. I tried and finally i discover that the id_rsa needs to pass from server slave to new server B:/captain. That is ok, but now i received one new mistake and i have other doubt , **"how i can do if i have 3 nodes, 2 slave, because the key id_rsa needs to move from slaves and in the server master B can be stay only one key?"**... i am confused! : /

New mistake:

```
September 2nd 2020, 9:37:45.321 pm    Error: Wrapped: STDERR: WARNING: No swap limit support

Error: Wrapped: STDERR: WARNING: No swap limit support

    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
    at Readable.<anonymous> (/usr/src/app/built/user/system/BackupManager.js:310:46)
    at Readable.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Readable.push (_stream_readable.js:218:10)
    at SSH2Stream.<anonymous> (/usr/src/app/node_modules/ssh2/lib/Channel.js:254:26)
    at SSH2Stream.emit (events.js:314:20)
    at parsePacket (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:3212:10)
Installation failed.
CaptainError: Error during setup: WARNING: No swap limit support

    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
    at Readable.<anonymous> (/usr/src/app/built/user/system/BackupManager.js:315:61)
    at Readable.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Readable.push (_stream_readable.js:218:10)
    at SSH2Stream.<anonymous> (/usr/src/app/node_modules/ssh2/lib/Channel.js:254:26)
    at SSH2Stream.emit (events.js:314:20)
    at parsePacket (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:3212:10)
    at SSH2Stream._transform (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:701:13) {
  captainErrorType: 1000,
  apiMessage: 'Error during setup: WARNING: No swap limit support\n'
}

```

**Comment by githubsaturn** [comment]
This is Docker related: https://unix.stackexchange.com/questions/342735/docker-warning-no-swap-limit-support

Regarding keys, it's simple. Not sure what the confusion is. Public key needs to be copied to "all nodes". Private key only needs to be copied to the main node so that the main node can connect to other nodes.

**Comment by xnardo** [comment]
Thanks very much!!! : ) Now work with 2 nodes (1 leader and 1 slave). 

My before doubt is when you have 3 nodes (1 leader and 2 slave), in the manual you need pass the private key id_rsa from slave A, to leader C, for example, to the folder /captain. But i think you need pass to the id_rsa from slave B too, my confused is, if you have the id_rsa already in de leader server, from slave A, what happen for the slave B private key?

**Comment by githubsaturn** [comment]
> in the manual you need pass the private key id_rsa from slave A, to leader C
Slave A to leader C? I am not sure if I understood you correctly. But here is what you should do:
- You had 3 servers: A1 (Leader) and B1 (secondary) C1 (secondary)
- You create a backup
- You want to restore, hence you create 3 new nodes:  A2 (Leader) and B2 (secondary) C2 (secondary)
- You set up the public key on ALL 3 new nodes A2, B2 and C2
- You copy id_rsa (private key), from your LOCAL MACHINE to A2 (the new leader node)

**Comment by xnardo** [comment]
Great! now i understand all process and work good, thanks you so much!
