### ISSUE TITLE
Caprover doesnt work after several hours

### ISSUE THREAD

**Issue by telegrambotdev** [caprover/caprover#859]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

Caprover doesnt work after several hours

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Answers to the following questions where applicable:
- Your OS and version? ubuntu 20
- RAM? 2gb

When i deployed caprover,it was worked fibe.but after some hours the webui doesnt loading.

my `docker service logs captain-captain -f` logs are below

```
y.js:100:8)                                 captain-captain.1.5zenx8nddrvs@ns327385    | October 16th 2020, 4:39:15.943 pm    Error: Wrapped: body         undefined
captain-captain.1.5zenx8nddrvs@ns327385    | Error: Wrapped: body         undefined     captain-captain.1.5zenx8nddrvs@ns327385    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)                              captain-captain.1.5zenx8nddrvs@ns327385    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
captain-captain.1.5zenx8nddrvs@ns327385    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:56:42)
captain-captain.1.5zenx8nddrvs@ns327385    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.5zenx8nddrvs@ns327385    |     at Request.emit (events.js:314:20)
captain-captain.1.5zenx8nddrvs@ns327385    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.5zenx8nddrvs@ns327385    |     at ClientRequest.emit (events.js:314:20)
captain-captain.1.5zenx8nddrvs@ns327385    |     at Socket.socketErrorListener (_http_client.js:469:9)
captain-captain.1.5zenx8nddrvs@ns327385    |     at Socket.emit (events.js:314:20)
captain-captain.1.5zenx8nddrvs@ns327385    |     at emitErrorNT (internal/streams/destroy.js:100:8)                                 captain-captain.1.5zenx8nddrvs@ns327385    | October 16th 2020, 4:39:15.945 pm    Error: Wrapped: randomUuid   515892ca-4ec9-4bb7-b48d-5cf6fb52936b
captain-captain.1.5zenx8nddrvs@ns327385    | Error: Wrapped: randomUuid   515892ca-4ec9-4bb7-b48d-5cf6fb52936b
captain-captain.1.5zenx8nddrvs@ns327385    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)                              captain-captain.1.5zenx8nddrvs@ns327385    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
captain-captain.1.5zenx8nddrvs@ns327385    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:57:42)
captain-captain.1.5zenx8nddrvs@ns327385    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.5zenx8nddrvs@ns327385    |     at Request.emit (events.js:314:20)
captain-captain.1.5zenx8nddrvs@ns327385    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)     captain-captain.1.5zenx8nddrvs@ns327385    |     at ClientRequest.emit (events.js:314:20)
captain-captain.1.5zenx8nddrvs@ns327385    |     at Socket.socketErrorListener (_http_client.js:469:9)
captain-captain.1.5zenx8nddrvs@ns327385    |     at Socket.emit (events.js:314:20)
captain-captain.1.5zenx8nddrvs@ns327385    |     at emitErrorNT (internal/streams/destroy.js:100:8)
captain-captain.1.5zenx8nddrvs@ns327385    | October 16th 2020, 4:39:15.949 pm    Captain health check failed: #0 at captain.stfrien74366fyus.caprover.tk                                           captain-captain.1.5zenx8nddrvs@ns327385    | October 16th 2020, 4:39:15.950 pm    NGINX health check failed: #0
```

this is my log

**Comment by telegrambotdev** [comment]
![IMG_20201016_223953_707](https://user-images.githubusercontent.com/20116017/96288155-958ca900-1000-11eb-9914-71344eea25f1.jpg)

**Comment by githubsaturn** [comment]
CapRover is failing to check its own health. It's probably due to a network configuration / port firewall that you have.

You can manually turn off the healthcheck:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by telegrambotdev** [comment]
> CapRover is failing to check its own health. It's probably due to a network configuration / port firewall that you have.
> 
> You can manually turn off the healthcheck:
> 
> ```
> echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
> docker service update captain-captain --force
> ```

whein i typedthat,i got 

`-bash: /captain/data/config-override.json: Permission denied`error

![IMG_20201016_235731_541](https://user-images.githubusercontent.com/20116017/96295397-73e4ef00-100b-11eb-99f8-a7a4db53d1f9.jpg)

**Comment by githubsaturn** [comment]
You need to run it as root

**Comment by telegrambotdev** [comment]
> You need to run it as root

Thank you.
