### ISSUE TITLE
409 error when starting caprover on captain-nginx container after reboot

### ISSUE THREAD

**Issue by LiquidITGuy** [caprover/caprover#860]
First of all, I want to thank you for this helpful program

What is the problem?
After a server upgrade I got a network problem on my server. I fixed the interface network, then rebooted.
Now everything seems good but caprover dont seems to be up again (just same bug than https://github.com/caprover/caprover/issues/761 I think) 
I tried to upgrade docker, to reboot caprover but none of that solves the problem

> errors corresponding to my reboot
```
#docker service ps captain-captain--no-trunc
ID                          NAME                    IMAGE                     NODE                DESIRED STATE       CURRENT STATE            ERROR                                                              PORTS
wz19p16epagmbzn1ttf8x3gg8   captain-captain.1       caprover/caprover:1.8.0   sandox              Running             Running 18 minutes ago
a2y9wdmebsr2rniex8g21rq2i    \_ captain-captain.1   caprover/caprover:1.8.0   sandox              Shutdown            Failed 18 minutes ago    "No such container: captain-captain.1.a2y9wdmebsr2rniex8g21rq2i"
u4mi73201gi2l7ol1yvrsc7qk    \_ captain-captain.1   caprover/caprover:1.8.0   sandox              Shutdown            Failed 27 minutes ago    "No such container: captain-captain.1.u4mi73201gi2l7ol1yvrsc7qk"
r98vq28ge9c3ochclkmewtji9    \_ captain-captain.1   caprover/caprover:1.8.0   sandox              Shutdown            Failed 3 hours ago       "No such container: captain-captain.1.r98vq28ge9c3ochclkmewtji9"
v83rd2eet9dqeqlcmtqys8s3p    \_ captain-captain.1   caprover/caprover:1.8.0   sandox              Shutdown            Failed 3 hours ago       "task: non-zero exit (1)"
```

```
# docker service logs captain-captain --since 60m
captain-captain.1.wz19p16epagm@sandox    |
captain-captain.1.wz19p16epagm@sandox    | > caprover@0.0.0 start /usr/src/app
captain-captain.1.wz19p16epagm@sandox    | > node ./built/server.js
captain-captain.1.wz19p16epagm@sandox    |
captain-captain.1.wz19p16epagm@sandox    | Captain Starting ...
captain-captain.1.wz19p16epagm@sandox    | Overriding skipVerifyingDomains from /captain/data/config-override.json
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:12.693 pm    Emptying generated and temp folders.
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:12.745 pm    Ensuring directories are available on host. Started.
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:12.755 pm    Ensuring directories are available on host. Finished.
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:12.769 pm    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:12.783 pm    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:12.793 pm    Migration not needed, skipping.
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:12.802 pm    Copying fake certificates...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:12.813 pm    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:12.814 pm    Locking NGINX configuration reloading...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:12.870 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:12.878 pm    Captain Nginx is already running..
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:15.886 pm    Retrying to get NodeID for captain-nginx retry count:0
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:15.892 pm    Updating NGINX service...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:15.914 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:20.916 pm    Pruning containers...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:20.917 pm    NGINX is fully set up and working...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:20.921 pm    Captain Certbot is already running..
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:20.925 pm    Updating Certbot service...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:23.943 pm    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:25.934 pm    Pruning containers...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:26.947 pm    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:29.952 pm    Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:32.960 pm    Retrying to get containerId for captain-certbot retry count:3
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:35.964 pm    Retrying to get containerId for captain-certbot retry count:4
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:38.968 pm    Retrying to get containerId for captain-certbot retry count:5
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:38.972 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:41.694 pm    **** Captain is initialized and ready to serve you! ****
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:51.703 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:56:53.180 pm    executeCommand Container: captain-certbot certbot renew --non-interactive
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:12.645 pm    Updating Load Balancer - renewAllCerts
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:12.645 pm    Locking NGINX configuration reloading...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:12.669 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:12.669 pm    sendReloadSignal...
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:15.674 pm    Retrying to get containerId for captain-nginx retry count:0
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:18.677 pm    Retrying to get containerId for captain-nginx retry count:1
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:21.680 pm    Retrying to get containerId for captain-nginx retry count:2
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:24.684 pm    Retrying to get containerId for captain-nginx retry count:3
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:27.688 pm    Retrying to get containerId for captain-nginx retry count:4
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:30.692 pm    Retrying to get containerId for captain-nginx retry count:5
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:33.697 pm    Retrying to get containerId for captain-nginx retry count:6
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:36.700 pm    Retrying to get containerId for captain-nginx retry count:7
captain-captain.1.wz19p16epagm@sandox    | October 17th 2020, 8:57:36.704 pm    Kill HUP Container: eaccea96fec7d40593f5db6716848b5d1d05ea7301998f13dc7ab1e1d0126af6
captain-captain.1.wz19p16epagm@sandox    | (node:26) UnhandledPromiseRejectionWarning: Error: (HTTP code 409) unexpected - Cannot kill container: eaccea96fec7d40593f5db6716848b5d1d05ea7301998f13dc7ab1e1d0126af6: Container eaccea96fec7d40593f5db6716848b5d1d05ea7301998f13dc7ab1e1d0126af6 is not running
captain-captain.1.wz19p16epagm@sandox    |     at /usr/src/app/node_modules/docker-modem/lib/modem.js:301:17
captain-captain.1.wz19p16epagm@sandox    |     at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:331:7)
captain-captain.1.wz19p16epagm@sandox    |     at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:300:5)
captain-captain.1.wz19p16epagm@sandox    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:275:14)
captain-captain.1.wz19p16epagm@sandox    |     at IncomingMessage.emit (events.js:326:22)
captain-captain.1.wz19p16epagm@sandox    |     at endReadableNT (_stream_readable.js:1244:12)
captain-captain.1.wz19p16epagm@sandox    |     at processTicksAndRejections (internal/process/task_queues.js:80:21)
captain-captain.1.wz19p16epagm@sandox    | (Use `node --trace-warnings ...` to show where the warning was created)
captain-captain.1.wz19p16epagm@sandox    | (node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
captain-captain.1.wz19p16epagm@sandox    | (node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
After some investigates, my suspicion goes to captain nginx :

```
# docker service ps captain-nginx --no-trunc
ID                          NAME                  IMAGE               NODE                DESIRED STATE       CURRENT STATE                  ERROR                       PORTS
t5oexlje63av0k34oi5yfxajx   captain-nginx.1       nginx:1             sandox              Ready               Ready less than a second ago
qgwi3qvm9c56nwcwr6cexf62m    \_ captain-nginx.1   nginx:1             sandox              Shutdown            Failed 2 seconds ago           "task: non-zero exit (1)"
at3cf2cij6rxaouj88vlscmgn    \_ captain-nginx.1   nginx:1             sandox              Shutdown            Failed 8 seconds ago           "task: non-zero exit (1)"
so4p0e5upibsltcn6060qk7et    \_ captain-nginx.1   nginx:1             sandox              Shutdown            Failed 15 seconds ago          "task: non-zero exit (1)"
qe6ixnsknt6q3wblyzc8195d3    \_ captain-nginx.1   nginx:1             sandox              Shutdown            Failed 21 seconds ago          "task: non-zero exit (1)"
```
```
# docker service logs captain-nginx --since 10m
captain-nginx.1.tadel8o1uv2w@sandox    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
captain-nginx.1.qatabz5cdls5@sandox    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
captain-nginx.1.tadel8o1uv2w@sandox    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
captain-nginx.1.qatabz5cdls5@sandox    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
captain-nginx.1.q0uv9n9teeza@sandox    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
captain-nginx.1.qatabz5cdls5@sandox    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
captain-nginx.1.tadel8o1uv2w@sandox    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
captain-nginx.1.q0uv9n9teeza@sandox    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
captain-nginx.1.qatabz5cdls5@sandox    | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
captain-nginx.1.q0uv9n9teeza@sandox    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
captain-nginx.1.tadel8o1uv2w@sandox    | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
captain-nginx.1.qatabz5cdls5@sandox    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
captain-nginx.1.tadel8o1uv2w@sandox    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
captain-nginx.1.qatabz5cdls5@sandox    | /docker-entrypoint.sh: Configuration complete; ready for start up
captain-nginx.1.q0uv9n9teeza@sandox    | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
captain-nginx.1.tadel8o1uv2w@sandox    | /docker-entrypoint.sh: Configuration complete; ready for start up
captain-nginx.1.q0uv9n9teeza@sandox    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
captain-nginx.1.q0uv9n9teeza@sandox    | /docker-entrypoint.sh: Configuration complete; ready for start up
captain-nginx.1.qatabz5cdls5@sandox    | 2020/10/17 21:16:32 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
captain-nginx.1.tadel8o1uv2w@sandox    | 2020/10/17 21:16:19 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
captain-nginx.1.qatabz5cdls5@sandox    | nginx: [emerg] invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
captain-nginx.1.q0uv9n9teeza@sandox    | 2020/10/17 21:16:38 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
captain-nginx.1.tadel8o1uv2w@sandox    | nginx: [emerg] invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
captain-nginx.1.q0uv9n9teeza@sandox    | nginx: [emerg] invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
captain-nginx.1.mrcnj8xiytyw@sandox    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
captain-nginx.1.mrcnj8xiytyw@sandox    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
captain-nginx.1.mrcnj8xiytyw@sandox    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
captain-nginx.1.mrcnj8xiytyw@sandox    | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
captain-nginx.1.mrcnj8xiytyw@sandox    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
captain-nginx.1.mrcnj8xiytyw@sandox    | /docker-entrypoint.sh: Configuration complete; ready for start up
captain-nginx.1.mrcnj8xiytyw@sandox    | 2020/10/17 21:16:25 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
captain-nginx.1.mrcnj8xiytyw@sandox    | nginx: [emerg] invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
captain-nginx.1.raolt6qtn3ck@sandox    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
captain-nginx.1.raolt6qtn3ck@sandox    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
captain-nginx.1.raolt6qtn3ck@sandox    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
captain-nginx.1.raolt6qtn3ck@sandox    | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
captain-nginx.1.raolt6qtn3ck@sandox    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
captain-nginx.1.raolt6qtn3ck@sandox    | /docker-entrypoint.sh: Configuration complete; ready for start up
captain-nginx.1.raolt6qtn3ck@sandox    | 2020/10/17 21:16:45 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
captain-nginx.1.raolt6qtn3ck@sandox    | nginx: [emerg] invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
```
And that's where I am now.
if you can help me it would be great :) 
If you have any questions I could try to answer

Answers to the following questions where applicable:
- Your OS and version?
- 10gb ram
- 2 core 4 thread per core
- 200 gb ssd
- Docker version 19.03.13, build 4484c46d9d
- Debian 10 on virtual machine

Worked since april and been upgraded (no bug on upgrades)

**Comment by githubsaturn** [comment]
```
captain-nginx.1.raolt6qtn3ck@sandox    | 2020/10/17 21:16:45 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
captain-nginx.1.raolt6qtn3ck@sandox    | nginx: [emerg] invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/captain.conf:1428
```

You've probably changed an nginx configuration that resulted in a bad config. 
```
docker service scale captain-captain=0
cp   /captain/data/config-captain.json   /captain/data/backup-config-captain.json
nano /captain/data/config-captain.json
# find the custom nginx config that you've added an entirely remove it
# IMPORTANT: make sure the json is still valid!!
# Save the file and exit
docker service scale captain-captain=1
```

**Comment by LiquidITGuy** [comment]
It solves the problem but I am really confused because all seems work up to times I reboot the server.

For other people in the same case, here is what I've done : 
1. Check and fix my network interface into the network files and start network configuration (changing name after server upgrade)
2. restart the server
3. follow the instructions of @githubsaturn 
4. fix my bad file changes (I forget to remove the , at the end of the line so the config file was not valid then it removed the config file 🗡️) 
5. restart

And that's it

thank you very much for you help

**Comment by githubsaturn** [comment]
Alternatively you can do this: https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui
