### ISSUE TITLE
Unable to Deploy Any Application. Error: No NodeId was found.

### ISSUE THREAD

**Issue by shashankklenty** [caprover/caprover#930]
**What is the problem?**

I am getting the error below when deploying any OCA, be it official or custom.

![Screenshot from 2020-12-08 21-50-03](https://user-images.githubusercontent.com/41108860/101509977-5a26af00-399f-11eb-84dd-fbaf9a8101c5.png)

On checking the `captain-captain` service logs I get the following on what I believe to be `POST /api/v2/user/apps/appDefinitions/update`.

```
Error: No NodeId was found. Try again in a minute...
    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
    at /usr/src/app/built/user/ServiceManager.js:494:64
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Notes about setup that might help:
1. This is a single node setup. No clustering across ec2 machines. Here is the leader node info:
![Screenshot from 2020-12-08 21-59-12](https://user-images.githubusercontent.com/41108860/101512350-e8e7fb80-39a0-11eb-987e-dbc9fc35f1e7.png)
1. I have setup a remote docker registry to docker hub but disabled push. The purpose of this was to solve the rate limit problem.

Answers to the following questions where applicable:
- **Your OS and version?** Ubuntu 20.04.1 LTS on AWS EC2
- **RAM?** 8GB

**Comment by githubsaturn** [comment]
Please get CapRover logs when this happens
```
docker service logs captain-captain --since 5m
```

**Comment by shashankklenty** [comment]
Hey it seems the problem has solved itself. Now the builds are working. However no changes were made from our end in the setup so its really confusing. I searched logs for when the build occurred. Hope this of some help:
```
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:10:38.219 pm    Registering app started: asdasd-rmq
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:10:38.272 pm    Building docker image. This might take a few minutes...
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:10:38.634 pm    Docker Auth is found. Pushing the image...
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:10:57.739 pm    Ensure service inited and Updated for: asdasd-rmq
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:10:57.743 pm    Check if service is running: srv-captain--asdasd-rmq
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:10:57.881 pm    Creating service srv-captain--asdasd-rmq with default image, we will update image later
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:10:57.975 pm    Updating service srv-captain--asdasd-rmq with image registry-1.docker.io/klenty/img-captain-asdasd-rmq:0
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:11:00.157 pm    Updating Load Balancer - ServiceManager
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:11:00.157 pm    Locking NGINX configuration reloading...
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:11:00.273 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:11:00.273 pm    sendReloadSignal...
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:11:00.294 pm    Kill HUP Container: 83cfafde0973f60d5348dd2d9c88e14a8c668345c4f8815860ed684e0617077f
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:11:00.357 pm    AppName is saved: asdasd-rmq
captain-captain.1.e4tx2je9ept5@REDACTED    | POST /api/v2/user/apps/appDefinitions/register 200 22138.996 ms - 61
captain-captain.1.e4tx2je9ept5@REDACTED    | GET /api/v2/user/apps/appDefinitions 200 16.109 ms - 111588
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:11:00.703 pm    Updating app started: asdasd-rmq
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:11:00.723 pm    Error: No NodeId was found. Try again in a minute...
captain-captain.1.e4tx2je9ept5@REDACTED    | Error: No NodeId was found. Try again in a minute...
captain-captain.1.e4tx2je9ept5@REDACTED    |     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
captain-captain.1.e4tx2je9ept5@REDACTED    |     at /usr/src/app/built/user/ServiceManager.js:494:64
captain-captain.1.e4tx2je9ept5@REDACTED    |     at runMicrotasks (<anonymous>)
captain-captain.1.e4tx2je9ept5@REDACTED    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
captain-captain.1.e4tx2je9ept5@REDACTED    | POST /api/v2/user/apps/appDefinitions/update 200 20.556 ms - 87
captain-captain.1.e4tx2je9ept5@REDACTED    | December 8th 2020, 4:11:03.157 pm    Pruning containers...
captain-captain.1.e4tx2je9ept5@REDACTED    | GET /api/v2/user/registries 200 4.121 ms - 345
captain-captain.1.e4tx2je9ept5@REDACTED    | GET /api/v2/user/system/nodes 200 95.061 ms - 351
captain-captain.1.e4tx2je9ept5@REDACTED    | POST /api/v2/user/registries/setpush 200 26.267 ms - 62
captain-captain.1.e4tx2je9ept5@REDACTED    | GET /api/v2/user/registries 200 5.323 ms - 309
captain-captain.1.e4tx2je9ept5@REDACTED    | GET /api/v2/user/apps/appDefinitions 200 25.817 ms - 111588
captain-captain.1.e4tx2je9ept5@REDACTED    | GET /api/v2/user/apps/appDefinitions 304 26.586 ms - -
```

**Comment by githubsaturn** [comment]
Looks like it's was a weird Docker issue where it returned an empty string for NodeID of your service:
https://github.com/caprover/caprover/blob/9094d116635a44ef4f596e426cf2486310937428/src/docker/DockerApi.ts#L111

**Comment by IamJeffG** [comment]
Just want to say I see this error very often, when I deploy apps using an automated script that hits the caprover server API.  Specifically it happens when I call `/api/v2/user/apps/appDefinitions/update` very soon (like, under 0.5 second) after creating the app at `/api/v2/user/apps/appDefinitions/register`.  You can see in @shashankklenty 's logs above, and my logs below, that the "Updating service" is at most a couple hundred milliseconds after "Ensure service ...".

Having looked at [`ServiceManager.updateAppDefinition`,](https://github.com/caprover/caprover/blob/922ed3f/src/user/ServiceManager.ts) this error could only happen when `hasPersistentData` is true.  It seems that registering the app creates the Swarm task object, but does not wait to ensure the app got assigned to a Node. The follow-up call began also before the app got assigned to a Swarm Node: the `/update` call tries to lookup the Node,  but since it's not assigned, it raises this error.

In my case, I even first `GET /api/v2/user/apps/appData/testapp` and check `isAppBuilding` is not true, before calling `/update`, but that is not enough to capture the Swarm node assignment.


```
$ docker service logs captain-captain
captain-captain.1.iisq6dh0glum    | GET /api/v2/user/apps/appData/testapp 200 3.061 ms - 630
captain-captain.1.iisq6dh0glum    | July 21st 2026, 3:10:26.106 pm    Ensure service inited and Updated for: testapp
captain-captain.1.iisq6dh0glum    | July 21st 2026, 3:10:26.107 pm    Check if service is running: srv-captain--testapp
captain-captain.1.iisq6dh0glum    | July 21st 2026, 3:10:26.109 pm    Creating service srv-captain--testapp with default image, we will update image later
captain-captain.1.iisq6dh0glum    | July 21st 2026, 3:10:26.113 pm    Updating service srv-captain--testapp with image caprover/caprover-placeholder-app:latest
captain-captain.1.iisq6dh0glum    | GET /api/v2/user/apps/appData/testapp 200 3.461 ms - 663
captain-captain.1.iisq6dh0glum    | GET /api/v2/user/apps/appDefinitions 200 6.170 ms - 19276
captain-captain.1.iisq6dh0glum    | July 21st 2026, 3:10:26.163 pm    Updating app started: testapp
captain-captain.1.iisq6dh0glum    | July 21st 2026, 3:10:26.175 pm    
captain-captain.1.iisq6dh0glum    | Error: No NodeId was found. Try again in a minute...
captain-captain.1.iisq6dh0glum    | Error: No NodeId was found. Try again in a minute...
captain-captain.1.iisq6dh0glum    |     at ApiStatusCodes.createError (/usr/src/app/built/api/ApiStatusCodes.js:11:16)
captain-captain.1.iisq6dh0glum    |     at /usr/src/app/built/user/ServiceManager.js:500:64
captain-captain.1.iisq6dh0glum    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
captain-captain.1.iisq6dh0glum    | POST /api/v2/user/apps/appDefinitions/update 200 14.247 ms - 87
captain-captain.1.iisq6dh0glum    | July 21st 2026, 3:10:26.640 pm    Pruning containers...
```

For the moment I'm going to be attempting the simple workaround of adding a small `sleep` before making the second API call, in hopes that's enough for Swarm to catch up.

**Comment by githubsaturn** [comment]
Make sure you are not passing `isDetachedBuild` as `true` when creating a new app. Beyond that, yea a tiny sleep would definitely help resolving the issue.

**Comment by githubsaturn** [comment]
FWIW even docker's engine code is full of sleep calls and retries because of uncertainty in scheduling with the OS. 

https://github.com/search?q=repo%3Amoby%2Fmoby+sleep+language%3AGo++NOT+is%3Aarchived&type=code&l=Go
