### ISSUE TITLE
toomanyrequests: You have reached your pull rate limit.

### ISSUE THREAD

**Issue by MattiaFailla** [caprover/caprover#963]
I am unable to start monitoring and to deploy other applications due to the limit imposed by docker. Is there an easy way to overcome this problem or to log-in into the docker account?
I know this problem is not strictly related to caprover, but I would like to point out that this problem will occur more and more often for other developers (especially if you use caprover in a dev environment where often release/pull request from docker happens) so a definite solution would be a really thumb up!
```
captain-captain.1.oe5xzg035adq@Ubuntu-1804-bionic-64-minimal    | January 10th 2021, 7:37:22.703 am    Error: (HTTP code 500) server error - toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit 
captain-captain.1.oe5xzg035adq@Ubuntu-1804-bionic-64-minimal    | Error: (HTTP code 500) server error - toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit 
captain-captain.1.oe5xzg035adq@Ubuntu-1804-bionic-64-minimal    |     at /usr/src/app/node_modules/docker-modem/lib/modem.js:301:17
captain-captain.1.oe5xzg035adq@Ubuntu-1804-bionic-64-minimal    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:328:9)
captain-captain.1.oe5xzg035adq@Ubuntu-1804-bionic-64-minimal    |     at IncomingMessage.emit (events.js:327:22)
captain-captain.1.oe5xzg035adq@Ubuntu-1804-bionic-64-minimal    |     at endReadableNT (_stream_readable.js:1327:12)
captain-captain.1.oe5xzg035adq@Ubuntu-1804-bionic-64-minimal    |     at processTicksAndRejections (internal/process/task_queues.js:80:21)
captain-captain.1.oe5xzg035adq@Ubuntu-1804-bionic-64-minimal    | POST /api/v2/user/system/netdata 500 1081.404 ms - 21
```

**Comment by githubsaturn** [comment]
There are a number of things that you can do to alleviate the issue:
https://github.com/caprover/caprover/issues/906
