### ISSUE TITLE
[Deployment Issue] Enable HTTPS with an app fail 1107 message

### ISSUE THREAD

**Issue by clementvp** [caprover/caprover#985]
What is the problem?

Try to install a one click apps (qBitorrent) with https, but https enable fail with 1107 message.

If applicable, content of `captain-definition` file:  

Just try to install qBitorrent one click app from the oneClick app catalog.

Steps to reproduce the problem:
Install qBitorrent as a one click app.  
Wait to have a functionnal app.
Try to enable HTTPS.
Get a 1107 message.

Answers to the following questions if applicable:
- Your OS and version?
Ubuntu 20 LTS
- RAM?
4Gb

But every others app (mine including) works with https enabled.  

And yes root domain is enabled with HTTPS and everything works fine... Except this app :/ .

App has been tested on another Caprover instance (Ubuntu 16.08, Caprover 1.6.1) and everything work fine (HTTPS successfully enabled)

Maybe CapVersion or Os Version (I know Ubuntu 20 is unstable for now) ?

Get this message from the captain log:  
 
``` 
January 26th 2021, 6:57:15.343 pm    Error: Wrapped: Verification Failed for toto.maclean.ovh
Error: Wrapped: Verification Failed for toto.maclean.ovh
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:54:42)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
January 26th 2021, 6:57:15.345 pm    Error: Wrapped: Error        null
Error: Wrapped: Error        null
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:55:42)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
January 26th 2021, 6:57:15.346 pm    Error: Wrapped: body         <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>

Error: Wrapped: body         <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>

    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:56:42)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
January 26th 2021, 6:57:15.348 pm    Error: Wrapped: randomUuid   ea4ca375-8292-4db3-a027-991687aff240
Error: Wrapped: randomUuid   ea4ca375-8292-4db3-a027-991687aff240
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:19)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:57:42)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
January 26th 2021, 6:57:15.349 pm    Error: Verification Failed.
Error: Verification Failed.
    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
    at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:58:57)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
POST /api/v2/user/apps/appDefinitions/enablebasedomainssl 200 1030.353 ms - 62
GET /api/v2/user/apps/appData/toto 304 5.300 ms - -
GET /api/v2/user/apps/appData/toto/logs?encoding=hex 200 36.814 ms - 13148
GET /api/v2/user/apps/appData/toto 304 8.649 ms - -
GET /api/v2/user/apps/appData/toto/logs?encoding=hex 200 33.267 ms - 13148`
```

**Comment by githubsaturn** [comment]
Try using another name for your app. Does it work? If so, the issue is probably related to cached DNS records.

You can also disable domain verification by running 
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by ClementVanPeuter** [comment]
Another name for the app does not work :/ 
What disabled domain verification do ? 

After disabling it can I get HTTPS trough let'sencrypt ? (Click on the https enable button)

**Comment by clementvp** [comment]
`echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force`  

Works like a charm.  
Thank you. Strange behaviour anyway with some domain verifications :/
